// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appHealth: () => typedError<string, AppError>(__TAURI_INVOKE("app_health")),
	loadAppConfig: () => typedError<AppConfig_Serialize, AppError>(__TAURI_INVOKE("load_app_config")),
	saveAppConfig: (config: AppConfig_Deserialize) => typedError<AppConfig_Serialize, AppError>(__TAURI_INVOKE("save_app_config", { config })),
	diagnosticsStatus: () => typedError<DiagnosticsStatus, AppError>(__TAURI_INVOKE("diagnostics_status")),
	setDiagnosticsEnabled: (enabled: boolean) => typedError<DiagnosticsStatus, AppError>(__TAURI_INVOKE("set_diagnostics_enabled", { enabled })),
	autostartStatus: () => typedError<AutostartStatus, AppError>(__TAURI_INVOKE("autostart_status")),
	setAutostartEnabled: (enabled: boolean) => typedError<AutostartStatus, AppError>(__TAURI_INVOKE("set_autostart_enabled", { enabled })),
	globalHotkeyStatus: () => typedError<HotkeyStatus_Serialize, AppError>(__TAURI_INVOKE("global_hotkey_status")),
	saveGlobalHotkeys: (settings: KeyEventItem_Deserialize[]) => typedError<HotkeyStatus_Serialize, AppError>(__TAURI_INVOKE("save_global_hotkeys", { settings })),
	generateQrCode: (content: string) => typedError<QrCodeImage, AppError>(__TAURI_INVOKE("generate_qr_code", { content })),
	scanScreenQr: () => typedError<QrScanResult, AppError>(__TAURI_INVOKE("scan_screen_qr")),
	fetchCertificate: (request: CertificateFetchRequest) => typedError<CertificateFetchResult, AppError>(__TAURI_INVOKE("fetch_certificate", { request })),
	calculateCertificateSha256: (pem: string) => typedError<string[], AppError>(__TAURI_INVOKE("calculate_certificate_sha256", { pem })),
	/**
	 *  Trigger the one-time native authorization dialog and, on success, install
	 *  the passwordless elevation launcher. No admin password is stored.
	 */
	tunRequestElevation: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("tun_request_elevation")),
	/**
	 *  Remove the passwordless elevation launcher + sudoers drop-in and clear the
	 *  session grant.
	 */
	tunRevokeElevation: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("tun_revoke_elevation")),
	connectActiveProfile: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("connect_active_profile")),
	disconnectCore: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("disconnect_core")),
	restartCore: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("restart_core")),
	runtimeStatus: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("runtime_status")),
	systemProxyStatus: () => typedError<SystemProxyStatusResponse, AppError>(__TAURI_INVOKE("system_proxy_status")),
	setSystemProxyMode: (mode: SysProxyType) => typedError<SystemProxyStatusResponse, AppError>(__TAURI_INVOKE("set_system_proxy_mode", { mode })),
	tunStatus: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("tun_status")),
	setTunEnabled: (enabled: boolean) => typedError<TunStatus, AppError>(__TAURI_INVOKE("set_tun_enabled", { enabled })),
	loadDnsSettings: () => typedError<DnsSettings_Serialize, AppError>(__TAURI_INVOKE("load_dns_settings")),
	saveDnsSettings: (settings: DnsSettings_Deserialize) => typedError<DnsSettings_Serialize, AppError>(__TAURI_INVOKE("save_dns_settings", { settings })),
	loadFullConfigTemplates: () => typedError<FullConfigTemplateItem_Serialize[], AppError>(__TAURI_INVOKE("load_full_config_templates")),
	saveFullConfigTemplate: (template: FullConfigTemplateItem_Deserialize) => typedError<FullConfigTemplateItem_Serialize, AppError>(__TAURI_INVOKE("save_full_config_template", { template })),
	listProfiles: (subid: string | null, filter: string | null) => typedError<ProfileListItem_Serialize[], AppError>(__TAURI_INVOKE("list_profiles", { subid, filter })),
	getProfile: (indexId: string) => typedError<{
	profile: ProfileItem_Serialize,
	profileEx: ProfileExItem_Serialize,
	serverStat: ServerStatItem,
	isActive: boolean,
} | null, AppError>(__TAURI_INVOKE("get_profile", { indexId })),
	saveProfile: (profile: ProfileItem_Deserialize) => typedError<ProfileListItem_Serialize, AppError>(__TAURI_INVOKE("save_profile", { profile })),
	deleteProfiles: (indexIds: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_profiles", { indexIds })),
	copyProfiles: (indexIds: string[]) => typedError<ProfileListItem_Serialize[], AppError>(__TAURI_INVOKE("copy_profiles", { indexIds })),
	exportProfileShareLinks: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_share_links", { indexIds })),
	exportProfileShareLinksBase64: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_share_links_base64", { indexIds })),
	exportProfileInnerLinks: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_inner_links", { indexIds })),
	exportProfileClientConfig: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_client_config", { indexIds })),
	setActiveProfile: (indexId: string) => typedError<ProfileListItem_Serialize, AppError>(__TAURI_INVOKE("set_active_profile", { indexId })),
	moveProfile: (subid: string | null, indexId: string, action: MoveAction, position: number | null) => typedError<ProfileListItem_Serialize[], AppError>(__TAURI_INVOKE("move_profile", { subid, indexId, action, position })),
	sortProfiles: (subid: string | null, sortKey: ProfileSortKey, ascending: boolean) => typedError<ProfileListItem_Serialize[], AppError>(__TAURI_INVOKE("sort_profiles", { subid, sortKey, ascending })),
	moveProfilesToGroup: (indexIds: string[], subid: string) => typedError<number, AppError>(__TAURI_INVOKE("move_profiles_to_group", { indexIds, subid })),
	dedupeProfiles: (subid: string | null, keepOlder: boolean | null) => typedError<ProfileDedupeResult, AppError>(__TAURI_INVOKE("dedupe_profiles", { subid, keepOlder })),
	listGroupChildCandidates: (currentIndexId: string | null, filter: string | null) => typedError<GroupChildCandidate[], AppError>(__TAURI_INVOKE("list_group_child_candidates", { currentIndexId, filter })),
	validateGroupProfile: (profile: ProfileItem_Deserialize) => typedError<GroupValidationResult, AppError>(__TAURI_INVOKE("validate_group_profile", { profile })),
	previewGroupProfile: (profile: ProfileItem_Deserialize) => typedError<GroupPreview, AppError>(__TAURI_INVOKE("preview_group_profile", { profile })),
	saveGroupProfile: (profile: ProfileItem_Deserialize) => typedError<ProfileListItem_Serialize, AppError>(__TAURI_INVOKE("save_group_profile", { profile })),
	listSubscriptions: () => typedError<SubItem_Serialize[], AppError>(__TAURI_INVOKE("list_subscriptions")),
	getSubscription: (id: string) => typedError<{
	Id: string,
	Remarks: string,
	Url: string,
	MoreUrl: string,
	Enabled: boolean,
	UserAgent: string,
	Sort: number,
	Filter?: string | null,
	AutoUpdateInterval: number,
	UpdateTime: number | null,
	ConvertTarget?: string | null,
	PrevProfile?: string | null,
	NextProfile?: string | null,
	PreSocksPort?: number | null,
	Memo?: string | null,
} | null, AppError>(__TAURI_INVOKE("get_subscription", { id })),
	saveSubscription: (item: SubItem_Deserialize) => typedError<SubItem_Serialize, AppError>(__TAURI_INVOKE("save_subscription", { item })),
	deleteSubscriptions: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_subscriptions", { ids })),
	importProfilesFromText: (text: string, subid: string | null, isSub: boolean) => typedError<ImportProfilesResult, AppError>(__TAURI_INVOKE("import_profiles_from_text", { text, subid, isSub })),
	importProfilesFromFile: (path: string, subid: string | null, isSub: boolean) => typedError<ImportProfilesResult, AppError>(__TAURI_INVOKE("import_profiles_from_file", { path, subid, isSub })),
	updateSubscriptions: (subid: string | null, preferProxy: boolean, proxyUrl: string | null) => typedError<SubscriptionUpdateResult, AppError>(__TAURI_INVOKE("update_subscriptions", { subid, preferProxy, proxyUrl })),
	runDueSubscriptionUpdates: (preferProxy: boolean, proxyUrl: string | null) => typedError<SubscriptionUpdateResult, AppError>(__TAURI_INVOKE("run_due_subscription_updates", { preferProxy, proxyUrl })),
	listRoutings: () => typedError<RoutingItem_Serialize[], AppError>(__TAURI_INVOKE("list_routings")),
	getRouting: (id: string) => typedError<{
	Id: string,
	Remarks: string,
	Url: string,
	RuleSet: RulesItem_Serialize[],
	RuleNum: number,
	Enabled: boolean,
	Locked: boolean,
	CustomIcon: string,
	CustomRulesetPath4Singbox: string,
	DomainStrategy: string,
	DomainStrategy4Singbox: string,
	Sort: number,
	IsActive: boolean,
} | null, AppError>(__TAURI_INVOKE("get_routing", { id })),
	saveRouting: (item: RoutingItem_Deserialize) => typedError<RoutingItem_Serialize, AppError>(__TAURI_INVOKE("save_routing", { item })),
	deleteRoutings: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_routings", { ids })),
	setActiveRouting: (id: string) => typedError<RoutingItem_Serialize, AppError>(__TAURI_INVOKE("set_active_routing", { id })),
	saveRoutingRule: (routingId: string, rule: RulesItem_Deserialize) => typedError<RoutingItem_Serialize, AppError>(__TAURI_INVOKE("save_routing_rule", { routingId, rule })),
	deleteRoutingRules: (routingId: string, ruleIds: string[]) => typedError<RoutingItem_Serialize, AppError>(__TAURI_INVOKE("delete_routing_rules", { routingId, ruleIds })),
	moveRoutingRule: (routingId: string, ruleId: string, action: MoveAction, position: number | null) => typedError<RoutingItem_Serialize, AppError>(__TAURI_INVOKE("move_routing_rule", { routingId, ruleId, action, position })),
	importRoutingTemplates: (preferProxy: boolean, proxyUrl: string | null, importAdvancedRules: boolean) => typedError<RoutingItem_Serialize[], AppError>(__TAURI_INVOKE("import_routing_templates", { preferProxy, proxyUrl, importAdvancedRules })),
	applyRegionalPreset: (presetType: PresetType, preferProxy: boolean, proxyUrl: string | null) => typedError<PresetApplyResult, AppError>(__TAURI_INVOKE("apply_regional_preset", { presetType, preferProxy, proxyUrl })),
	clashListProxies: () => typedError<ClashProxiesSnapshot, AppError>(__TAURI_INVOKE("clash_list_proxies")),
	clashTestDelay: (proxyNames: string[]) => typedError<ClashDelayTestResult[], AppError>(__TAURI_INVOKE("clash_test_delay", { proxyNames })),
	clashSelectProxy: (groupName: string, proxyName: string) => typedError<ClashProxiesSnapshot, AppError>(__TAURI_INVOKE("clash_select_proxy", { groupName, proxyName })),
	clashListConnections: () => typedError<ClashConnectionsSnapshot, AppError>(__TAURI_INVOKE("clash_list_connections")),
	clashCloseConnection: (connectionId: string | null) => typedError<ClashConnectionsSnapshot, AppError>(__TAURI_INVOKE("clash_close_connection", { connectionId })),
	clashSetRuleMode: (mode: RuleMode) => typedError<AppConfig_Serialize, AppError>(__TAURI_INVOKE("clash_set_rule_mode", { mode })),
	clashReloadConfig: (path: string | null) => typedError<null, AppError>(__TAURI_INVOKE("clash_reload_config", { path })),
	clashStartMonitor: () => typedError<ClashMonitorStatus, AppError>(__TAURI_INVOKE("clash_start_monitor")),
	clashStopMonitor: () => typedError<ClashMonitorStatus, AppError>(__TAURI_INVOKE("clash_stop_monitor")),
	runSpeedtest: (action: SpeedActionType, indexIds: string[]) => typedError<SpeedtestRunResult, AppError>(__TAURI_INVOKE("run_speedtest", { action, indexIds })),
	cancelSpeedtest: () => typedError<SpeedtestStatus, AppError>(__TAURI_INVOKE("cancel_speedtest")),
	speedtestStatus: () => typedError<SpeedtestStatus, AppError>(__TAURI_INVOKE("speedtest_status")),
	appUpdateStatus: () => typedError<AppUpdaterStatus, AppError>(__TAURI_INVOKE("app_update_status")),
	checkAppUpdate: () => typedError<AppUpdateCheckResult, AppError>(__TAURI_INVOKE("check_app_update")),
	installAppUpdate: () => typedError<AppUpdateInstallResult, AppError>(__TAURI_INVOKE("install_app_update")),
	updateStatus: () => typedError<UpdateStatus, AppError>(__TAURI_INVOKE("update_status")),
	saveUpdatePreferences: (preRelease: boolean, selectedTargetIds: string[]) => typedError<UpdateStatus, AppError>(__TAURI_INVOKE("save_update_preferences", { preRelease, selectedTargetIds })),
	loadRulesetGeoSources: () => typedError<RulesetGeoSourceSettings, AppError>(__TAURI_INVOKE("load_ruleset_geo_sources")),
	saveRulesetGeoSources: (settings: RulesetGeoSourceSettings) => typedError<RulesetGeoSourceSettings, AppError>(__TAURI_INVOKE("save_ruleset_geo_sources", { settings })),
	checkUpdates: (preRelease: boolean, selectedTargetIds: string[], preferProxy: boolean, proxyUrl: string | null) => typedError<UpdateRunResult, AppError>(__TAURI_INVOKE("check_updates", { preRelease, selectedTargetIds, preferProxy, proxyUrl })),
	downloadUpdates: (preRelease: boolean, selectedTargetIds: string[], preferProxy: boolean, proxyUrl: string | null) => typedError<UpdateRunResult, AppError>(__TAURI_INVOKE("download_updates", { preRelease, selectedTargetIds, preferProxy, proxyUrl })),
	manualAppUpdateLinks: (preRelease: boolean, preferProxy: boolean, proxyUrl: string | null) => typedError<ManualAppUpdateLinks, AppError>(__TAURI_INVOKE("manual_app_update_links", { preRelease, preferProxy, proxyUrl })),
	/**
	 *  Re-install a core binary from the packaged seed (`{resource_dir}/core-seeds/<core>/`)
	 *  into `bin/<core>/`. This is the recovery action behind the missing-core prompt: the
	 *  startup seed copy already runs automatically, but this lets the UI re-run it on demand
	 *  when the binary is absent (e.g. cleared bin dir, antivirus removal, or a skipped first run).
	 */
	installCoreSeed: (coreType: CoreType) => typedError<CoreSeedInstallResult, AppError>(__TAURI_INVOKE("install_core_seed", { coreType })),
	backupStatus: () => typedError<BackupStatus_Serialize, AppError>(__TAURI_INVOKE("backup_status")),
	backupSaveWebdavSettings: (settings: WebDavItem_Deserialize) => typedError<WebDavItem_Serialize, AppError>(__TAURI_INVOKE("backup_save_webdav_settings", { settings })),
	backupCreateLocal: (outputPath: string | null) => typedError<BackupOperationResult, AppError>(__TAURI_INVOKE("backup_create_local", { outputPath })),
	backupRestoreLocal: (inputPath: string) => typedError<BackupRestoreResult_Serialize, AppError>(__TAURI_INVOKE("backup_restore_local", { inputPath })),
	backupWebdavCheck: (settings: WebDavItem_Deserialize) => typedError<BackupOperationResult, AppError>(__TAURI_INVOKE("backup_webdav_check", { settings })),
	backupWebdavPush: (settings: WebDavItem_Deserialize) => typedError<BackupRemoteResult, AppError>(__TAURI_INVOKE("backup_webdav_push", { settings })),
	backupWebdavPull: (settings: WebDavItem_Deserialize) => typedError<BackupRestoreResult_Serialize, AppError>(__TAURI_INVOKE("backup_webdav_pull", { settings })),
	/**
	 *  Report the window decoration this build should render. Only Windows gets the
	 *  custom borderless title bar; macOS and Linux keep their native frame, and the
	 *  web fallback (no Tauri runtime) resolves to `none` on the frontend.
	 */
	getWindowChromeConfig: () => typedError<WindowChromeConfig, AppError>(__TAURI_INVOKE("get_window_chrome_config")),
	/**
	 *  Tint the Windows Acrylic blur material to match the in-app light/dark theme.
	 *  The frontend drives its own (non-system) theme, so this command sets the tint
	 *  explicitly per mode to keep the native material's base color aligned with the
	 *  UI. Acrylic has a single variant; light and dark differ only by `color`.
	 * 
	 *  Non-Windows platforms are a no-op: window effects are an OS capability, and
	 *  macOS / Linux / web fall back to the flat CSS neutral-gray veil.
	 */
	setWindowAcrylic: (dark: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_window_acrylic", { dark })),
	ipcDemoRoundTrip: (request: DemoRequest) => typedError<DemoResponse, AppError>(__TAURI_INVOKE("ipc_demo_round_trip", { request })),
};

/** Events */
export const events = {
	appEvent: makeEvent<AppEvent>("app-event"),
	invalidateEvent: makeEvent<InvalidateEvent>("invalidate-event"),
	transientStreamEvent: makeEvent<TransientStreamEvent>("transient-stream-event"),
};

/* Types */
export type AppConfig = AppConfig_Serialize | AppConfig_Deserialize;

export type AppConfig_Deserialize = {
	IndexId?: string,
	SubIndexId?: string,
	CoreBasicItem?: CoreBasicItem_Deserialize,
	TunModeItem?: TunModeItem,
	KcpItem?: KcpItem,
	GrpcItem?: GrpcItem_Deserialize,
	RoutingBasicItem?: RoutingBasicItem,
	GUIItem?: GuiItem,
	MsgUIItem?: MsgUiItem_Deserialize,
	UIItem?: UiItem_Deserialize,
	ConstItem?: ConstItem_Deserialize,
	SpeedTestItem?: SpeedTestItem_Deserialize,
	Mux4RayItem?: Mux4RayItem_Deserialize,
	Mux4SboxItem?: Mux4SboxItem_Deserialize,
	HysteriaItem?: HysteriaItem,
	ClashUIItem?: ClashUiItem,
	SystemProxyItem?: SystemProxyItem_Deserialize,
	WebDavItem?: WebDavItem_Deserialize,
	CheckUpdateItem?: CheckUpdateItem_Deserialize,
	DiagnosticsItem?: DiagnosticsItem_Deserialize,
	Fragment4RayItem?: Fragment4RayItem_Deserialize,
	Inbound?: InItem_Deserialize[],
	GlobalHotkeys?: KeyEventItem_Deserialize[],
	CoreTypeItem?: CoreTypeItem[],
	SimpleDNSItem?: SimpleDnsItem_Deserialize,
};

export type AppConfig_Serialize = {
	IndexId: string,
	SubIndexId: string,
	CoreBasicItem: CoreBasicItem_Serialize,
	TunModeItem: TunModeItem,
	KcpItem: KcpItem,
	GrpcItem: GrpcItem_Serialize,
	RoutingBasicItem: RoutingBasicItem,
	GUIItem: GuiItem,
	MsgUIItem: MsgUiItem_Serialize,
	UIItem: UiItem_Serialize,
	ConstItem: ConstItem_Serialize,
	SpeedTestItem: SpeedTestItem_Serialize,
	Mux4RayItem: Mux4RayItem_Serialize,
	Mux4SboxItem: Mux4SboxItem_Serialize,
	HysteriaItem: HysteriaItem,
	ClashUIItem: ClashUiItem,
	SystemProxyItem: SystemProxyItem_Serialize,
	WebDavItem: WebDavItem_Serialize,
	CheckUpdateItem: CheckUpdateItem_Serialize,
	DiagnosticsItem: DiagnosticsItem_Serialize,
	Fragment4RayItem: Fragment4RayItem_Serialize,
	Inbound: InItem_Serialize[],
	GlobalHotkeys: KeyEventItem_Serialize[],
	CoreTypeItem: CoreTypeItem[],
	SimpleDNSItem: SimpleDnsItem_Serialize,
};

export type AppError = { kind: "eventEmit"; message: string } | { kind: "autostart"; message: string } | { kind: "configLoad"; message: string } | { kind: "configSave"; message: string } | { kind: "backup"; message: string } | { kind: "certificate"; message: string } | { kind: "clash"; message: string } | { kind: "database"; message: string } | { kind: "dns"; message: DnsCommandError } | { kind: "group"; message: string } | { kind: "hotkey"; message: string } | { kind: "preset"; message: string } | { kind: "profile"; message: string } | { kind: "qr"; message: string } | { kind: "export"; message: string } | { kind: "missingCore"; message: MissingCoreError } | { kind: "runtime"; message: string } | { kind: "routing"; message: string } | { kind: "speedtest"; message: string } | { kind: "sudo"; message: string } | { kind: "subscription"; message: string } | { kind: "sysProxy"; message: string } | { kind: "state"; message: string } | { kind: "template"; message: string } | { kind: "tun"; message: string } | { kind: "update"; message: string };

export type AppEvent = { kind: "notice"; payload: AppNotice } | { kind: "selectTab"; payload: ShellTabTarget };

export type AppNotice = {
	level: AppNoticeLevel,
	title: string,
	message: string | null,
};

export type AppNoticeLevel = "info" | "warning" | "error";

export type AppUpdateCheckResult = {
	currentVersion: string,
	update: AppUpdateInfo | null,
};

export type AppUpdateInfo = {
	currentVersion: string,
	version: string,
	date: string | null,
	body: string | null,
	downloadUrl: string,
};

export type AppUpdateInstallResult = {
	state: AppUpdateInstallState,
	currentVersion: string,
	installedVersion: string | null,
};

export type AppUpdateInstallState = "installed" | "noUpdate";

export type AppUpdaterState = "ready" | "unconfigured" | "unsupported" | "error";

export type AppUpdaterStatus = {
	currentVersion: string,
	state: AppUpdaterState,
	message: string | null,
};

export type AutostartPlatform = "windows" | "linux" | "macos" | "other";

export type AutostartStatus = {
	enabled: boolean,
	platform: AutostartPlatform,
	artifactKind: string | null,
	artifactPath: string | null,
	artifactName: string | null,
};

export type BackupOperationResult = {
	path: string | null,
	bytes: number | null,
	message: string,
};

export type BackupRemoteResult = {
	path: string | null,
	remotePath: string,
	bytes: number | null,
	message: string,
};

export type BackupRestoreResult = BackupRestoreResult_Serialize | BackupRestoreResult_Deserialize;

export type BackupRestoreResult_Deserialize = {
	path: string,
	restoredConfig: AppConfig_Deserialize,
	message: string,
};

export type BackupRestoreResult_Serialize = {
	path: string,
	restoredConfig: AppConfig_Serialize,
	message: string,
};

export type BackupStatus = BackupStatus_Serialize | BackupStatus_Deserialize;

export type BackupStatus_Deserialize = {
	defaultBackupPath: string,
	backupDir: string,
	webDavItem: WebDavItem_Deserialize,
};

export type BackupStatus_Serialize = {
	defaultBackupPath: string,
	backupDir: string,
	webDavItem: WebDavItem_Serialize,
};

export type CertificateFetchRequest = {
	address: string,
	port: number,
	serverName: string | null,
	allowInsecure: boolean,
	includeChain: boolean,
};

export type CertificateFetchResult = {
	pem: string,
	sha256: string[],
	chainCount: number,
	warning: string | null,
};

export type CheckUpdateItem = CheckUpdateItem_Serialize | CheckUpdateItem_Deserialize;

export type CheckUpdateItem_Deserialize = {
	CheckPreReleaseUpdate?: boolean,
	SelectedCoreTypes?: string[] | null,
};

export type CheckUpdateItem_Serialize = {
	CheckPreReleaseUpdate: boolean,
	SelectedCoreTypes?: string[] | null,
};

export type ClashConnectionItem = {
	id: string | null,
	network: string | null,
	connectionType: string | null,
	host: string,
	source: string,
	destination: string,
	upload: number | null,
	download: number | null,
	start: string,
	chains: string[],
	rule: string | null,
	rulePayload: string | null,
	process: string | null,
	processPath: string | null,
};

export type ClashConnectionsSnapshot = {
	downloadTotal: number | null,
	uploadTotal: number | null,
	connections: ClashConnectionItem[],
};

export type ClashDelayTestResult = {
	name: string,
	delay: number | null,
	message: string | null,
};

export type ClashMonitorState = "running" | "stopped" | "failed";

export type ClashMonitorStatus = {
	state: ClashMonitorState,
	running: boolean,
	stale: boolean,
	message: string | null,
};

export type ClashProxiesSnapshot = {
	groups: ClashProxyGroup[],
	allNodes: ClashProxyNode[],
	ruleMode: RuleMode,
};

export type ClashProxyGroup = {
	name: string,
	proxyType: string,
	now: string | null,
	nodes: ClashProxyNode[],
};

export type ClashProxyNode = {
	name: string,
	proxyType: string,
	delay: number | null,
	delayLabel: string,
	udp: boolean,
	active: boolean,
	testable: boolean,
};

export type ClashTrafficEvent = {
	up: number | null,
	down: number | null,
};

export type ClashUiItem = {
	RuleMode?: RuleMode,
	EnableIPv6?: boolean,
	EnableMixinContent?: boolean,
	ProxiesSorting?: number,
	ProxiesAutoRefresh?: boolean,
	ProxiesAutoDelayTestInterval?: number,
	ConnectionsAutoRefresh?: boolean,
	ConnectionsRefreshInterval?: number,
	ConnectionsColumnItem?: ColumnItem[],
};

export type ColumnItem = {
	Name?: string,
	Width?: number,
	Index?: number,
};

export type ConfigType = number;

export type ConstItem = ConstItem_Serialize | ConstItem_Deserialize;

export type ConstItem_Deserialize = {
	SubConvertUrl?: string | null,
	CdnBaseUrl?: string | null,
	CdnReleaseIndexUrl?: string | null,
	CdnCoreManifestUrl?: string | null,
	GeoSourceUrl?: string | null,
	SrsSourceUrl?: string | null,
	RouteRulesTemplateSourceUrl?: string | null,
};

export type ConstItem_Serialize = {
	SubConvertUrl?: string | null,
	CdnBaseUrl?: string | null,
	CdnReleaseIndexUrl?: string | null,
	CdnCoreManifestUrl?: string | null,
	GeoSourceUrl?: string | null,
	SrsSourceUrl?: string | null,
	RouteRulesTemplateSourceUrl?: string | null,
};

export type CoreBasicItem = CoreBasicItem_Serialize | CoreBasicItem_Deserialize;

export type CoreBasicItem_Deserialize = {
	LogEnabled?: boolean,
	Loglevel?: string,
	MuxEnabled?: boolean,
	DefAllowInsecure?: boolean,
	DefFingerprint?: string,
	DefUserAgent?: string,
	SendThrough?: string | null,
	BindInterface?: string | null,
	EnableFragment?: boolean,
	EnableCacheFile4Sbox?: boolean,
};

export type CoreBasicItem_Serialize = {
	LogEnabled: boolean,
	Loglevel: string,
	MuxEnabled: boolean,
	DefAllowInsecure: boolean,
	DefFingerprint: string,
	DefUserAgent: string,
	SendThrough?: string | null,
	BindInterface?: string | null,
	EnableFragment: boolean,
	EnableCacheFile4Sbox: boolean,
};

export type CoreSeedInstallResult = {
	coreType: CoreType,
	status: CoreSeedInstallStatus,
	installedFiles: string[],
};

export type CoreSeedInstallStatus = "installed" | "alreadyInstalled" | "seedMissing";

export type CoreState = "disconnected" | "connecting" | "connected" | "disconnecting";

export type CoreStateEvent = {
	state: CoreState,
	activeProfileId: string | null,
	mainPid: number | null,
	prePid: number | null,
	runningCoreType: CoreType | null,
};

export type CoreType = number;

export type CoreTypeItem = {
	ConfigType?: ConfigType,
	CoreType?: CoreType,
};

export type DemoRequest = {
	message: string,
};

export type DemoResponse = {
	echoedMessage: string,
	messageLength: number,
};

export type DiagnosticsItem = DiagnosticsItem_Serialize | DiagnosticsItem_Deserialize;

export type DiagnosticsItem_Deserialize = {
	Enabled?: boolean,
	AnonymousInstallId?: string,
	EndpointUrl?: string | null,
};

export type DiagnosticsItem_Serialize = {
	Enabled: boolean,
	AnonymousInstallId?: string,
	EndpointUrl?: string | null,
};

export type DiagnosticsStatus = {
	enabled: boolean,
	deliveryConfigured: boolean,
	queuedEvents: number,
	queuedBytes: number,
};

export type DnsCommandError = {
	message: string,
	issues: DnsValidationIssue[],
};

export type DnsItem = DnsItem_Serialize | DnsItem_Deserialize;

export type DnsItem_Deserialize = {
	Id?: string,
	Remarks?: string,
	Enabled?: boolean,
	CoreType?: CoreType,
	UseSystemHosts?: boolean,
	NormalDNS?: string | null,
	TunDNS?: string | null,
	DomainStrategy4Freedom?: string | null,
	DomainDNSAddress?: string | null,
};

export type DnsItem_Serialize = {
	Id: string,
	Remarks: string,
	Enabled: boolean,
	CoreType: CoreType,
	UseSystemHosts: boolean,
	NormalDNS?: string | null,
	TunDNS?: string | null,
	DomainStrategy4Freedom?: string | null,
	DomainDNSAddress?: string | null,
};

export type DnsSettings = DnsSettings_Serialize | DnsSettings_Deserialize;

export type DnsSettingsDefaults = {
	singboxNormalDns: string,
	singboxTunDns: string,
};

export type DnsSettings_Deserialize = {
	simpleDnsItem: SimpleDnsItem_Deserialize,
	singboxDnsItem: DnsItem_Deserialize,
	defaults: DnsSettingsDefaults,
};

export type DnsSettings_Serialize = {
	simpleDnsItem: SimpleDnsItem_Serialize,
	singboxDnsItem: DnsItem_Serialize,
	defaults: DnsSettingsDefaults,
};

export type DnsValidationIssue = {
	field: string,
	message: string,
};

export type ExportProfilesFormat = "shareLinks" | "shareLinksBase64" | "innerLinks" | "clientConfig";

export type ExportProfilesRequest = {
	indexIds: string[],
	format: ExportProfilesFormat,
};

export type ExportProfilesResult = {
	text: string,
	count: number,
	format: ExportProfilesFormat,
};

export type Fragment4RayItem = Fragment4RayItem_Serialize | Fragment4RayItem_Deserialize;

export type Fragment4RayItem_Deserialize = {
	Packets?: string | null,
	Length?: string | null,
	Interval?: string | null,
};

export type Fragment4RayItem_Serialize = {
	Packets?: string | null,
	Length?: string | null,
	Interval?: string | null,
};

export type FullConfigTemplateItem = FullConfigTemplateItem_Serialize | FullConfigTemplateItem_Deserialize;

export type FullConfigTemplateItem_Deserialize = {
	Id?: string,
	Remarks?: string,
	Enabled?: boolean,
	CoreType?: CoreType,
	Config?: string | null,
	TunConfig?: string | null,
	AddProxyOnly?: boolean | null,
	ProxyDetour?: string | null,
};

export type FullConfigTemplateItem_Serialize = {
	Id: string,
	Remarks: string,
	Enabled: boolean,
	CoreType: CoreType,
	Config?: string | null,
	TunConfig?: string | null,
	AddProxyOnly?: boolean | null,
	ProxyDetour?: string | null,
};

export type GlobalHotkey = number;

export type GlobalHotkeyAction = {
	action: GlobalHotkey,
	label: string,
};

export type GlobalHotkeyBinding = {
	action: GlobalHotkey,
	accelerator: string,
};

export type GridOrientation = number;

export type GroupChildCandidate = {
	indexId: string,
	remarks: string,
	address: string,
	configType: ConfigType,
	subid: string,
	isGroup: boolean,
	selectable: boolean,
	reason: string | null,
};

export type GroupPreview = {
	validation?: GroupValidationResult,
	singboxRoutes?: GroupPreviewRoute[],
};

export type GroupPreviewBalancer = {
	tag: string,
	selectors: string[],
	strategy: string | null,
	fallbackTag: string | null,
};

export type GroupPreviewRoute = {
	tag: string,
	kind: string,
	dialerProxy: string | null,
	downloadDialerProxy: string | null,
	detour: string | null,
	outbounds: string[],
};

export type GroupValidationResult = {
	valid?: boolean,
	normalizedChildItems?: string,
	childIndexIds?: string[],
	errors?: string[],
	warnings?: string[],
};

export type GrpcItem = GrpcItem_Serialize | GrpcItem_Deserialize;

export type GrpcItem_Deserialize = {
	IdleTimeout?: number | null,
	HealthCheckTimeout?: number | null,
	PermitWithoutStream?: boolean | null,
	InitialWindowsSize?: number | null,
};

export type GrpcItem_Serialize = {
	IdleTimeout?: number | null,
	HealthCheckTimeout?: number | null,
	PermitWithoutStream?: boolean | null,
	InitialWindowsSize?: number | null,
};

export type GuiItem = {
	AutoRun?: boolean,
	EnableStatistics?: boolean,
	DisplayRealTimeSpeed?: boolean,
	KeepOlderDedupl?: boolean,
	AutoUpdateInterval?: number,
	TrayMenuServersLimit?: number,
	EnableHWA?: boolean,
	EnableLog?: boolean,
};

export type HotkeyStatus = HotkeyStatus_Serialize | HotkeyStatus_Deserialize;

export type HotkeyStatus_Deserialize = {
	actions: GlobalHotkeyAction[],
	settings: KeyEventItem_Deserialize[],
	registered: GlobalHotkeyBinding[],
};

export type HotkeyStatus_Serialize = {
	actions: GlobalHotkeyAction[],
	settings: KeyEventItem_Serialize[],
	registered: GlobalHotkeyBinding[],
};

export type HysteriaItem = {
	UpMbps?: number,
	DownMbps?: number,
	HopInterval?: number,
};

export type ImportProfilesResult = {
	imported?: number,
	skipped?: number,
	removedExisting?: number,
	subid?: string | null,
	importedIndexIds?: string[],
};

export type InItem = InItem_Serialize | InItem_Deserialize;

export type InItem_Deserialize = {
	LocalPort?: number,
	Protocol?: string,
	UdpEnabled?: boolean,
	SniffingEnabled?: boolean,
	DestOverride?: string[] | null,
	RouteOnly?: boolean,
	AllowLANConn?: boolean,
	NewPort4Lan?: boolean,
	User?: string,
	Pass?: string,
	SecondLocalPortEnabled?: boolean,
};

export type InItem_Serialize = {
	LocalPort: number,
	Protocol: string,
	UdpEnabled: boolean,
	SniffingEnabled: boolean,
	DestOverride?: string[] | null,
	RouteOnly: boolean,
	AllowLANConn: boolean,
	NewPort4Lan: boolean,
	User: string,
	Pass: string,
	SecondLocalPortEnabled: boolean,
};

export type InvalidateEvent = {
	keys: QueryInvalidation[],
};

export type KcpItem = {
	Mtu?: number,
	Tti?: number,
	UplinkCapacity?: number,
	DownlinkCapacity?: number,
	CwndMultiplier?: number,
	MaxSendingWindow?: number,
};

export type KeyEventItem = KeyEventItem_Serialize | KeyEventItem_Deserialize;

export type KeyEventItem_Deserialize = {
	EGlobalHotkey?: GlobalHotkey,
	Alt?: boolean,
	Control?: boolean,
	Shift?: boolean,
	KeyCode?: number | null,
};

export type KeyEventItem_Serialize = {
	EGlobalHotkey: GlobalHotkey,
	Alt: boolean,
	Control: boolean,
	Shift: boolean,
	KeyCode?: number | null,
};

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

export type LogLineEvent = {
	id: number,
	level: LogLevel,
	line: string,
};

export type ManualAppUpdateDownload = {
	name: string,
	kind: string,
	version: string,
	url: string,
	sha256: string | null,
	bytes: number | null,
};

export type ManualAppUpdateLinks = {
	currentVersion: string,
	remoteVersion: string | null,
	hasUpdate: boolean,
	releaseIndexUrl: string,
	channel: string,
	target: string,
	arch: string,
	downloads: ManualAppUpdateDownload[],
};

export type MissingCoreError = {
	message: string,
	coreType: CoreType,
	searchDir: string,
	candidates: string[],
	downloadUrl: string,
};

export type MoveAction = number;

export type MsgUiItem = MsgUiItem_Serialize | MsgUiItem_Deserialize;

export type MsgUiItem_Deserialize = {
	MainMsgFilter?: string | null,
	AutoRefresh?: boolean | null,
};

export type MsgUiItem_Serialize = {
	MainMsgFilter?: string | null,
	AutoRefresh?: boolean | null,
};

export type MultipleLoad = number;

export type Mux4RayItem = Mux4RayItem_Serialize | Mux4RayItem_Deserialize;

export type Mux4RayItem_Deserialize = {
	Concurrency?: number | null,
	XudpConcurrency?: number | null,
	XudpProxyUDP443?: string | null,
};

export type Mux4RayItem_Serialize = {
	Concurrency?: number | null,
	XudpConcurrency?: number | null,
	XudpProxyUDP443?: string | null,
};

export type Mux4SboxItem = Mux4SboxItem_Serialize | Mux4SboxItem_Deserialize;

export type Mux4SboxItem_Deserialize = {
	Protocol?: string,
	MaxConnections?: number,
	Padding?: boolean | null,
};

export type Mux4SboxItem_Serialize = {
	Protocol: string,
	MaxConnections: number,
	Padding?: boolean | null,
};

export type PresetApplyResult = {
	presetType: PresetType,
	geoSourceUrl: string | null,
	srsSourceUrl: string | null,
	routeRulesTemplateSourceUrl: string | null,
	singboxDnsFetched: boolean,
	simpleDnsFetched: boolean,
	fallbackCustomDnsEnabled: boolean,
};

export type PresetType = number;

export type ProfileDedupeResult = {
	total: number,
	kept: number,
	removedIndexIds: string[],
};

export type ProfileExItem = ProfileExItem_Serialize | ProfileExItem_Deserialize;

export type ProfileExItem_Deserialize = {
	IndexId?: string,
	Delay?: number,
	Speed?: number | null,
	Sort?: number,
	Message?: string | null,
	IpInfo?: string | null,
};

export type ProfileExItem_Serialize = {
	IndexId: string,
	Delay: number,
	Speed: number | null,
	Sort: number,
	Message?: string | null,
	IpInfo?: string | null,
};

export type ProfileItem = ProfileItem_Serialize | ProfileItem_Deserialize;

export type ProfileItem_Deserialize = {
	IndexId?: string,
	ConfigType?: ConfigType,
	CoreType?: CoreType | null,
	ConfigVersion?: number,
	Subid?: string,
	IsSub?: boolean,
	PreSocksPort?: number | null,
	DisplayLog?: boolean,
	Remarks?: string,
	Address?: string,
	Port?: number,
	Password?: string,
	Username?: string,
	Network?: string,
	StreamSecurity?: string,
	AllowInsecure?: string,
	Sni?: string,
	Alpn?: string,
	Fingerprint?: string,
	PublicKey?: string,
	ShortId?: string,
	SpiderX?: string,
	Mldsa65Verify?: string,
	MuxEnabled?: boolean | null,
	Cert?: string,
	CertSha?: string,
	EchConfigList?: string,
	Finalmask?: string,
	ProtocolExtra?: ProtocolExtraItem_Deserialize,
	TransportExtra?: TransportExtraItem_Deserialize,
};

export type ProfileItem_Serialize = {
	IndexId: string,
	ConfigType: ConfigType,
	CoreType?: CoreType | null,
	ConfigVersion: number,
	Subid: string,
	IsSub: boolean,
	PreSocksPort?: number | null,
	DisplayLog: boolean,
	Remarks: string,
	Address: string,
	Port: number,
	Password: string,
	Username: string,
	Network: string,
	StreamSecurity: string,
	AllowInsecure: string,
	Sni: string,
	Alpn: string,
	Fingerprint: string,
	PublicKey: string,
	ShortId: string,
	SpiderX: string,
	Mldsa65Verify: string,
	MuxEnabled?: boolean | null,
	Cert: string,
	CertSha: string,
	EchConfigList: string,
	Finalmask: string,
	ProtocolExtra: ProtocolExtraItem_Serialize,
	TransportExtra: TransportExtraItem_Serialize,
};

export type ProfileListItem = ProfileListItem_Serialize | ProfileListItem_Deserialize;

export type ProfileListItem_Deserialize = {
	profile: ProfileItem_Deserialize,
	profileEx: ProfileExItem_Deserialize,
	serverStat: ServerStatItem,
	isActive: boolean,
};

export type ProfileListItem_Serialize = {
	profile: ProfileItem_Serialize,
	profileEx: ProfileExItem_Serialize,
	serverStat: ServerStatItem,
	isActive: boolean,
};

export type ProfileSortKey = "sort" | "configType" | "remarks" | "address" | "port" | "network" | "streamSecurity" | "delay" | "speed" | "ipInfo" | "subid";

export type ProtocolExtraItem = ProtocolExtraItem_Serialize | ProtocolExtraItem_Deserialize;

export type ProtocolExtraItem_Deserialize = {
	Uot?: boolean | null,
	CongestionControl?: string | null,
	AlterId?: string | null,
	VmessSecurity?: string | null,
	Flow?: string | null,
	VlessEncryption?: string | null,
	SsMethod?: string | null,
	WgPublicKey?: string | null,
	WgPresharedKey?: string | null,
	WgInterfaceAddress?: string | null,
	WgAllowedIps?: string | null,
	WgReserved?: string | null,
	WgMtu?: number | null,
	SalamanderPass?: string | null,
	UpMbps?: number | null,
	DownMbps?: number | null,
	Ports?: string | null,
	HopInterval?: string | null,
	InsecureConcurrency?: number | null,
	NaiveQuic?: boolean | null,
	GroupType?: string | null,
	ChildItems?: string | null,
	SubChildItems?: string | null,
	Filter?: string | null,
	MultipleLoad?: MultipleLoad | null,
};

export type ProtocolExtraItem_Serialize = {
	Uot?: boolean | null,
	CongestionControl?: string | null,
	AlterId?: string | null,
	VmessSecurity?: string | null,
	Flow?: string | null,
	VlessEncryption?: string | null,
	SsMethod?: string | null,
	WgPublicKey?: string | null,
	WgPresharedKey?: string | null,
	WgInterfaceAddress?: string | null,
	WgAllowedIps?: string | null,
	WgReserved?: string | null,
	WgMtu?: number | null,
	SalamanderPass?: string | null,
	UpMbps?: number | null,
	DownMbps?: number | null,
	Ports?: string | null,
	HopInterval?: string | null,
	InsecureConcurrency?: number | null,
	NaiveQuic?: boolean | null,
	GroupType?: string | null,
	ChildItems?: string | null,
	SubChildItems?: string | null,
	Filter?: string | null,
	MultipleLoad?: MultipleLoad | null,
};

export type QrCodeImage = {
	mimeType: string,
	svg: string,
};

export type QrScanResult = {
	status: QrScanStatus,
	text: string | null,
	source: string,
	message: string | null,
};

export type QrScanStatus = "found" | "notFound" | "unavailable";

export type QueryInvalidation = {
	queryKey: string[],
	reason: string,
};

export type RoutingBasicItem = {
	DomainStrategy?: string,
	DomainStrategy4Singbox?: string,
	RoutingIndexId?: string,
};

export type RoutingItem = RoutingItem_Serialize | RoutingItem_Deserialize;

export type RoutingItem_Deserialize = {
	Id?: string,
} | {
	id?: string,
} & {
	Remarks?: string,
} | {
	remarks?: string,
} & {
	Url?: string,
} | {
	url?: string,
} & {
	RuleSet?: RulesItem_Deserialize[],
} | {
	ruleSet?: RulesItem_Deserialize[],
} & {
	RuleNum?: number,
} | {
	ruleNum?: number,
} & {
	Enabled?: boolean,
} | {
	enabled?: boolean,
} & {
	Locked?: boolean,
} | {
	locked?: boolean,
} & {
	CustomIcon?: string,
} | {
	customIcon?: string,
} & {
	CustomRulesetPath4Singbox?: string,
} | {
	customRulesetPath4Singbox?: string,
} & {
	DomainStrategy?: string,
} | {
	domainStrategy?: string,
} & {
	DomainStrategy4Singbox?: string,
} | {
	domainStrategy4Singbox?: string,
} & {
	Sort?: number,
} | {
	sort?: number,
} & {
	IsActive?: boolean,
} | {
	isActive?: boolean,
};

export type RoutingItem_Serialize = {
	Id: string,
	Remarks: string,
	Url: string,
	RuleSet: RulesItem_Serialize[],
	RuleNum: number,
	Enabled: boolean,
	Locked: boolean,
	CustomIcon: string,
	CustomRulesetPath4Singbox: string,
	DomainStrategy: string,
	DomainStrategy4Singbox: string,
	Sort: number,
	IsActive: boolean,
};

export type RuleMode = number;

export type RuleType = number;

export type RulesItem = RulesItem_Serialize | RulesItem_Deserialize;

export type RulesItem_Deserialize = {
	Id?: string,
} | {
	id?: string,
} & {
	Type?: string | null,
} | {
	type?: string | null,
} & {
	Port?: string | null,
} | {
	port?: string | null,
} & {
	Network?: string | null,
} | {
	network?: string | null,
} & {
	InboundTag?: string[] | null,
} | {
	inboundTag?: string[] | null,
} & {
	OutboundTag?: string | null,
} | {
	outboundTag?: string | null,
} & {
	Ip?: string[] | null,
} | {
	ip?: string[] | null,
} & {
	Domain?: string[] | null,
} | {
	domain?: string[] | null,
} & {
	Protocol?: string[] | null,
} | {
	protocol?: string[] | null,
} & {
	Process?: string[] | null,
} | {
	process?: string[] | null,
} & {
	Enabled?: boolean,
} | {
	enabled?: boolean,
} & {
	Remarks?: string | null,
} | {
	remarks?: string | null,
} & {
	RuleType?: RuleType | null,
} | {
	ruleType?: RuleType | null,
};

export type RulesItem_Serialize = {
	Id: string,
	Type?: string | null,
	Port?: string | null,
	Network?: string | null,
	InboundTag?: string[] | null,
	OutboundTag?: string | null,
	Ip?: string[] | null,
	Domain?: string[] | null,
	Protocol?: string[] | null,
	Process?: string[] | null,
	Enabled: boolean,
	Remarks?: string | null,
	RuleType?: RuleType | null,
};

export type RulesetGeoSourceSettings = {
	geoSourceUrl: string | null,
	srsSourceUrl: string | null,
};

export type RuntimeConnectionState = "disconnected" | "connected";

export type RuntimeStatusResponse = {
	state: RuntimeConnectionState,
	activeProfileId: string | null,
	mainPid: number | null,
	prePid: number | null,
	runningCoreType: CoreType | null,
};

export type ServerStatItem = {
	IndexId?: string,
	TotalUp?: number | null,
	TotalDown?: number | null,
	TodayUp?: number | null,
	TodayDown?: number | null,
	DateNow?: number | null,
};

export type ShellTabTarget = "profiles" | "clashProxies" | "clashConnections" | "logs";

export type SimpleDnsItem = SimpleDnsItem_Serialize | SimpleDnsItem_Deserialize;

export type SimpleDnsItem_Deserialize = {
	UseSystemHosts?: boolean | null,
	AddCommonHosts?: boolean | null,
	FakeIP?: boolean | null,
	GlobalFakeIp?: boolean | null,
	BlockBindingQuery?: boolean | null,
	DirectDNS?: string | null,
	RemoteDNS?: string | null,
	BootstrapDNS?: string | null,
	Strategy4Freedom?: string | null,
	Strategy4Proxy?: string | null,
	ServeStale?: boolean | null,
	ParallelQuery?: boolean | null,
	Hosts?: string | null,
	DirectExpectedIPs?: string | null,
};

export type SimpleDnsItem_Serialize = {
	UseSystemHosts?: boolean | null,
	AddCommonHosts?: boolean | null,
	FakeIP?: boolean | null,
	GlobalFakeIp?: boolean | null,
	BlockBindingQuery?: boolean | null,
	DirectDNS?: string | null,
	RemoteDNS?: string | null,
	BootstrapDNS?: string | null,
	Strategy4Freedom?: string | null,
	Strategy4Proxy?: string | null,
	ServeStale?: boolean | null,
	ParallelQuery?: boolean | null,
	Hosts?: string | null,
	DirectExpectedIPs?: string | null,
};

export type SpeedActionType = number;

export type SpeedTestItem = SpeedTestItem_Serialize | SpeedTestItem_Deserialize;

export type SpeedTestItem_Deserialize = {
	SpeedTestTimeout?: number,
	SpeedTestUrl?: string,
	SpeedPingTestUrl?: string,
	MixedConcurrencyCount?: number,
	IPAPIUrl?: string,
	UdpTestTarget?: string,
	SpeedTestPageSize?: number | null,
	SpeedTestDelayInterval?: number | null,
};

export type SpeedTestItem_Serialize = {
	SpeedTestTimeout: number,
	SpeedTestUrl: string,
	SpeedPingTestUrl: string,
	MixedConcurrencyCount: number,
	IPAPIUrl: string,
	UdpTestTarget: string,
	SpeedTestPageSize?: number | null,
	SpeedTestDelayInterval?: number | null,
};

export type SpeedTestResult = {
	action: SpeedActionType,
	indexId: string,
	delay: number | null,
	speed: number | null,
	message: string | null,
	ipInfo: string | null,
};

export type SpeedtestRunResult = {
	action: SpeedActionType,
	cancelled: boolean,
	selectedCount: number,
	completedCount: number,
	results: SpeedTestResult[],
};

export type SpeedtestStatus = {
	running: boolean,
};

export type StatisticsSnapshot = {
	activeProfileId: string | null,
	proxyUploadBytesPerSecond: number | null,
	proxyDownloadBytesPerSecond: number | null,
	directUploadBytesPerSecond: number | null,
	directDownloadBytesPerSecond: number | null,
	uploadBytesPerSecond: number | null,
	downloadBytesPerSecond: number | null,
	serverStat: ServerStatItem | null,
};

export type SubItem = SubItem_Serialize | SubItem_Deserialize;

export type SubItem_Deserialize = {
	Id?: string,
	Remarks?: string,
	Url?: string,
	MoreUrl?: string,
	Enabled?: boolean,
	UserAgent?: string,
	Sort?: number,
	Filter?: string | null,
	AutoUpdateInterval?: number,
	UpdateTime?: number | null,
	ConvertTarget?: string | null,
	PrevProfile?: string | null,
	NextProfile?: string | null,
	PreSocksPort?: number | null,
	Memo?: string | null,
};

export type SubItem_Serialize = {
	Id: string,
	Remarks: string,
	Url: string,
	MoreUrl: string,
	Enabled: boolean,
	UserAgent: string,
	Sort: number,
	Filter?: string | null,
	AutoUpdateInterval: number,
	UpdateTime: number | null,
	ConvertTarget?: string | null,
	PrevProfile?: string | null,
	NextProfile?: string | null,
	PreSocksPort?: number | null,
	Memo?: string | null,
};

export type SubscriptionUpdateResult = {
	updated?: number,
	skipped?: number,
	imported?: number,
	removedExisting?: number,
	messages?: string[],
};

export type SysProxyChanged = {
	requestedMode: SysProxyMode,
	effectiveMode: SysProxyMode,
	pacAvailable: boolean,
	proxy: string | null,
};

export type SysProxyMode = "unchanged" | "forcedChange" | "forcedClear" | "pac";

export type SysProxyType = number;

export type SystemProxyItem = SystemProxyItem_Serialize | SystemProxyItem_Deserialize;

export type SystemProxyItem_Deserialize = {
	SysProxyType?: SysProxyType,
	SystemProxyExceptions?: string,
	NotProxyLocalAddress?: boolean,
	SystemProxyAdvancedProtocol?: string,
	CustomSystemProxyPacPath?: string | null,
	CustomSystemProxyScriptPath?: string | null,
};

export type SystemProxyItem_Serialize = {
	SysProxyType: SysProxyType,
	SystemProxyExceptions: string,
	NotProxyLocalAddress: boolean,
	SystemProxyAdvancedProtocol: string,
	CustomSystemProxyPacPath?: string | null,
	CustomSystemProxyScriptPath?: string | null,
};

export type SystemProxyStatusResponse = {
	requestedMode: SysProxyType,
	effectiveMode: SysProxyType,
	pacAvailable: boolean,
	proxy: string | null,
	exceptions: string,
	pacUrl: string | null,
};

/**
 *  Title-bar layout selected per platform. Windows uses a fully self-drawn
 *  borderless bar (minimize/maximize/close + drag region); every other platform
 *  keeps its native window frame and draws no custom title bar (`None`).
 */
export type TitleBarLayout = "windows" | "none";

export type TransientStreamEvent = { kind: "logLine"; payload: LogLineEvent } | { kind: "coreState"; payload: CoreStateEvent } | { kind: "statistics"; payload: StatisticsSnapshot } | { kind: "sysProxyChanged"; payload: SysProxyChanged } | { kind: "tunChanged"; payload: TunChanged } | { kind: "clashMonitorStatus"; payload: ClashMonitorStatus } | { kind: "clashTraffic"; payload: ClashTrafficEvent } | { kind: "clashConnections"; payload: ClashConnectionsSnapshot } | { kind: "speedtestResult"; payload: SpeedTestResult };

export type TransportExtraItem = TransportExtraItem_Serialize | TransportExtraItem_Deserialize;

export type TransportExtraItem_Deserialize = {
	RawHeaderType?: string | null,
	Host?: string | null,
	Path?: string | null,
	XhttpMode?: string | null,
	XhttpExtra?: string | null,
	GrpcAuthority?: string | null,
	GrpcServiceName?: string | null,
	GrpcMode?: string | null,
	KcpHeaderType?: string | null,
	KcpSeed?: string | null,
	KcpMtu?: number | null,
};

export type TransportExtraItem_Serialize = {
	RawHeaderType?: string | null,
	Host?: string | null,
	Path?: string | null,
	XhttpMode?: string | null,
	XhttpExtra?: string | null,
	GrpcAuthority?: string | null,
	GrpcServiceName?: string | null,
	GrpcMode?: string | null,
	KcpHeaderType?: string | null,
	KcpSeed?: string | null,
	KcpMtu?: number | null,
};

export type TunChanged = {
	enabled: boolean,
};

export type TunModeItem = {
	EnableTun?: boolean,
	AutoRoute?: boolean,
	StrictRoute?: boolean,
	Stack?: string,
	Mtu?: number,
	EnableIPv6Address?: boolean,
	IcmpRouting?: string,
	EnableLegacyProtect?: boolean,
};

export type TunPlatform = "windows" | "linux" | "macos" | "other";

export type TunPreflight = {
	platform: TunPlatform,
	state: TunPreflightState,
	notes: string[],
	routeRestoreNote: string,
	windowsCleanupDevices: string[],
};

export type TunPreflightState = "ready" | "needsElevation" | "manualCheck" | "unsupported";

export type TunStatus = {
	enabled: boolean,
	allowEnableTun: boolean,
	requiresElevation: boolean,
	elevationGranted: boolean,
	restoreOnDisconnect: boolean,
	preflight: TunPreflight,
};

export type UiItem = UiItem_Serialize | UiItem_Deserialize;

export type UiItem_Deserialize = {
	EnableAutoAdjustMainLvColWidth?: boolean,
	MainGirdHeight1?: number,
	MainGirdHeight2?: number,
	MainGirdOrientation?: GridOrientation,
	ColorPrimaryName?: string | null,
	CurrentTheme?: string | null,
	CurrentLanguage?: string,
	CurrentFontFamily?: string,
	CurrentFontSize?: number,
	EnableDragDropSort?: boolean,
	DoubleClick2Activate?: boolean,
	AutoHideStartup?: boolean,
	Hide2TrayWhenClose?: boolean,
	MacOSShowInDock?: boolean,
	MainColumnItem?: ColumnItem[],
	WindowSizeItem?: WindowSizeItem[],
};

export type UiItem_Serialize = {
	EnableAutoAdjustMainLvColWidth: boolean,
	MainGirdHeight1: number,
	MainGirdHeight2: number,
	MainGirdOrientation: GridOrientation,
	ColorPrimaryName?: string | null,
	CurrentTheme?: string | null,
	CurrentLanguage: string,
	CurrentFontFamily: string,
	CurrentFontSize: number,
	EnableDragDropSort: boolean,
	DoubleClick2Activate: boolean,
	AutoHideStartup: boolean,
	Hide2TrayWhenClose: boolean,
	MacOSShowInDock: boolean,
	MainColumnItem: ColumnItem[],
	WindowSizeItem: WindowSizeItem[],
};

export type UpdateAcquisition = "appPackage" | "optionalDownload";

export type UpdateCheckResult = {
	targetId: string,
	status: UpdateResultStatus,
	message: string,
	currentVersion: string | null,
	remoteVersion: string | null,
	downloadUrl: string | null,
	fileName: string | null,
	sha256: string | null,
	bytes: number | null,
	usedProxy: boolean | null,
};

export type UpdateResultStatus = "skipped" | "upToDate" | "updateAvailable" | "downloaded" | "error";

export type UpdateRunResult = {
	preRelease: boolean,
	results: UpdateCheckResult[],
	targets: UpdateTarget[],
};

export type UpdateStatus = {
	preRelease: boolean,
	targets: UpdateTarget[],
};

export type UpdateTarget = {
	id: string,
	name: string,
	kind: UpdateTargetKind,
	coreType: CoreType | null,
	selected: boolean,
	updateSupported: boolean,
	license: string | null,
	acquisition: UpdateAcquisition,
	redistributeInInstaller: boolean,
	remarks: string,
};

export type UpdateTargetKind = "app" | "geo" | "srs";

export type WebDavItem = WebDavItem_Serialize | WebDavItem_Deserialize;

export type WebDavItem_Deserialize = {
	Url?: string | null,
	UserName?: string | null,
	Password?: string | null,
	DirName?: string | null,
};

export type WebDavItem_Serialize = {
	Url?: string | null,
	UserName?: string | null,
	Password?: string | null,
	DirName?: string | null,
};

export type WindowChromeConfig = {
	titleBarLayout: TitleBarLayout,
};

export type WindowSizeItem = {
	TypeName?: string,
	Width?: number,
	Height?: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

