[package]
name = "voya-platform"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
test-support = []

[dependencies]
arboard = "3.6"
libc.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
voya-core.workspace = true
zeroize.workspace = true
xcap = "=0.9.8"
sys-locale = "0.3"

[build-dependencies]
cc = "1.2"

[lints]
workspace = true
