// Derived from apps/desktop/src/ipc/bindings.ts by scripts/quality/contracts-source.mjs.
// Do not edit this file manually — run `pnpm generate:bindings`.

/**
 *  Every IPC command, with the result envelope already unwrapped.
 *
 *  A platform binding declares `satisfies VoyaCommands` so dropping or
 *  mistyping a command is a compile error rather than a runtime surprise.
 */
export type VoyaCommands = {
	loadUiPreferences: () => Promise<AppearanceSettings>,
	loadAppSettings: () => Promise<AppSettingsV1>,
	getSettingsApplyStatus: () => Promise<SettingsApplyStatus>,
	applyPendingSettings: () => Promise<SettingsApplyStatus>,
	/**
	 *  Thin adapter over `voya_app::settings`.
	 * 
	 *  Validation, the pre-commit OS side effects, the commit and both rollback
	 *  paths are the transaction in voya-app, where they are unit-tested; the only
	 *  things left here are turning `AppError`s back out of it and dispatching the
	 *  runtime action it selected.
	 */
	saveAppSettings: (settings: AppSettingsV1) => Promise<AppSettingsV1>,
	generateQrCode: (content: string) => Promise<QrCodeImage>,
	scanScreenQr: () => Promise<QrScanResult>,
	/**
	 *  Decodes the QR codes in a picture the user picked. The webview decodes the
	 *  file and sends grey pixels (base64, one byte each), so no image decoder
	 *  ships in either the bundle or the binary; locating codes in a large
	 *  picture takes long enough to keep off the async workers.
	 */
	decodeQrImage: (width: number, height: number, lumaBase64: string) => Promise<QrScanResult>,
	/**  Returns an empty string when the clipboard holds no text. */
	readClipboardText: () => Promise<string>,
	/**
	 *  Asks where to save `contents` and writes it there. Returns `false` when the
	 *  user cancels the save dialog.
	 */
	exportLogs: (contents: string) => Promise<boolean>,
	/**
	 *  Whether the Logs panel is on screen to receive log lines. While it is not,
	 *  the lines queue (the newest few hundred) instead of each batch being
	 *  serialized into a webview that discards it. Idempotent, and synchronous so
	 *  calls apply in the order they were made. It cannot fail; the `Result` keeps
	 *  it on the same typed-error facade as every other command.
	 */
	setLogStreaming: (enabled: boolean) => Promise<null>,
	/**
	 *  Trigger the one-time native authorization dialog and, on success, install
	 *  the passwordless elevation launcher. No admin password is stored.
	 */
	tunRequestElevation: () => Promise<TunStatus>,
	connectActiveProfile: () => Promise<RuntimeStatusResponse>,
	disconnectCore: () => Promise<RuntimeStatusResponse>,
	restartCore: () => Promise<RuntimeStatusResponse>,
	runtimeStatus: () => Promise<RuntimeStatusResponse>,
	systemProxyStatus: () => Promise<SystemProxyStatusResponse>,
	connectionModeStatus: () => Promise<ConnectionModeStatus>,
	/**
	 *  Switches the app between system proxy and TUN mode.
	 * 
	 *  The transaction itself is `voya_app::connection_mode`: the mode is always
	 *  persisted, but the machine's proxy settings are only rewritten while the
	 *  supervisor reports `Connected` — a mode pointed at a port nothing is
	 *  listening on would black-hole every request. Only a TUN flag change needs a
	 *  running core to be restarted.
	 */
	setConnectionMode: (mode: ConnectionMode) => Promise<ConnectionModeStatus>,
	/**  Looks up the exit address of the running connection through its local proxy. */
	checkConnectionIp: () => Promise<ConnectionIpResult>,
	/**
	 *  Carries out the user's answer to the close prompt, optionally keeping it
	 *  as the close action from now on.
	 */
	resolveCloseRequest: (action: CloseRequestAction, remember: boolean) => Promise<null>,
	tunStatus: () => Promise<TunStatus>,
	tunProviderDiagnostics: () => Promise<TunProviderDiagnostics>,
	setTunEnabled: (enabled: boolean) => Promise<TunStatus>,
	loadDnsSettings: () => Promise<DnsSettings>,
	getDefaultDnsSettings: () => Promise<DnsSettings>,
	saveDnsSettings: (settings: DnsSettings) => Promise<DnsSettings>,
	/**  Every node as the node table shows it; `get_profile` has one in full. */
	listProfileSummaries: () => Promise<ProfileSummaryListing>,
	/**  One node in full, for the editor and the details dialog. */
	getProfile: (indexId: string) => Promise<ProfileDetails>,
	saveProfile: (profile: Profile) => Promise<ProfileDetails>,
	deleteProfiles: (indexIds: string[]) => Promise<number>,
	exportProfileShareLinks: (indexIds: string[]) => Promise<ExportProfilesResult>,
	setActiveProfile: (indexId: string) => Promise<ProfileDetails>,
	moveProfile: (subscriptionId: string | null, indexId: string, action: MoveAction, position: number | null) => Promise<null>,
	listPolicyGroups: () => Promise<PolicyGroupListing>,
	/**
	 *  Saves a group. Editing the group a running core uses restarts the core so
	 *  the change takes effect.
	 */
	savePolicyGroup: (group: PolicyGroup) => Promise<PolicyGroup>,
	deletePolicyGroups: (ids: string[]) => Promise<number>,
	/**
	 *  Makes a group what connecting uses. Connecting or restarting is the
	 *  caller's next step, exactly as after choosing a node.
	 */
	setActivePolicyGroup: (id: string) => Promise<PolicyGroup>,
	/**
	 *  Stores a selector's member and, when that group is running, switches the
	 *  core to it live. The choice is kept even if the live switch fails.
	 */
	selectPolicyGroupMember: (groupId: string, profileId: string) => Promise<PolicyGroup>,
	/**  The running group's current member and delays; `None` while no group runs. */
	policyGroupRuntime: () => Promise<{
		groupId: string,
		/**  The member traffic goes through right now. */
		nowProfileId: string | null,
		members: PolicyGroupRuntimeMember[],
	} | null>,
	/**
	 *  Probes every member of the running group through the core and returns the
	 *  group with those delays; `None` while no group runs.
	 */
	testPolicyGroupDelay: () => Promise<{
		groupId: string,
		/**  The member traffic goes through right now. */
		nowProfileId: string | null,
		members: PolicyGroupRuntimeMember[],
	} | null>,
	listSubscriptions: () => Promise<Subscription[]>,
	listSubscriptionMetadata: () => Promise<SubscriptionMetadata[]>,
	saveSubscription: (item: Subscription) => Promise<Subscription>,
	deleteSubscriptions: (ids: string[]) => Promise<number>,
	importProfilesFromText: (text: string, subscriptionId: string | null) => Promise<ImportProfilesResult>,
	previewImportProfiles: (text: string) => Promise<ImportPreview>,
	updateSubscriptions: (subscriptionId: string | null, preferProxy: boolean, proxyUrl: string | null) => Promise<SubscriptionUpdateResult>,
	listRoutings: () => Promise<Routing_Serialize[]>,
	saveRouting: (item: Routing_Deserialize) => Promise<Routing_Serialize>,
	deleteRoutings: (ids: string[]) => Promise<number>,
	setActiveRouting: (id: string) => Promise<Routing_Serialize>,
	saveRoutingRule: (routingId: string, rule: RoutingRule) => Promise<Routing_Serialize>,
	deleteRoutingRules: (routingId: string, ruleIds: string[]) => Promise<Routing_Serialize>,
	moveRoutingRule: (routingId: string, ruleId: string, action: MoveAction, position: number | null) => Promise<Routing_Serialize>,
	/**
	 *  Replaces a routing profile's rules with the default set, keeping its
	 *  per-app proxy rule.
	 */
	resetRoutingRules: (routingId: string) => Promise<Routing_Serialize>,
	/**
	 *  Enumerates running processes (and installed applications where the OS
	 *  makes that cheap) for the per-app proxy picker. Blocking OS enumeration
	 *  runs off the async runtime.
	 */
	listProcessCandidates: () => Promise<ProcessCandidate[]>,
	proxyListConnections: () => Promise<ProxyConnectionsSnapshot>,
	proxyCloseConnection: (connectionId: string | null) => Promise<ProxyConnectionsSnapshot>,
	proxySetTrafficMode: (mode: TrafficMode) => Promise<TrafficModeResponse>,
	proxyStartMonitor: () => Promise<ProxyMonitorStatus>,
	proxyStopMonitor: () => Promise<ProxyMonitorStatus>,
	runSpeedtest: (request: SpeedtestRequest) => Promise<SpeedtestRunResult>,
	cancelSpeedtest: () => Promise<SpeedtestStatus>,
	speedtestStatus: () => Promise<SpeedtestStatus>,
	appUpdateStatus: () => Promise<AppUpdaterStatus>,
	updateGeoAssets: () => Promise<ResourceUpdateFile[]>,
	updateSrsAssets: () => Promise<ResourceUpdateFile[]>,
	/**
	 *  Re-install a core binary from the packaged seed (`{resource_dir}/core-seeds/<core>/`)
	 *  into `bin/<core>/`. This is the recovery action behind the missing-core prompt: the
	 *  startup seed copy already runs automatically, but this lets the UI re-run it on demand
	 *  when the binary is absent (e.g. cleared bin dir, antivirus removal, or a skipped first run).
	 */
	installCoreSeed: () => Promise<CoreSeedInstallResult>,
	getSelfHostState: () => Promise<SelfHostState>,
	saveSelfHostConfig: (config: SelfHostConfig) => Promise<SelfHostState>,
	setSelfHostEnabled: (enabled: boolean) => Promise<SelfHostState>,
	rotateSelfHostCredentials: () => Promise<SelfHostState>,
	getSelfHostStats: () => Promise<SelfHostStats>,
	runSelfHostEnvironmentCheck: () => Promise<SelfHostState>,
	/**
	 *  Adds the Windows firewall rule; the UAC prompt blocks until answered, so
	 *  the work runs off the UI thread inside the manager.
	 */
	applySelfHostFirewallRule: () => Promise<SelfHostState>,
	/**
	 *  The five window-chrome actions the custom title bar drives.
	 * 
	 *  They used to go through `@tauri-apps/api/window`'s `getCurrentWindow()`,
	 *  which pulls `window.js`/`dpi.js`/`image.js` into the startup vendor chunk.
	 *  A thin Rust command keeps the same behavior and leaves those modules out.
	 */
	minimizeWindow: () => Promise<null>,
	toggleMaximizeWindow: () => Promise<null>,
	closeWindow: () => Promise<null>,
	isWindowMaximized: () => Promise<boolean>,
	/**  Whether the window is on screen rather than hidden into the tray. */
	isWindowVisible: () => Promise<boolean>,
	/**
	 *  macOS overlays native traffic lights on the webview; Windows renders caption
	 *  buttons in its borderless window. Linux and the web fallback use `none`.
	 */
	getWindowChromeConfig: () => Promise<WindowChromeConfig>,
	/**
	 *  Tint the Windows Acrylic blur material to match the in-app light/dark theme.
	 *  The frontend drives its own (non-system) theme, so this command sets the tint
	 *  explicitly per mode to keep the native material's base color aligned with the
	 *  UI. Acrylic has a single variant; light and dark differ only by `color`.
	 * 
	 *  Non-Windows platforms are a no-op: window effects are an OS capability, and
	 *  macOS / Linux / web fall back to the flat CSS neutral-gray veil.
	 */
	setWindowAcrylic: (dark: boolean) => Promise<null>,
};

/**
 *  The three backend event channels and the payload each carries.
 *
 *  `channel` is the wire name the backend emits under; a transport that is
 *  not Tauri still has to route by it.
 */
export type VoyaEventChannels = {
	appEvent: { channel: "app-event"; payload: AppEvent },
	invalidateEvent: { channel: "invalidate-event"; payload: InvalidateEvent },
	transientStreamEvent: { channel: "transient-stream-event"; payload: TransientStreamEvent },
};

export type VoyaEventName = keyof VoyaEventChannels;

export type VoyaEventPayload<Name extends VoyaEventName> = VoyaEventChannels[Name]["payload"];

/* Types */
/**
 *  One failed IPC command.
 * 
 *  The three parts answer three different questions and nothing else may be
 *  inferred from any of them:
 * 
 *  - `kind` is **what the frontend branches on**. Every discrimination the UI
 *    performs has to be expressible here; the previous 23-arm union carried a
 *    string in 21 of its arms, which is why elevation retry was triggered by
 *    substring-matching the word "authorization" in `message`.
 *  - `subsystem` says which part of the app failed. It is for grouping, logging
 *    and copy ("Profiles: …"), never for control flow — the same `kind` means
 *    the same thing whichever subsystem raised it.
 *  - `message` is an English diagnostic. Show it, log it, that is all. It is
 *    never parsed, and rewording it must never change behavior.
 */
export type AppError = {
	kind: AppErrorKind,
	subsystem: AppErrorSubsystem,
	message: string,
};

/**  The kind of row a [`AppErrorKind::NotFound`] refers to. */
export type AppErrorEntity = "policyGroup" | "profile" | "routing" | "routingRule" | "subscription";

/**
 *  What went wrong, in the terms the frontend acts on.
 * 
 *  Serialized internally tagged, so a failure reads `{ type: "elevationRequired" }`
 *  and TypeScript narrows the payload from the tag alone.
 */
export type AppErrorKind = 
/**
 *  Submitted values were rejected. `issues` name the offending fields and
 *  carry a [`ValidationCode`](crate::ValidationCode) the frontend
 *  translates, which is the pairing the DNS pane already renders.
 */
{ type: "validation"; issues: ValidationIssue[] } | 
/**
 *  A referenced row does not exist. The UI's remedy is to refresh the list
 *  it selected from, so the entity matters more than the id.
 */
{ type: "notFound"; entity: AppErrorEntity; id: string | null } | 
/**
 *  The action needs one-time system authorization. This is the *only*
 *  signal that may open a privilege prompt: TUN and the elevated
 *  supervisor spawn both raise it, and no message text can substitute.
 */
{ type: "elevationRequired" } | 
/**
 *  The action is not offered on this platform, such as leaving VPN mode on
 *  macOS. The UI hides the control, so reaching this is a stale view.
 */
{ type: "unsupported" } | 
/**  The core executable is not installed where the app looks for it. */
{ type: "missingCore"; searchDir: string; candidates: string[]; downloadUrl: string } | 
/**  A download, subscription fetch or Clash API call failed. Retryable. */
{ type: "network" } | 
/**  A filesystem or child-process operation failed. */
{ type: "io" } | 
/**
 *  Persistence failed. `code` separates the cases that have different
 *  remedies, and `reset_command` carries the manual recovery line when the
 *  database itself reported one.
 */
{ type: "database"; code: DatabaseErrorCode; resetCommand: string | null } | 
/**
 *  Anything with no better classification: a poisoned lock, a join error,
 *  an invariant the app itself broke.
 */
{ type: "internal" };

/**  Which part of the app produced a failure. Diagnostic grouping only. */
export type AppErrorSubsystem = 
/**  The shell itself: window chrome, event emission, background tasks. */
"app" | "autostart" | 
/**  Reading or writing the persisted application configuration. */
"config" | "dns" | "export" | "policyGroup" | "profile" | "proxyRuntime" | "qr" | "routing" | 
/**  Core lifecycle: config generation, supervisor, connect/disconnect. */
"runtime" | 
/**  The self-hosted exit node. */
"selfHost" | "speedtest" | "subscription" | "sysProxy" | "tun" | "update";

export type AppEvent = { kind: "notice"; payload: AppNotice } | { kind: "selectTab"; payload: ShellTabTarget } | 
/**  The main window was closed while the close action is "ask". */
{ kind: "closeRequested" };

/**
 *  One toast.
 * 
 *  `code` replaced the prose `title` the shell used to spell out at each of its
 *  call sites: those titles were English literals that `pnpm check:i18n` could
 *  not see, and the toast is the most visible text the backend produces.
 *  `detail` stays an untranslated diagnostic — the error behind the notice.
 */
export type AppNotice = {
	level: AppNoticeLevel,
	code: NoticeCode,
	detail: string | null,
};

export type AppNoticeLevel = "info" | "warning" | "error";

export type AppSettingsV1 = {
	schemaVersion: number,
	appearance: AppearanceSettings,
	behavior: BehaviorSettings,
	core: CoreSettings,
	network: NetworkSettings,
	routing: RoutingSettings,
	dns: DnsSettings,
	speedTest: SpeedtestSettings,
	multiplexing: MultiplexingSettings,
	hysteria: HysteriaSettings,
	proxy: ProxySettings,
};

export type AppUpdaterState = "ready" | "unconfigured" | "unsupported" | "error";

export type AppUpdaterStatus = {
	currentVersion: string,
	state: AppUpdaterState,
	message: string | null,
};

export type AppearanceSettings = {
	language: string,
	theme: ThemeMode,
};

export type AutostartPlatform = "windows" | "linux" | "macos" | "ios" | "android" | "other";

export type AutostartStatus = {
	enabled: boolean,
	platform: AutostartPlatform,
	artifactKind: string | null,
	artifactPath: string | null,
	artifactName: string | null,
};

export type BehaviorSettings = {
	autostart: boolean,
	/**  Look up the exit IP each time a connection is established. */
	autoCheckIp: boolean,
	/**  What closing the main window does. */
	closeAction: CloseAction,
	/**  Keep the window hidden when the app is launched at login. */
	startMinimized: boolean,
	/**
	 *  Create a lowest-latency policy group the first time a subscription
	 *  imports nodes. The group is never activated automatically.
	 */
	autoCreateSubscriptionGroup: boolean,
};

/**  What closing the main window does. */
export type CloseAction = 
/**  Hide the window and keep running from the tray. */
"minimizeToTray" | "quit" | 
/**  Ask every time the window is closed. */
"ask";

/**  The user's answer to a close prompt. */
export type CloseRequestAction = "minimizeToTray" | "quit" | "cancel";

/**  The public address the running connection exits from. */
export type ConnectionIpResult = {
	ip: string | null,
	countryCode: string | null,
};

/**
 *  How traffic is captured. A derived view over the two persisted primitives
 *  (system proxy type + TUN flag), never stored itself. It is independent of
 *  the traffic mode, which decides where captured traffic goes.
 */
export type ConnectionMode = 
/**  Local inbound for system proxy use. Windows and Linux only. */
"systemProxy" | 
/**  TUN mode; all traffic is routed through the virtual interface. */
"vpn";

export type ConnectionModeStatus = {
	mode: ConnectionMode,
	vpnAvailable: boolean,
	/**
	 *  Whether the platform offers the system proxy mode at all. macOS only
	 *  captures traffic through its PacketTunnel VPN.
	 */
	systemProxyAvailable: boolean,
	/**
	 *  Whether the platform's tunnel can match traffic by process. The macOS
	 *  NetworkExtension tunnel cannot, so per-app rules are not offered there.
	 */
	processRulesSupported: boolean,
	/**
	 *  sing-box process rules only match traffic entering through TUN, so
	 *  per-app rules are effective only while they are supported and `mode` is
	 *  `Vpn`.
	 */
	processRulesEffective: boolean,
};

/**
 *  Which core operation a log line is about.
 * 
 *  The flow used to interpolate an English fragment ("connect", "Routing
 *  changed") into its log sentences; the fragment is a code now so the whole
 *  sentence can be assembled in the reader's language.
 */
export type CoreFlowReason = "connect" | "restart" | "disconnect" | "routingChanged" | "dnsChanged" | "tunChanged" | "connectionModeChanged" | "activeProfileChanged" | "policyGroupChanged" | "settingsSaved" | 
/**  The connected node's IPv6 egress turned out different from its record. */
"ipv6EgressChanged";

export type CoreSeedInstallResult = {
	status: CoreSeedInstallStatus,
	installedFiles: string[],
};

export type CoreSeedInstallStatus = "installed" | "alreadyInstalled" | "seedMissing";

export type CoreSettings = {
	logEnabled: boolean,
	logLevel: string,
	muxEnabled: boolean,
	defaultAllowInsecure: boolean,
	defaultFingerprint: string,
	defaultUserAgent: string,
	sendThrough: string | null,
	bindInterface: string | null,
	tlsFragment: TlsFragmentMode,
	fragmentFallbackDelayMs: number,
	cacheFileEnabled: boolean,
};

/**
 *  What the core process is doing right now.
 * 
 *  The single vocabulary for the runtime's connection state: the status command
 *  returns it inside [`crate::RuntimeStatusResponse`] and the transient
 *  `coreState` stream carries the very same struct, so there is nothing to
 *  translate between a response and an event. `Connecting`/`Disconnecting` are
 *  transitions only the event stream ever reports — a status read observes a
 *  settled supervisor and answers `Connected`, `Disconnected`, or `CleanupPending`.
 */
export type CoreState = "cleanupPending" | "disconnected" | "connecting" | "connected" | "disconnecting";

/**  Why a persistence call failed, at the granularity the UI can act on. */
export type DatabaseErrorCode = 
/**
 *  The stored schema is not the one this build expects; the database has to
 *  be reset manually before anything else will work.
 */
"schemaUnsupported" | 
/**  A stored payload could not be decoded — one bad row, or a damaged file. */
"corrupt" | 
/**  Another writer holds the database. Retrying is the remedy. */
"locked" | 
/**  The database file could not be read or written. */
"io" | "other";

export type DnsSettings = {
	addCommonHosts: boolean | null,
	fakeIp: boolean | null,
	globalFakeIp: boolean | null,
	blockBindingQuery: boolean | null,
	direct: string | null,
	remote: string | null,
	bootstrap: string | null,
	directStrategy: string | null,
	proxyStrategy: string | null,
	hosts: string | null,
	directExpectedIps: string | null,
};

export type ExportProfilesResult = {
	text: string,
	count: number,
};

export type HysteriaSettings = {
	uploadMbps: number,
	downloadMbps: number,
	hopIntervalSeconds: number,
};

/**  Why one line of imported text did not simply become a node. */
export type ImportLineCode = 
/**  The line was a subscription URL and was added as a source instead. */
{ code: "subscriptionSourceAdded" } | 
/**  The share link names a transport sing-box cannot carry. */
{ code: "unsupportedTransport"; transport: string } | 
/**  The line uses a share-link scheme this build does not read. */
{ code: "unsupportedProtocol" } | 
/**  The share link lacks a field its protocol requires. */
{ code: "missingField"; protocol: string; field: string } | 
/**  The share link's port is not a valid port. */
{ code: "invalidPort"; protocol: string; port: string } | 
/**
 *  Any other malformed share link. `detail` is an untranslated diagnostic
 *  for logs; the interface does not show it.
 */
{ code: "parseFailed"; detail: string };

/**  One reported line of an import, numbered from 1. */
export type ImportLineIssue = {
	line: number,
	code: ImportLineCode,
};

/**  A read-only preview. Credentials are deliberately excluded. */
export type ImportPreview = {
	nodes: ImportPreviewNode[],
	subscriptionUrls: string[],
	failed: number,
	lineIssues: ImportLineIssue[],
};

export type ImportPreviewNode = {
	name: string,
	protocol: string,
	address: string,
};

export type ImportProfilesResult = {
	imported: number,
	updated: number,
	skipped: number,
	parsed: number,
	filtered: number,
	deduped: number,
	failed: number,
	removedExisting: number,
	removedDuplicates: number,
	discardedNodeOverrides: number,
	subscriptionId: string | null,
	importedProfileIds: string[],
	updatedProfileIds: string[],
	lineIssues: ImportLineIssue[],
	/**
	 *  Subscriptions created from subscription URLs in the text. Their nodes
	 *  arrive only once they are updated.
	 */
	addedSubscriptionIds: string[],
};

export type InboundSettings = {
	localPort: number,
	sniffingEnabled: boolean,
	lanConnectionsAllowed: boolean,
	separateLanPort: boolean,
	username: string,
	password: string,
	secondaryPortEnabled: boolean,
};

export type InvalidateEvent = {
	keys: QueryInvalidation[],
};

/**
 *  One frontend query cache, named on the wire.
 * 
 *  Replaces the free-string key list the shell used to build by hand. The
 *  variants are generated into `apps/desktop/src/ipc/bindings.ts`, and
 *  `packages/client/src/query-keys.ts` maps each one onto the `queryKey`
 *  array its `useQuery` really uses, so a variant added here fails the frontend
 *  typecheck until the map is extended. Only caches an emitter can actually
 *  invalidate belong here; a query whose data no command mutates
 *  (`process-candidates`, `profile-share-qr`) deliberately has no variant.
 * 
 *  Internally tagged rather than a bare string so a future scope that has to
 *  name one row (`{ kind: "profile", id }`) is an additive change instead of a
 *  rewrite of the wire shape.
 */
export type InvalidationScope = 
/**  `["profiles"]` — the profile list, every filter slice of it. */
{ kind: "profiles" } | 
/**  `["subscriptions"]` */
{ kind: "subscriptions" } | 
/**  `["subscription-metadata"]` */
{ kind: "subscriptionMetadata" } | 
/**  `["routings"]` */
{ kind: "routings" } | 
/**  `["dns"]` */
{ kind: "dns" } | 
/**  `["app-settings"]` — the whole settings bundle projected from `AppConfig`. */
{ kind: "appSettings" } | 
/**  `["ui-preferences"]` — the appearance slice the shell reads on its own. */
{ kind: "uiPreferences" } | 
/**  `["connection-mode"]` — TUN / system-proxy mode and its availability. */
{ kind: "connectionMode" } | 
/**  `["proxy-connections"]` */
{ kind: "proxyConnections" } | 
/**  `["profiles", "policy-groups"]` — stored groups and their resolved members. */
{ kind: "policyGroups" } | 
/**  `["policy-group-runtime"]` — the running group's current member and delays. */
{ kind: "policyGroupRuntime" } | 
/**
 *  `["self-host"]` — the self-hosted node's settings, status, links and
 *  last network check.
 */
{ kind: "selfHost" };

/**
 *  A log line the **app** wrote, named by code.
 * 
 *  Only lines the app authors are in here. Everything the core process prints
 *  travels as [`LogLineBody::Core`] and is shown byte for byte.
 */
export type LogCode = { code: "connecting" } | { code: "connected" } | { code: "restarting" } | { code: "restarted" } | { code: "disconnecting" } | { code: "disconnected" } | { code: "restartingAfterChange"; reason: CoreFlowReason } | { code: "restartedAfterChange"; reason: CoreFlowReason } | 
/**  The core exited and was restarted straight away. */
{ code: "coreExitRestarted"; attempt: number } | 
/**  The core exited and a restart is scheduled. */
{ code: "coreExitRetryScheduled"; attempt: number; delayMs: number } | 
/**  The core exited too often and the app stopped restarting it. */
{ code: "coreExitGaveUp" } | { code: "nativeTunExited" } | 
/**
 *  An operation failed before the supervisor was touched, so the core that
 *  was already running is still serving traffic.
 */
{ code: "previousCoreStillRunning"; reason: CoreFlowReason } | 
/**  The supervisor could not say what state it ended up in. */
{ code: "runtimeStatusRefreshFailed"; reason: CoreFlowReason } | 
/**  A core operation failed; `detail` carries the error. */
{ code: "coreOperationFailed"; reason: CoreFlowReason } | 
/**  A change was committed and its follow-up work failed. */
{ code: "postCommitFailed" } | { code: "speedtestCancellationRequested" } | { code: "subscriptionAutoUpdateFailed"; remarks: string } | { code: "subscriptionAutoUpdateFinished"; remarks: string; imported: number } | { code: "selfHostStarted" } | { code: "selfHostStartFailed" } | { code: "selfHostStopped" } | 
/**  The node's core exited and a restart is scheduled. */
{ code: "selfHostRetryScheduled"; attempt: number; delayMs: number } | { code: "selfHostGaveUp" } | { code: "selfHostPortMapped"; port: number } | { code: "selfHostPortMappingFailed" };

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

/**  One line in the Logs panel. */
export type LogLineBody = 
/**
 *  Output of the core process, passed through unchanged. It is the core's
 *  own text in the core's own wording, so translating it is not ours to do.
 */
{ source: "core"; line: string } | 
/**
 *  A `tracing` event from the app's own instrumentation, forwarded to the
 *  panel so a failure is visible without opening the file log. Structured
 *  developer diagnostics with a module target — deliberately untranslated,
 *  for the same reason a stack trace is.
 */
{ source: "diagnostic"; line: string } | 
/**
 *  A line the app wrote *for the user*. `detail` is an untranslated
 *  technical diagnostic (an error's `Display`), shown after the translated
 *  sentence.
 */
{ source: "app"; code: LogCode; detail: string | null };

/**
 *  One line for the Logs panel.
 * 
 *  `body` says who wrote it: the core process (raw passthrough) or the app
 *  itself (a [`crate::LogCode`] the frontend translates). It used to be a
 *  single `line: String`, which meant every sentence the app logged reached
 *  the panel in English whatever the interface language was.
 */
export type LogLineEvent = {
	id: number,
	/**
	 *  When the app queued the line, in milliseconds since the Unix epoch.
	 *  Lines are held back while no Logs panel is open, so the time they
	 *  reach the webview says nothing about when they happened.
	 */
	loggedAtMs: number | null,
	level: LogLevel,
	body: LogLineBody,
};

export type MoveAction = "top" | "up" | "down" | "bottom" | "position";

export type MultiplexingSettings = {
	protocol: string,
	maxConnections: number,
	padding: boolean | null,
};

export type NetworkSettings = {
	tun: TunSettings,
	systemProxy: SystemProxySettings,
	inbounds: InboundSettings[],
};

/**
 *  What the backend is telling the user about, as a code the frontend
 *  translates.
 * 
 *  One variant per distinct message rather than a message assembled from
 *  parts: a notice is a whole sentence in every locale, and languages do not
 *  agree on how to build one out of a subject and a verb.
 */
export type NoticeCode = { code: "profileRefreshFailed" } | { code: "policyGroupRefreshFailed" } | { code: "subscriptionRefreshFailed" } | { code: "routingRefreshFailed" } | { code: "dnsRefreshFailed" } | { code: "proxyViewRefreshFailed" } | { code: "connectionModeRefreshFailed" } | { code: "settingsRefreshFailed" } | { code: "routingSavedRestartFailed" } | { code: "routingDeletedRestartFailed" } | { code: "routingSelectedRestartFailed" } | { code: "routingRuleSavedRestartFailed" } | { code: "routingRulesDeletedRestartFailed" } | { code: "routingRuleMovedRestartFailed" } | { code: "routingRulesResetRestartFailed" } | { code: "dnsSavedRestartFailed" } | { code: "tunSavedRestartFailed" } | { code: "connectionModeSavedRestartFailed" } | { code: "activeProfileRestartFailed" } | { code: "policyGroupSavedRestartFailed" } | { code: "settingsSavedRuntimeUpdateFailed" } | { code: "proxyModeSavedRuntimeUpdateFailed" } | { code: "policyGroupSelectionRuntimeUpdateFailed" } | { code: "settingsSavedSystemProxyUpdateFailed" } | { code: "systemProxyStatusRefreshFailed" } | { code: "tunStatusRefreshFailed" } | { code: "trayRefreshFailed" } | { code: "trayActionFailed" } | 
/**  The running node or policy group was deleted, so the connection stopped. */
{ code: "activeSelectionRemoved" } | { code: "coreStopped" } | { code: "nativeTunStopped" } | { code: "coreStartedSystemProxyFailed" } | { code: "systemProxyRestoreFailed" } | { code: "subscriptionAutoUpdateFailed"; remarks: string } | 
/**
 *  The connected node could not reach IPv6 destinations, so IPv6 is kept
 *  to direct routes while it is in use.
 */
{ code: "nodeIpv6Unsupported"; remarks: string } | 
/**  A node recorded without IPv6 egress reached IPv6 again. */
{ code: "nodeIpv6Restored"; remarks: string } | 
/**  The node's core kept exiting and was left stopped. */
{ code: "selfHostGaveUp" } | 
/**
 *  This device's public address changed; links handed out earlier point
 *  at the old one.
 */
{ code: "selfHostAddressChanged" } | { code: "selfHostRefreshFailed" };

/**  A stored group as the editor reads and writes it. */
export type PolicyGroup = {
	/**  Empty when creating a group. */
	id: string,
	name: string,
	strategy: PolicyGroupStrategy,
	/**  Every node of this subscription joins after the explicit members. */
	sourceSubscriptionId: string | null,
	/**  Created by a subscription import rather than by the user. */
	autoCreated: boolean,
	/**  The member a selector uses; `None` means the first member. */
	selectedProfileId: string | null,
	testUrl: string | null,
	intervalSeconds: number | null,
	toleranceMs: number | null,
	/**  Explicit members, in order. */
	memberIds: string[],
};

export type PolicyGroupEntry = {
	group: PolicyGroup,
	/**  Members resolved against the current node list, in connection order. */
	members: PolicyGroupMember[],
	/**  Whether connecting uses this group. */
	isActive: boolean,
};

export type PolicyGroupListing = {
	entries: PolicyGroupEntry[],
};

/**  One resolved member of a group. */
export type PolicyGroupMember = {
	profileId: string,
	remarks: string,
};

/**  The running group as the core reports it. */
export type PolicyGroupRuntime = {
	groupId: string,
	/**  The member traffic goes through right now. */
	nowProfileId: string | null,
	members: PolicyGroupRuntimeMember[],
};

/**  One member of the running group, with the core's last measurement. */
export type PolicyGroupRuntimeMember = {
	profileId: string,
	remarks: string,
	/**  `None` before a probe, or after a failed one. */
	delayMs: number | null,
};

/**  How a group picks the member traffic goes through. */
export type PolicyGroupStrategy = 
/**  The user picks the member. */
"selector" | 
/**  The member with the lowest measured delay, within a tolerance. */
"urlTest" | 
/**  The first reachable member, in list order. */
"fallback";

/**
 *  A running process or installed application offered by the per-app proxy
 *  picker; `process_name` is the executable basename sing-box matches on.
 */
export type ProcessCandidate = {
	displayName: string,
	processName: string,
	executablePath: string | null,
	source: ProcessCandidateSource,
};

export type ProcessCandidateSource = "runningProcess" | "installedApplication";

export type Profile = {
	id: string,
	subscriptionId: string | null,
	displayLog: boolean,
	remarks: string,
	protocol: ProfileProtocol,
	transport: ProfileTransport | null,
	tls: TlsSettings | null,
};

/**
 *  One node in full: what the editor, the details dialog and the calls that
 *  save or activate a node return. Lists carry [`ProfileSummaryEntry`]
 *  instead, so credentials, transport and TLS settings of every node do not
 *  cross IPC and sit in the renderer's cache on every refresh.
 */
export type ProfileDetails = {
	profile: Profile,
	metrics: ProfileMetrics,
	traffic: ProfileTraffic,
	isActive: boolean,
};

export type ProfileKind = "vmess" | "shadowsocks" | "socks" | "vless" | "trojan" | "hysteria2" | "tuic" | "wireGuard" | "http" | "anytls" | "naive";

export type ProfileMetrics = {
	delayMs: number,
	sort: number,
	/**
	 *  The last probe's outcome, decoded from the persisted `profile_ex`
	 *  column. `None` means the profile has never been tested.
	 */
	outcome: SpeedtestOutcome | null,
	ipInfo: string | null,
	countryCode: string | null,
};

export type ProfileProtocol = { kind: "vmess"; server: ServerEndpoint; uuid: string; cipher: string | null } | { kind: "shadowsocks"; server: ServerEndpoint; password: string; method: string; udpOverTcp: boolean } | { kind: "socks"; server: ServerEndpoint; username: string; password: string } | { kind: "vless"; server: ServerEndpoint; uuid: string; flow: string | null; encryption: string | null } | { kind: "trojan"; server: ServerEndpoint; password: string } | { kind: "hysteria2"; server: ServerEndpoint; password: string; portHops: string | null; obfuscationPassword: string | null } | { kind: "tuic"; server: ServerEndpoint; uuid: string; password: string; congestionControl: string | null } | { kind: "wireGuard"; server: ServerEndpoint; privateKey: string; peerPublicKey: string | null; presharedKey: string | null; interfaceAddress: string | null; allowedIps: string | null; reserved: string | null; mtu: number | null } | { kind: "http"; server: ServerEndpoint; username: string; password: string } | { kind: "anytls"; server: ServerEndpoint; password: string } | { kind: "naive"; server: ServerEndpoint; username: string; password: string; quic: boolean; congestionControl: string | null; insecureConcurrency: number | null; udpOverTcp: boolean };

/**  What the node table shows of a node. */
export type ProfileSummary = {
	id: string,
	subscriptionId: string | null,
	remarks: string,
	kind: ProfileKind,
	address: string,
	port: number,
};

/**
 *  One row of a node listing. `profile` keeps the nesting of
 *  [`ProfileDetails`], so a row reads the same way either shape does.
 */
export type ProfileSummaryEntry = {
	profile: ProfileSummary,
	metrics: ProfileMetrics,
	isActive: boolean,
};

/**
 *  A profile listing plus what is missing from it.
 * 
 *  `undecodableProfiles` counts stored profiles this build could not read —
 *  most often ones written by a newer build. Persistence skips those rows
 *  rather than failing the whole listing, so one unreadable server cannot take
 *  away the user's ability to see, connect to or delete the others.
 * 
 *  The count travels *with* the rows instead of arriving as a notice on the
 *  side: the listing is re-fetched on every profile query, so an event would
 *  repeat without end, while a field on the response lets the screen state the
 *  shortfall once, quietly, beside the list it belongs to.
 */
export type ProfileSummaryListing = {
	entries: ProfileSummaryEntry[],
	undecodableProfiles: number,
};

export type ProfileTraffic = {
	totalUpload: number | null,
	totalDownload: number | null,
	todayUpload: number | null,
	todayDownload: number | null,
	date: number | null,
};

export type ProfileTransport = { kind: "tcp"; header: string | null; host: string | null; path: string | null } | { kind: "websocket"; host: string | null; path: string | null } | { kind: "httpUpgrade"; host: string | null; path: string | null } | { kind: "http2"; host: string | null; path: string | null } | { kind: "grpc"; authority: string | null; serviceName: string | null; mode: string | null } | { kind: "quic"; host: string | null; path: string | null };

export type ProxyConnectionItem = {
	id: string | null,
	network: string | null,
	connectionType: string | null,
	host: string,
	source: string,
	destination: string,
	upload: number | null,
	download: number | null,
	start: string,
	chains: string[],
	rule: string | null,
	rulePayload: string | null,
	process: string | null,
	processPath: string | null,
};

export type ProxyConnectionsSnapshot = {
	downloadTotal: number | null,
	uploadTotal: number | null,
	connections: ProxyConnectionItem[],
};

export type ProxyMonitorState = "running" | "stopped" | "failed";

export type ProxyMonitorStatus = {
	state: ProxyMonitorState,
	running: boolean,
	stale: boolean,
	message: string | null,
};

export type ProxySettings = {
	/**
	 *  The persisted Clash traffic mode. Typed for the same reason as
	 *  [`SystemProxySettings::mode`]: `rename_all = "camelCase"` emits the very
	 *  canonical strings this field stores (`rule`, `global`, `unchanged`).
	 */
	trafficMode: TrafficMode,
};

export type QrCodeImage = {
	mimeType: string,
	svg: string,
};

export type QrScanFailureReason = "permissionDenied" | "unsupported" | "captureFailed" | "timeout" | "busy";

export type QrScanResult = {
	status: QrScanStatus,
	texts: string[],
	source: string,
	message: string | null,
	/**  Also set on a successful scan when some displays could not be captured. */
	failureReason: QrScanFailureReason | null,
};

export type QrScanStatus = "found" | "notFound" | "unavailable";

/**
 *  One invalidated cache plus the change that invalidated it.
 * 
 *  `reason` stays a free string on purpose: it is diagnostic (it names the
 *  command, and shows up in logs), never part of the contract the frontend
 *  switches on.
 */
export type QueryInvalidation = {
	scope: InvalidationScope,
	reason: string,
};

export type ResourceUpdateFile = {
	name: string,
	bytes: number,
	usedProxy: boolean,
};

export type Routing = Routing_Serialize | Routing_Deserialize;

export type RoutingRule = {
	id: string,
	kind: string | null,
	port: string | null,
	network: string | null,
	inboundTags: string[] | null,
	/**
	 *  `proxy`, `direct`, `block`, a node's remarks, or `group:<id>` for a
	 *  policy group.
	 */
	outbound: string | null,
	ip: string[] | null,
	domain: string[] | null,
	protocol: string[] | null,
	process: string[] | null,
	enabled: boolean,
	remarks: string | null,
	scope: RoutingRuleScope | null,
};

export type RoutingRuleScope = "all" | "routing" | "dns";

export type RoutingSettings = {
	domainStrategy: string,
};

export type Routing_Deserialize = {
	id: string,
	remarks: string,
	rules: RoutingRule[],
	enabled: boolean,
	locked: boolean,
	icon: string,
	singboxRulesetPath: string,
	singboxDomainStrategy: string,
	sort: number,
};

export type Routing_Serialize = {
	id: string,
	remarks: string,
	rules: RoutingRule[],
	enabled: boolean,
	locked: boolean,
	icon: string,
	singboxRulesetPath: string,
	singboxDomainStrategy: string,
	sort: number,
	isActive: boolean,
};

/**
 *  What the runtime is doing, as both an answer and an announcement.
 * 
 *  The four runtime commands return this, and `TransientStreamEvent::CoreState`
 *  carries exactly the same struct, so the frontend stores whichever arrives
 *  first without reshaping it. It used to be two types — this one plus an
 *  identically-shaped `CoreStateEvent` — which cost three converters in the
 *  shell and three more on the frontend to move one fact between them.
 * 
 *  `Deserialize` exists because it travels as an event payload, not because
 *  anything sends one to the backend.
 */
export type RuntimeStatusResponse = {
	/**  Milliseconds since this core connected; absent outside a confirmed connection. */
	connectedDurationMs: number | null,
	state: CoreState,
	/**
	 *  The confirmed running tunnel, independent of the saved connection mode.
	 *  Absent during transitions, pending cleanup, and local-proxy operation.
	 */
	activeTunBackend: TunBackend | null,
	activeProfileId: string | null,
	mainPid: number | null,
	prePid: number | null,
};

export type SelfHostAddressFamily = "ipv4" | "ipv6";

/**  Where a share link's address came from. */
export type SelfHostAddressKind = "custom" | "ipv4" | "ipv6";

/**  How an interface address relates to the internet. */
export type SelfHostAddressScope = 
/**  Globally routable. */
"public" | 
/**  RFC 1918 or IPv6 unique-local. */
"private" | 
/**  100.64.0.0/10, assigned by a carrier-grade NAT or an overlay network. */
"shared" | "linkLocal";

/**
 *  The part of the node the user edits.
 * 
 *  A port of `0` means "not chosen yet": the app picks a free one the first
 *  time the node is enabled and stores it, so links stay stable afterwards.
 */
export type SelfHostConfig = {
	enabled: boolean,
	/**  First part of every link's remark. Empty uses the product name. */
	deviceLabel: string,
	vlessEnabled: boolean,
	vlessPort: number,
	shadowsocksEnabled: boolean,
	shadowsocksPort: number,
	/**  The public site whose TLS handshake the REALITY inbound borrows. */
	realityServerName: string,
	realityServerPort: number,
	/**
	 *  A DDNS name or fixed address links should use instead of the detected
	 *  public addresses.
	 */
	customAddress: string | null,
	/**  Lets peers reach this device's local network. Loopback stays closed. */
	allowLanAccess: boolean,
	blockBittorrent: boolean,
	/**  Ask the router (UPnP IGD) to forward the node's ports. */
	upnpEnabled: boolean,
};

export type SelfHostEnvironmentReport = {
	/**  Milliseconds since the Unix epoch. */
	checkedAtMs: number | null,
	localAddresses: SelfHostLocalAddress[],
	ipv4: SelfHostFamilyReport,
	ipv6: SelfHostFamilyReport,
	portMapping: SelfHostPortMappingReport,
	firewall: SelfHostFirewallStatus,
	/**  Whether the probe service answered at all. */
	probeAvailable: boolean,
	selfTest: SelfHostSelfTest,
};

export type SelfHostFamilyReport = {
	family: SelfHostAddressFamily,
	publicAddress: string | null,
	nat: SelfHostNatKind,
	reachability: SelfHostReachability,
	/**  Set when `reachability` comes from the probe service, not inference. */
	verifiedByProbe: boolean,
	reasons: SelfHostReasonCode[],
};

export type SelfHostFirewallStatus = 
/**  The platform's firewall is not managed by the app. */
"notManaged" | "ruleMissing" | "rulePresent" | "unknown";

export type SelfHostLocalAddress = {
	interface: string,
	address: string,
	family: SelfHostAddressFamily,
	scope: SelfHostAddressScope,
};

/**  What sits between this device and the internet for one address family. */
export type SelfHostNatKind = 
/**  The public address is on this device. */
"none" | 
/**  One home router. */
"nat" | 
/**  The carrier shares one public address between customers. */
"carrierGrade" | 
/**  Two routers in a row. */
"double" | 
/**  No public address was learned for this family. */
"noConnectivity" | "unknown";

export type SelfHostPortMappingReport = {
	status: SelfHostPortMappingStatus,
	/**  The router's own WAN address, as it reported it. */
	gatewayExternalAddress: string | null,
	mappedPorts: number[],
	detail: string | null,
};

export type SelfHostPortMappingStatus = "disabled" | 
/**  No UPnP gateway answered on this network. */
"noGateway" | "mapped" | "failed";

/**  Why the node is not running as asked. The frontend translates the code. */
export type SelfHostProblem = 
/**  Neither protocol is switched on. */
"noProtocol" | 
/**  Another program already listens on one of the node's ports. */
"portInUse" | 
/**  The sing-box core is not installed. */
"coreMissing" | 
/**  The core exited on its own. */
"coreExited" | 
/**  The config could not be written or the core could not be launched. */
"startFailed";

export type SelfHostProtocol = "vless" | "shadowsocks";

/**  Whether a device on the internet can open a connection to the node. */
export type SelfHostReachability = 
/**  The probe service connected to every node port. */
"reachable" | 
/**  The probe service could not connect. */
"unreachable" | 
/**  No probe, but nothing in the way was found. */
"likelyReachable" | 
/**  No probe, and a router is in the way without a forwarding rule. */
"needsPortForward" | "noConnectivity" | "unknown";

/**
 *  One finding of the network check. Each code has its own explanation and
 *  suggestion in the locale files.
 */
export type SelfHostReasonCode = "publicAddressOnDevice" | "behindNat" | "carrierGradeNat" | "doubleNat" | "portMapped" | "upnpUnavailable" | "upnpFailed" | "probeReachable" | "probeTimedOut" | "probeRefused" | "probeUnavailable" | "noPublicAddress" | "ipv6FirewallUnknown" | "tunActive" | "firewallRuleMissing";

export type SelfHostRuntime = {
	status: SelfHostRuntimeStatus,
	problem: SelfHostProblem | null,
	/**  Untranslated diagnostic behind `problem`. */
	detail: string | null,
	/**  The port behind `PortInUse`. */
	port: number | null,
};

export type SelfHostRuntimeStatus = "stopped" | "starting" | "running" | 
/**  The core exited and a restart is scheduled. */
"retrying" | 
/**
 *  Starting failed, or the core kept exiting; the node stays down until the
 *  user changes something or switches it off and on.
 */
"failed";

/**
 *  A real client connecting to the node over loopback and fetching a page
 *  through it: the only check that catches a disguise site REALITY cannot
 *  use, which otherwise fails silently on every peer.
 */
export type SelfHostSelfTest = {
	vless: SelfHostSelfTestResult,
	shadowsocks: SelfHostSelfTestResult,
};

/**  Whether a client on this device could use the node through one protocol. */
export type SelfHostSelfTestResult = "passed" | "failed" | 
/**  The protocol is off, or the node was not running. */
"skipped";

export type SelfHostShareLink = {
	protocol: SelfHostProtocol,
	addressKind: SelfHostAddressKind,
	address: string,
	port: number,
	remarks: string,
	link: string,
};

/**  Everything the Self-hosted node page renders. */
export type SelfHostState = {
	config: SelfHostConfig,
	/**
	 *  What every setting falls back to: the page shows these as placeholders
	 *  and saves them to reset the node.
	 */
	defaults: SelfHostConfig,
	runtime: SelfHostRuntime,
	/**  Links for every enabled protocol at every usable address. */
	shareLinks: SelfHostShareLink[],
	/**  The latest network check, if one ran since launch. */
	environment: SelfHostEnvironmentReport | null,
	/**  Whether this platform can add a firewall rule for the node. */
	firewallRuleSupported: boolean,
};

/**  Live traffic through the node, read from its core. */
export type SelfHostStats = {
	activeConnections: number,
	uploadTotalBytes: number | null,
	downloadTotalBytes: number | null,
};

export type ServerEndpoint = {
	address: string,
	port: number,
};

export type ServerStatItem = {
	indexId: string,
	totalUp: number | null,
	totalDown: number | null,
	todayUp: number | null,
	todayDown: number | null,
	dateNow: number | null,
};

export type SettingsApplyAction = "none" | "reconnect" | "reapplyProxy";

export type SettingsApplyStatus = {
	action: SettingsApplyAction,
	connected: boolean,
};

export type ShellTabTarget = "profiles" | "proxyConnections" | "logs";

/**
 *  How a probe ended, as a code rather than a sentence.
 * 
 *  Persisted in `profile_ex.message` using the same camelCase codes as IPC.
 *  Unrecognised stored values become `Unknown` without hiding the profile.
 */
export type SpeedtestOutcome = 
/**  Selected and queued behind another probe. */
"waiting" | 
/**  The probe is running right now. */
"testing" | 
/**  The probe finished; `delay` carries the measurement. */
"completed" | "timedOut" | "proxyConnectFailed" | "proxyConnectionRefused" | "proxyConnectionClosed" | "cancelled" | 
/**  The run ended before this profile's turn came up. */
"skipped" | 
/**  The profile's own configuration is invalid, so nothing was probed. */
"invalidProfile" | 
/**  The test core could not be started, or its config could not be written. */
"coreUnavailable" | 
/**  No free local port was available for the probe. */
"noAvailablePort" | 
/**
 *  The running core predates this node or its current settings (it was
 *  added or edited after connecting), so measuring needs a reconnect.
 */
"reconnectRequired" | 
/**  A failure with no more specific code. */
"failed" | 
/**  A stored value this build cannot classify, without dropping the row. */
"unknown";

export type SpeedtestRequest = {
	target: SpeedtestTarget,
};

/**
 *  One profile's probe result.
 * 
 *  `detail` is an untranslated technical line shown under the outcome. It is
 *  never persisted and never carries a local filesystem path: the failure
 *  classification used to fall through to the error's own `Display`, which for
 *  a config-write failure printed the app-data directory into a column the
 *  profile table renders.
 */
export type SpeedtestResult = {
	indexId: string,
	delay: number | null,
	outcome: SpeedtestOutcome,
	detail: string | null,
	ipInfo: string | null,
	countryCode: string | null,
};

export type SpeedtestRunResult = {
	cancelled: boolean,
	selectedCount: number,
	completedCount: number,
	results: SpeedtestResult[],
};

export type SpeedtestSettings = {
	timeoutSeconds: number,
	latencyUrl: string,
	ipLookupUrl: string,
	pageSize: number | null,
	delayIntervalSeconds: number | null,
};

export type SpeedtestStatus = {
	running: boolean,
};

export type SpeedtestTarget = { scope: "profiles"; profileIds: string[] };

export type StatisticsSnapshot = {
	activeProfileId: string | null,
	proxyUploadBytesPerSecond: number | null,
	proxyDownloadBytesPerSecond: number | null,
	directUploadBytesPerSecond: number | null,
	directDownloadBytesPerSecond: number | null,
	uploadBytesPerSecond: number | null,
	downloadBytesPerSecond: number | null,
	serverStat: ServerStatItem | null,
};

export type Subscription = {
	id: string,
	remarks: string,
	url: string,
	additionalUrl: string,
	enabled: boolean,
	userAgent: string,
	sort: number,
	filter: string | null,
	converterTarget: string | null,
	autoUpdateIntervalMinutes: number | null,
};

/**
 *  Usage metadata reported by the subscription server on the latest successful
 *  fetch (`subscription-userinfo` and `profile-title` response headers).
 */
export type SubscriptionMetadata = {
	subscriptionId: string,
	uploadBytes: number | null,
	downloadBytes: number | null,
	totalBytes: number | null,
	expireAt: number | null,
	lastUpdateAt: number | null,
	profileTitle: string | null,
};

export type SubscriptionUpdateOutcome = {
	subscriptionId: string,
	status: SubscriptionUpdateStatus,
	reason: SubscriptionUpdateReason,
	imported: number,
	removedExisting: number,
	diagnostic: string | null,
};

export type SubscriptionUpdateReason = "updated" | "invalidSource" | "sourceChanged" | "emptyContent" | "downloadFailed" | "noImportableNodes" | "invalidFilter";

export type SubscriptionUpdateResult = {
	updated: number,
	skipped: number,
	imported: number,
	removedExisting: number,
	messages: string[],
	outcomes: SubscriptionUpdateOutcome[],
};

export type SubscriptionUpdateStatus = "success" | "skipped" | "failed";

export type SystemProxyManagement = "automatic" | "unsupported";

export type SystemProxySettings = {
	/**
	 *  The persisted OS-proxy mode. Typed rather than a `String`: the enum's
	 *  `rename_all = "camelCase"` emits exactly the values this field stores
	 *  (`forcedClear`, `forcedChange`, `unchanged`), and `voya-db` pins that
	 *  with a value test. The retired `pac` value is normalized at startup.
	 */
	mode: SystemProxyType,
	exceptions: string,
	bypassLocal: boolean,
};

/**
 *  The OS proxy state, as both an answer and an announcement.
 * 
 *  `TransientStreamEvent::SysProxyChanged` carries this struct; the narrower
 *  `SysProxyChanged` it replaced duplicated four of these fields and re-declared
 *  `SystemProxyType` under a second name.
 */
export type SystemProxyStatusResponse = {
	management: SystemProxyManagement,
	requestedMode: SystemProxyType,
	/**
	 *  The app's applied policy; always Unchanged where the system proxy is
	 *  unsupported.
	 */
	effectiveMode: SystemProxyType,
	proxy: string | null,
	exceptions: string,
};

export type SystemProxyType = "forcedClear" | "forcedChange" | "unchanged";

export type ThemeMode = "system" | "light" | "dark";

export type TitleBarLayout = "macos" | "windows" | "none";

/**
 *  How TLS handshakes are split to get past filters that match on the
 *  ClientHello.
 */
export type TlsFragmentMode = "off" | 
/**  sing-box `tls.fragment`: the ClientHello is split into TCP segments. */
"tlsHello" | 
/**  sing-box `tls.record_fragment`: the ClientHello is split into TLS records. */
"record";

export type TlsMode = "tls" | "reality";

export type TlsSettings = {
	mode: TlsMode,
	serverName: string | null,
	alpn: string[],
	realityPublicKey: string | null,
	realityShortId: string | null,
	certificatePem: string | null,
	echConfig: string[],
};

export type TrafficMode = "rule" | "global" | "unchanged";

export type TrafficModeResponse = {
	mode: TrafficMode,
};

/**
 *  Live state that is not a query cache.
 * 
 *  The three status variants carry the very structs their commands return, so
 *  the frontend stores an event payload and a command result interchangeably.
 *  They used to be narrower parallel DTOs, which cost a converter in the shell
 *  and another on the frontend for each one.
 */
export type TransientStreamEvent = 
/**
 *  Logs-panel lines in the order they were written, delivered at most
 *  once per batch window instead of one event per line.
 */
{ kind: "logLines"; payload: LogLineEvent[] } | { kind: "coreState"; payload: RuntimeStatusResponse } | { kind: "statistics"; payload: StatisticsSnapshot } | { kind: "sysProxyChanged"; payload: SystemProxyStatusResponse } | { kind: "tunChanged"; payload: TunStatus } | { kind: "proxyMonitorStatus"; payload: ProxyMonitorStatus } | { kind: "proxyConnections"; payload: ProxyConnectionsSnapshot } | 
/**
 *  Speedtest results in the order they were reached. A run's start and a
 *  cancel settle every selected node at once and arrive as one event; a
 *  measured node arrives on its own.
 */
{ kind: "speedtestResults"; payload: SpeedtestResult[] };

export type TunBackend = "process" | "macosPacketTunnel" | "windowsService" | "iosPacketTunnel" | "androidVpnService" | "unsupported";

export type TunPlatform = "windows" | "linux" | "macos" | "ios" | "android" | "other";

export type TunPreflight = {
	platform: TunPlatform,
	state: TunPreflightState,
	notes: string[],
	routeRestoreNote: string,
	windowsCleanupDevices: string[],
};

export type TunPreflightState = "ready" | "needsElevation" | "manualCheck" | "unsupported";

export type TunProviderDiagnostics = {
	backend: TunBackend,
	containerPath: string | null,
	statusPath: string | null,
	logPath: string | null,
	packagingMode: string | null,
	expectedProviderPath: string | null,
	systemExtensionState: string | null,
	registrationPaths: string[],
	statusState: string | null,
	lastError: string | null,
	providerBundlePath: string | null,
	breadcrumbs: string[],
	providerLogTail: string[],
	hostLogTail: string[],
	message: string | null,
};

export type TunProviderState = "notApplicable" | "missingComponent" | "permissionRequired" | "stopped" | "starting" | "running" | "error";

export type TunSettings = {
	enabled: boolean,
	autoRoute: boolean,
	strictRoute: boolean,
	stack: string,
	mtu: number,
	ipv6Enabled: boolean,
	icmpRouting: string,
};

export type TunStatus = {
	enabled: boolean,
	backend: TunBackend,
	providerState: TunProviderState,
	allowEnableTun: boolean,
	requiresElevation: boolean,
	elevationGranted: boolean,
	needsVpnPermission: boolean,
	needsServiceInstall: boolean,
	nativeComponentReady: boolean,
	lastProviderError: string | null,
	providerPathMismatch: boolean,
	resolvedProviderPath: string | null,
	expectedProviderPath: string | null,
	restoreOnDisconnect: boolean,
	preflight: TunPreflight,
};

/**
 *  Why a submitted or generated value was rejected.
 * 
 *  Produced by `voya_core`'s node/group validators, by the DNS pane's checks
 *  and by settings validation. [`ValidationCode::Untranslated`] is the
 *  deliberate escape hatch for the managers that have no code yet: it is
 *  greppable, it shows the English diagnostic verbatim, and adding a code for
 *  one is a purely additive change.
 */
export type ValidationCode = { code: "subscriptionReadOnly"; subscriptionId: string } | { code: "invalidAddress" } | { code: "invalidPort" } | { code: "invalidPassword" } | { code: "invalidFlow" } | { code: "invalidShadowsocksMethod" } | { code: "invalidRealityPublicKey" } | { code: "unsupportedProtocolNetwork"; protocol: string; network: string } | { code: "unsupportedShadowsocksNetwork"; network: string } | { code: "routingRuleWithoutOutbound"; rule: string } | { code: "routingRuleOutboundNotFound"; rule: string; outbound: string } | { code: "policyGroupWithoutValidMembers"; group: string } | { code: "policyGroupWithoutMembers" } | { code: "policyGroupIntervalOutOfRange"; min: number; max: number } | { code: "policyGroupToleranceOutOfRange"; min: number; max: number } | { code: "policyGroupTestUrlInvalid" } | { code: "dnsAddressEmpty" } | { code: "dnsAddressPort"; port: string } | { code: "dnsHostsLine"; line: number } | { code: "dnsExpectedIps" } | { code: "textRequired" } | { code: "textTooLong" } | { code: "textControlCharacters" } | { code: "tooManyItems" } | { code: "unsupportedSettingsSchema"; found: number; expected: number } | { code: "tunMtuOutOfRange"; min: number; max: number } | { code: "negativeHysteriaBandwidth" } | { code: "hysteriaHopIntervalTooShort"; minimumSeconds: number } | { code: "fragmentFallbackDelayOutOfRange"; min: number; max: number } | { code: "inboundPortOutOfRange"; min: number; max: number } | { code: "inboundCredentialsIncomplete" } | { code: "inboundRequired" } | { code: "selfHostPortOutOfRange"; min: number; max: number } | 
/**  Two of the node's ports are the same. */
{ code: "selfHostPortsCollide" } | 
/**  Neither protocol is switched on. */
{ code: "selfHostNoProtocol" } | 
/**
 *  A rejection this contract has no code for. The English `message` is the
 *  failing manager's own diagnostic and is rendered verbatim.
 */
{ code: "untranslated"; message: string };

/**
 *  One rejected value.
 * 
 *  `field` is a stable identifier, not a display label: the DNS pane keys its
 *  inputs by `direct`/`remote`/`bootstrap`/`hosts`, the settings surface by its
 *  contract path (`network.tun.mtu`), and the group builder by `children`.
 */
export type ValidationIssue = {
	field: string,
	code: ValidationCode,
	/**  Empty unless the validator descended into a group or a rule outbound. */
	scope: ValidationScope[],
};

/**
 *  Where a validation message was produced, when the validator had to walk
 *  into a group's children or a routing rule's outbound to find it.
 * 
 *  This replaces the `"group child A / B: "` prefixes the validators used to
 *  glue onto the front of a message, which made the message itself
 *  untranslatable. The frontend renders the breadcrumb from these entries and
 *  the translated message after it.
 */
export type ValidationScope = { kind: "routingRuleOutbound"; rule: string; outbound: string } | { kind: "policyGroupMember"; group: string; member: string };

export type WindowChromeConfig = {
	titleBarLayout: TitleBarLayout,
};
