/**
 * Derives the transport-agnostic TypeScript contract from the Tauri Specta
 * bindings.
 *
 * `apps/desktop/src/ipc/bindings.ts` is generated from the Rust `specta` types
 * and is the single source of truth, but it cannot be shared: it imports
 * `@tauri-apps/api`, which ADR-0002 confines to `apps/desktop/src/ipc`. This
 * module strips the Tauri plumbing and keeps what any frontend needs — the DTOs
 * and the command signatures — so `@voya/contracts` stays a derivative of the
 * generated file rather than a hand-written mirror of the Rust types.
 *
 * Two deliberate shape changes:
 *
 * - Commands become a `VoyaCommands` type returning `Promise<T>` instead of
 *   `Promise<CommandResult<T>>`. The result envelope is a transport detail;
 *   every caller already goes through a wrapper that throws on the error arm,
 *   so the shared contract describes the unwrapped call a feature actually
 *   makes. A platform binding declares `satisfies VoyaCommands` to prove it
 *   implements the whole surface.
 * - Event channels become a `VoyaEventChannels` map keyed by the same names the
 *   backend emits, so a non-Tauri transport has one decoder per channel.
 *
 * Two further artifacts come out of the same parse, for the transports that are
 * not Tauri: `commands.ts` (the wire name and argument names behind each
 * command, so a generic transport can rebuild Tauri's named-argument object
 * from a positional call) and `commands.json` (the wire names alone, which the
 * Rust mobile host reads to prove it has taken a decision about every one).
 */

const COMMANDS_MARKER = "/** Commands */";
const EVENTS_MARKER = "/** Events */";
const TYPES_MARKER = "/* Types */";
const RUNTIME_MARKER = "/* Tauri Specta runtime */";

const INVOKE_MARKER = "__TAURI_INVOKE(";
const RETURN_END_MARKER = ", AppError>(__TAURI_INVOKE(";
const RETURN_START_MARKER = ") => typedError<";

const HEADER = `// Derived from apps/desktop/src/ipc/bindings.ts by scripts/quality/contracts-source.mjs.
// Do not edit this file manually — run \`pnpm generate:bindings\`.
`;

function sliceBetween(source, startMarker, endMarker) {
  const start = source.indexOf(startMarker);
  if (start === -1) {
    throw new Error(`bindings.ts is missing the ${startMarker} marker`);
  }

  const from = start + startMarker.length;
  const end = source.indexOf(endMarker, from);
  if (end === -1) {
    throw new Error(`bindings.ts is missing the ${endMarker} marker after ${startMarker}`);
  }

  return source.slice(from, end);
}

const ENTRY_START_PATTERN = /^\t([A-Za-z0-9_]+): \(/;
const DOC_LINE_PATTERN = /^\s*(\/\*\*|\*\/|\*)/;

/**
 * Pulls the signature out of one command entry.
 *
 * Two commands (`policyGroupRuntime`, `testPolicyGroupDelay`) return an inline
 * object type that specta emits across several lines, so an entry is not
 * necessarily one line. Anchoring the return type on the literal
 * `, AppError>(__TAURI_INVOKE(` avoids a balanced-generics scan while still
 * tolerating `{`, `|` and `[]` inside it.
 */
function parseEntry(name, text) {
  const returnStart = text.indexOf(RETURN_START_MARKER);
  if (returnStart === -1) {
    throw new Error(`Command ${name} has no recognizable typedError signature`);
  }

  const returnEnd = text.indexOf(RETURN_END_MARKER, returnStart);
  if (returnEnd === -1) {
    throw new Error(`Command ${name} has no recognizable AppError return arm`);
  }

  const parametersStart = text.indexOf("(");
  const parameters = text.slice(parametersStart + 1, returnStart);
  const returnType = text.slice(returnStart + RETURN_START_MARKER.length, returnEnd);

  if (parameters.includes("\n")) {
    throw new Error(`Command ${name} has a multi-line parameter list, which this generator cannot re-indent`);
  }

  // specta emits the inner lines of an inline object type at a single tab,
  // which reads as dedented once the entry is nested in `VoyaCommands`.
  const indentedReturnType = returnType
    .split("\n")
    .map((line, index) => (index === 0 ? line : `\t${line}`))
    .join("\n");

  const invocation = parseInvocation(name, text);
  assertArgumentsMatch(name, parameters, invocation.params);

  return { name, parameters, returnType: indentedReturnType, ...invocation };
}

/**
 * The invoked argument names must be the declared parameters, in order.
 *
 * A generic transport rebuilds the named object from positional arguments, so
 * a silent disagreement here would send `{ b: a, a: b }` and only fail at
 * runtime, on the device.
 */
function assertArgumentsMatch(name, parameters, args) {
  const declared = parameters.trim()
    ? parameters.split(",").map((parameter) => parameter.split(":")[0].trim())
    : [];

  if (declared.join(",") !== args.join(",")) {
    throw new Error(
      `Command ${name} declares (${declared.join(", ")}) but invokes with (${args.join(", ")})`,
    );
  }
}

const INVOCATION_PATTERN = /^"([a-z0-9_]+)"(?:\s*,\s*\{([^}]*)\})?\s*\)/;

/**
 * The wire call behind one command: the snake_case name Tauri registered it
 * under and the argument names it expects, in declaration order.
 *
 * A non-Tauri transport takes positional arguments from a `VoyaCommands` call
 * and has to rebuild the very same named object, so the names are part of the
 * contract rather than a detail of this file.
 */
function parseInvocation(name, text) {
  const invokeStart = text.indexOf(INVOKE_MARKER);
  const match = INVOCATION_PATTERN.exec(text.slice(invokeStart + INVOKE_MARKER.length));
  if (!match) {
    throw new Error(`Command ${name} has no recognizable __TAURI_INVOKE call`);
  }

  const params = (match[2] ?? "")
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => {
      // specta emits shorthand (`{ enabled }`); a renamed key would still be
      // `key: value`, and the key is what goes on the wire.
      const key = entry.split(":")[0].trim();
      if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key)) {
        throw new Error(`Command ${name} passes an argument this generator cannot name: ${entry}`);
      }
      return key;
    });

  return { params, wireName: match[1] };
}

export function parseCommands(commandsBlock) {
  const commands = [];
  let pendingDoc = [];
  let current = null;

  const finish = () => {
    if (!current) {
      return;
    }
    commands.push({ ...parseEntry(current.name, current.lines.join("\n")), doc: current.doc });
    current = null;
  };

  for (const line of commandsBlock.split("\n")) {
    if (current) {
      current.lines.push(line);
      if (current.lines.join("\n").includes(INVOKE_MARKER)) {
        finish();
      }
      continue;
    }

    const match = ENTRY_START_PATTERN.exec(line);
    if (match) {
      current = { name: match[1], lines: [line], doc: pendingDoc };
      pendingDoc = [];
      if (line.includes(INVOKE_MARKER)) {
        finish();
      }
      continue;
    }

    if (DOC_LINE_PATTERN.test(line)) {
      pendingDoc.push(line);
      continue;
    }

    // Blank lines keep a doc run alive; anything else ends one that never
    // attached to a command.
    if (line.trim().length > 0) {
      pendingDoc = [];
    }
  }

  finish();

  // A silently dropped command is the failure mode that matters here: the
  // contract would still compile and a platform binding would still satisfy it.
  const invocations = commandsBlock.split(INVOKE_MARKER).length - 1;
  if (commands.length !== invocations) {
    throw new Error(
      `Parsed ${commands.length} commands but bindings.ts invokes ${invocations} — the generator shape changed`,
    );
  }

  if (commands.length === 0) {
    throw new Error("No commands parsed out of bindings.ts — the generator shape changed");
  }

  return commands;
}

const EVENT_PATTERN = /^\t([A-Za-z0-9_]+): makeEvent<([A-Za-z0-9_]+)>\("([^"]+)"\)/;

export function parseEvents(eventsBlock) {
  const events = [];

  for (const line of eventsBlock.split("\n")) {
    const match = EVENT_PATTERN.exec(line);
    if (match) {
      events.push({ key: match[1], payloadType: match[2], channel: match[3] });
    }
  }

  const declarations = eventsBlock.split("makeEvent<").length - 1;
  if (events.length !== declarations) {
    throw new Error(`Parsed ${events.length} events but bindings.ts declares ${declarations}`);
  }

  if (events.length === 0) {
    throw new Error("No events parsed out of bindings.ts — the generator shape changed");
  }

  return events;
}

function renderCommands(commands) {
  const members = commands.map((command) => {
    const doc = command.doc.length > 0 ? `${command.doc.join("\n")}\n` : "";
    return `${doc}\t${command.name}: (${command.parameters}) => Promise<${command.returnType}>,`;
  });

  return [
    "/**",
    " *  Every IPC command, with the result envelope already unwrapped.",
    " *",
    " *  A platform binding declares `satisfies VoyaCommands` so dropping or",
    " *  mistyping a command is a compile error rather than a runtime surprise.",
    " */",
    "export type VoyaCommands = {",
    ...members,
    "};",
  ].join("\n");
}

function renderEvents(events) {
  const channels = events.map(
    (event) => `\t${event.key}: { channel: "${event.channel}"; payload: ${event.payloadType} },`,
  );

  return [
    "/**",
    " *  The three backend event channels and the payload each carries.",
    " *",
    " *  `channel` is the wire name the backend emits under; a transport that is",
    " *  not Tauri still has to route by it.",
    " */",
    "export type VoyaEventChannels = {",
    ...channels,
    "};",
    "",
    "export type VoyaEventName = keyof VoyaEventChannels;",
    "",
    'export type VoyaEventPayload<Name extends VoyaEventName> = VoyaEventChannels[Name]["payload"];',
  ].join("\n");
}

const WIRE_HEADER = `// Derived from apps/desktop/src/ipc/bindings.ts by scripts/quality/contracts-source.mjs.
// Do not edit this file manually — run \`pnpm generate:bindings\`.
`;

function renderCommandWire(commands) {
  const members = commands.map((command) => {
    const params = command.params.map((param) => `"${param}"`).join(", ");
    return `\t${command.name}: { name: "${command.wireName}", params: [${params}] },`;
  });

  return [
    WIRE_HEADER,
    'import type { VoyaCommands } from "./generated";',
    "",
    "/**",
    " * How each command travels: the name the backend registered it under and the",
    " * arguments it expects, in the order `VoyaCommands` passes them.",
    " *",
    " * Tauri takes a named object rather than a positional list, and a native",
    " * module has to send the same wire shape, so a transport rebuilds the object",
    " * from this table instead of repeating 70-odd hand-written wrappers.",
    " */",
    "export const VOYA_COMMAND_WIRE = {",
    ...members,
    '} as const satisfies Record<keyof VoyaCommands, { name: string; params: readonly string[] }>;',
    "",
  ].join("\n");
}

/**
 * Every wire command name, sorted.
 *
 * `crates/voya-mobile-ffi` reads this file so a command added in Rust cannot
 * slip past the mobile host without either a dispatcher or an explicit entry on
 * its unsupported list.
 */
function renderCommandNames(commands) {
  const names = commands.map((command) => command.wireName).toSorted();
  const duplicate = names.find((name, index) => name === names[index + 1]);
  if (duplicate) {
    throw new Error(`Two commands share the wire name ${duplicate}`);
  }

  return `${JSON.stringify(names, null, 2)}\n`;
}

export function generateCommandWire(bindingsSource) {
  return renderCommandWire(parseCommands(sliceBetween(bindingsSource, COMMANDS_MARKER, EVENTS_MARKER)));
}

export function generateCommandNames(bindingsSource) {
  return renderCommandNames(parseCommands(sliceBetween(bindingsSource, COMMANDS_MARKER, EVENTS_MARKER)));
}

export function generateContractsSource(bindingsSource) {
  const commandsBlock = sliceBetween(bindingsSource, COMMANDS_MARKER, EVENTS_MARKER);
  const eventsBlock = sliceBetween(bindingsSource, EVENTS_MARKER, TYPES_MARKER);
  const typesBlock = sliceBetween(bindingsSource, TYPES_MARKER, RUNTIME_MARKER);

  const commands = parseCommands(commandsBlock);
  const events = parseEvents(eventsBlock);

  return [
    HEADER,
    renderCommands(commands),
    "",
    renderEvents(events),
    "",
    "/* Types */",
    typesBlock.trim(),
    "",
  ].join("\n");
}
