// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	loadUiPreferences: () => typedError<AppearanceSettings, AppError>(__TAURI_INVOKE("load_ui_preferences")),
	loadAppSettings: () => typedError<AppSettingsV1, AppError>(__TAURI_INVOKE("load_app_settings")),
	getSettingsApplyStatus: () => typedError<SettingsApplyStatus, AppError>(__TAURI_INVOKE("get_settings_apply_status")),
	applyPendingSettings: () => typedError<SettingsApplyStatus, AppError>(__TAURI_INVOKE("apply_pending_settings")),
	/**
	 *  Thin adapter over `voya_app::settings_flow`.
	 * 
	 *  Validation, the pre-commit OS side effects, the commit and both rollback
	 *  paths are the transaction in voya-app, where they are unit-tested; the only
	 *  things left here are turning `AppError`s back out of it and dispatching the
	 *  runtime action it selected.
	 */
	saveAppSettings: (settings: AppSettingsV1) => typedError<AppSettingsV1, AppError>(__TAURI_INVOKE("save_app_settings", { settings })),
	generateQrCode: (content: string) => typedError<QrCodeImage, AppError>(__TAURI_INVOKE("generate_qr_code", { content })),
	scanScreenQr: () => typedError<QrScanResult, AppError>(__TAURI_INVOKE("scan_screen_qr")),
	scanClipboardQr: () => typedError<QrScanResult, AppError>(__TAURI_INVOKE("scan_clipboard_qr")),
	/**  Returns an empty string when the clipboard holds no text. */
	readClipboardText: () => typedError<string, AppError>(__TAURI_INVOKE("read_clipboard_text")),
	fetchCertificate: (request: CertificateFetchRequest) => typedError<CertificateFetchResult, AppError>(__TAURI_INVOKE("fetch_certificate", { request })),
	calculateCertificateSha256: (pem: string) => typedError<string[], AppError>(__TAURI_INVOKE("calculate_certificate_sha256", { pem })),
	/**
	 *  Trigger the one-time native authorization dialog and, on success, install
	 *  the passwordless elevation launcher. No admin password is stored.
	 */
	tunRequestElevation: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("tun_request_elevation")),
	connectActiveProfile: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("connect_active_profile")),
	disconnectCore: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("disconnect_core")),
	restartCore: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("restart_core")),
	runtimeStatus: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("runtime_status")),
	systemProxyStatus: () => typedError<SystemProxyStatusResponse, AppError>(__TAURI_INVOKE("system_proxy_status")),
	/**  Refresh the observed system proxy state and notify the renderer. */
	recheckSystemProxy: () => typedError<SystemProxyStatusResponse, AppError>(__TAURI_INVOKE("recheck_system_proxy")),
	/**  Fixed destination; renderer input cannot turn this into an arbitrary opener. */
	openNetworkSettings: () => typedError<null, AppError>(__TAURI_INVOKE("open_network_settings")),
	/**
	 *  Changes only the system proxy flavor. Same transaction as
	 *  `set_connection_mode`: the mode is persisted always, the machine is only
	 *  touched while a core is running.
	 */
	setSystemProxyMode: (mode: SystemProxyType) => typedError<SystemProxyStatusResponse, AppError>(__TAURI_INVOKE("set_system_proxy_mode", { mode })),
	connectionModeStatus: () => typedError<ConnectionModeStatus, AppError>(__TAURI_INVOKE("connection_mode_status")),
	/**
	 *  Switches the app between system proxy and TUN mode.
	 * 
	 *  The transaction itself is `voya_app::connection_mode`: the mode is always
	 *  persisted, but the machine's proxy settings are only rewritten while the
	 *  supervisor reports `Connected` — a mode pointed at a port nothing is
	 *  listening on would black-hole every request. Only a TUN flag change needs a
	 *  running core to be restarted.
	 */
	setConnectionMode: (mode: ConnectionMode, pacEnabled: boolean | null) => typedError<ConnectionModeStatus, AppError>(__TAURI_INVOKE("set_connection_mode", { mode, pacEnabled })),
	tunStatus: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("tun_status")),
	tunProviderDiagnostics: () => typedError<TunProviderDiagnostics, AppError>(__TAURI_INVOKE("tun_provider_diagnostics")),
	setTunEnabled: (enabled: boolean) => typedError<TunStatus, AppError>(__TAURI_INVOKE("set_tun_enabled", { enabled })),
	loadDnsSettings: () => typedError<DnsSettings, AppError>(__TAURI_INVOKE("load_dns_settings")),
	saveDnsSettings: (settings: DnsSettings) => typedError<DnsSettings, AppError>(__TAURI_INVOKE("save_dns_settings", { settings })),
	listProfiles: (subscriptionId: string | null, filter: string | null) => typedError<ProfileListing, AppError>(__TAURI_INVOKE("list_profiles", { subscriptionId, filter })),
	saveProfile: (profile: Profile) => typedError<ProfileListEntry, AppError>(__TAURI_INVOKE("save_profile", { profile })),
	deleteProfiles: (indexIds: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_profiles", { indexIds })),
	exportProfileShareLinks: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_share_links", { indexIds })),
	exportProfileShareLinksBase64: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_share_links_base64", { indexIds })),
	exportProfileVoyaBundle: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_voya_bundle", { indexIds })),
	setActiveProfile: (indexId: string) => typedError<ProfileListEntry, AppError>(__TAURI_INVOKE("set_active_profile", { indexId })),
	moveProfile: (subscriptionId: string | null, indexId: string, action: MoveAction, position: number | null) => typedError<ProfileListEntry[], AppError>(__TAURI_INVOKE("move_profile", { subscriptionId, indexId, action, position })),
	listSubscriptions: () => typedError<Subscription[], AppError>(__TAURI_INVOKE("list_subscriptions")),
	listSubscriptionMetadata: () => typedError<SubscriptionMetadata[], AppError>(__TAURI_INVOKE("list_subscription_metadata")),
	saveSubscription: (item: Subscription) => typedError<Subscription, AppError>(__TAURI_INVOKE("save_subscription", { item })),
	deleteSubscriptions: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_subscriptions", { ids })),
	importProfilesFromText: (text: string, subscriptionId: string | null) => typedError<ImportProfilesResult, AppError>(__TAURI_INVOKE("import_profiles_from_text", { text, subscriptionId })),
	updateSubscriptions: (subscriptionId: string | null, preferProxy: boolean, proxyUrl: string | null) => typedError<SubscriptionUpdateResult, AppError>(__TAURI_INVOKE("update_subscriptions", { subscriptionId, preferProxy, proxyUrl })),
	listRoutings: () => typedError<Routing_Serialize[], AppError>(__TAURI_INVOKE("list_routings")),
	saveRouting: (item: Routing_Deserialize) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("save_routing", { item })),
	deleteRoutings: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_routings", { ids })),
	setActiveRouting: (id: string) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("set_active_routing", { id })),
	saveRoutingRule: (routingId: string, rule: RoutingRule) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("save_routing_rule", { routingId, rule })),
	deleteRoutingRules: (routingId: string, ruleIds: string[]) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("delete_routing_rules", { routingId, ruleIds })),
	moveRoutingRule: (routingId: string, ruleId: string, action: MoveAction, position: number | null) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("move_routing_rule", { routingId, ruleId, action, position })),
	/**
	 *  Enumerates running processes (and installed applications where the OS
	 *  makes that cheap) for the per-app proxy picker. Blocking OS enumeration
	 *  runs off the async runtime.
	 */
	listProcessCandidates: () => typedError<ProcessCandidate[], AppError>(__TAURI_INVOKE("list_process_candidates")),
	proxyListConnections: () => typedError<ProxyConnectionsSnapshot, AppError>(__TAURI_INVOKE("proxy_list_connections")),
	proxyCloseConnection: (connectionId: string | null) => typedError<ProxyConnectionsSnapshot, AppError>(__TAURI_INVOKE("proxy_close_connection", { connectionId })),
	proxySetTrafficMode: (mode: TrafficMode) => typedError<TrafficModeResponse, AppError>(__TAURI_INVOKE("proxy_set_traffic_mode", { mode })),
	proxyStartMonitor: () => typedError<ProxyMonitorStatus, AppError>(__TAURI_INVOKE("proxy_start_monitor")),
	proxyStopMonitor: () => typedError<ProxyMonitorStatus, AppError>(__TAURI_INVOKE("proxy_stop_monitor")),
	runSpeedtest: (request: SpeedtestRequest) => typedError<SpeedtestRunResult, AppError>(__TAURI_INVOKE("run_speedtest", { request })),
	cancelSpeedtest: () => typedError<SpeedtestStatus, AppError>(__TAURI_INVOKE("cancel_speedtest")),
	speedtestStatus: () => typedError<SpeedtestStatus, AppError>(__TAURI_INVOKE("speedtest_status")),
	appUpdateStatus: () => typedError<AppUpdaterStatus, AppError>(__TAURI_INVOKE("app_update_status")),
	updateGeoAssets: () => typedError<ResourceUpdateFile[], AppError>(__TAURI_INVOKE("update_geo_assets")),
	updateSrsAssets: () => typedError<ResourceUpdateFile[], AppError>(__TAURI_INVOKE("update_srs_assets")),
	/**
	 *  Re-install a core binary from the packaged seed (`{resource_dir}/core-seeds/<core>/`)
	 *  into `bin/<core>/`. This is the recovery action behind the missing-core prompt: the
	 *  startup seed copy already runs automatically, but this lets the UI re-run it on demand
	 *  when the binary is absent (e.g. cleared bin dir, antivirus removal, or a skipped first run).
	 */
	installCoreSeed: (coreType: CoreType) => typedError<CoreSeedInstallResult, AppError>(__TAURI_INVOKE("install_core_seed", { coreType })),
	/**
	 *  macOS overlays native traffic lights on the webview; Windows renders caption
	 *  buttons in its borderless window. Linux and the web fallback use `none`.
	 */
	getWindowChromeConfig: () => typedError<WindowChromeConfig, AppError>(__TAURI_INVOKE("get_window_chrome_config")),
	/**
	 *  Tint the Windows Acrylic blur material to match the in-app light/dark theme.
	 *  The frontend drives its own (non-system) theme, so this command sets the tint
	 *  explicitly per mode to keep the native material's base color aligned with the
	 *  UI. Acrylic has a single variant; light and dark differ only by `color`.
	 * 
	 *  Non-Windows platforms are a no-op: window effects are an OS capability, and
	 *  macOS / Linux / web fall back to the flat CSS neutral-gray veil.
	 */
	setWindowAcrylic: (dark: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_window_acrylic", { dark })),
};

/** Events */
export const events = {
	appEvent: makeEvent<AppEvent>("app-event"),
	invalidateEvent: makeEvent<InvalidateEvent>("invalidate-event"),
	transientStreamEvent: makeEvent<TransientStreamEvent>("transient-stream-event"),
};

/* Types */
/**
 *  One failed IPC command.
 * 
 *  The three parts answer three different questions and nothing else may be
 *  inferred from any of them:
 * 
 *  - `kind` is **what the frontend branches on**. Every discrimination the UI
 *    performs has to be expressible here; the previous 23-arm union carried a
 *    string in 21 of its arms, which is why elevation retry was triggered by
 *    substring-matching the word "authorization" in `message`.
 *  - `subsystem` says which part of the app failed. It is for grouping, logging
 *    and copy ("Profiles: …"), never for control flow — the same `kind` means
 *    the same thing whichever subsystem raised it.
 *  - `message` is an English diagnostic. Show it, log it, that is all. It is
 *    never parsed, and rewording it must never change behavior.
 */
export type AppError = {
	kind: AppErrorKind,
	subsystem: AppErrorSubsystem,
	message: string,
};

/**  The kind of row a [`AppErrorKind::NotFound`] refers to. */
export type AppErrorEntity = "profile" | "routing" | "routingRule" | "subscription" | 
/**  The core-info table has no entry for the requested core type. */
"coreInfo";

/**
 *  What went wrong, in the terms the frontend acts on.
 * 
 *  Serialized internally tagged, so a failure reads `{ type: "elevationRequired" }`
 *  and TypeScript narrows the payload from the tag alone.
 */
export type AppErrorKind = 
/**
 *  Submitted values were rejected. `issues` name the offending fields and
 *  carry a [`ValidationCode`](crate::ValidationCode) the frontend
 *  translates, which is the pairing the DNS pane already renders.
 */
{ type: "validation"; issues: ValidationIssue[] } | 
/**
 *  A referenced row does not exist. The UI's remedy is to refresh the list
 *  it selected from, so the entity matters more than the id.
 */
{ type: "notFound"; entity: AppErrorEntity; id: string | null } | 
/**
 *  The action needs one-time system authorization. This is the *only*
 *  signal that may open a privilege prompt: TUN and the elevated
 *  supervisor spawn both raise it, and no message text can substitute.
 */
{ type: "elevationRequired" } | 
/**  The core executable is not installed where the app looks for it. */
{ type: "missingCore"; coreType: CoreType; searchDir: string; candidates: string[]; downloadUrl: string } | 
/**  A download, subscription fetch or Clash API call failed. Retryable. */
{ type: "network" } | 
/**  A filesystem or child-process operation failed. */
{ type: "io" } | 
/**
 *  Persistence failed. `code` separates the cases that have different
 *  remedies, and `reset_command` carries the manual recovery line when the
 *  database itself reported one.
 */
{ type: "database"; code: DatabaseErrorCode; resetCommand: string | null } | 
/**
 *  Anything with no better classification: a poisoned lock, a join error,
 *  an invariant the app itself broke.
 */
{ type: "internal" };

/**  Which part of the app produced a failure. Diagnostic grouping only. */
export type AppErrorSubsystem = 
/**  The shell itself: window chrome, event emission, background tasks. */
"app" | "autostart" | "certificate" | 
/**  Reading or writing the persisted application configuration. */
"config" | "dns" | "export" | "profile" | "proxyRuntime" | "qr" | "routing" | 
/**  Core lifecycle: config generation, supervisor, connect/disconnect. */
"runtime" | "speedtest" | "subscription" | "sysProxy" | "tun" | "update";

export type AppEvent = { kind: "notice"; payload: AppNotice } | { kind: "selectTab"; payload: ShellTabTarget };

/**
 *  One toast.
 * 
 *  `code` replaced the prose `title` the shell used to spell out at each of its
 *  call sites: those titles were English literals that `pnpm check:i18n` could
 *  not see, and the toast is the most visible text the backend produces.
 *  `detail` stays an untranslated diagnostic — the error behind the notice.
 */
export type AppNotice = {
	level: AppNoticeLevel,
	code: NoticeCode,
	detail: string | null,
};

export type AppNoticeLevel = "info" | "warning" | "error";

export type AppSettingsV1 = {
	schemaVersion: number,
	appearance: AppearanceSettings,
	behavior: BehaviorSettings,
	core: CoreSettings,
	network: NetworkSettings,
	routing: RoutingSettings,
	dns: DnsSettings,
	speedTest: SpeedtestSettings,
	multiplexing: MultiplexingSettings,
	grpc: GrpcSettings,
	hysteria: HysteriaSettings,
	proxy: ProxySettings,
};

export type AppUpdaterState = "ready" | "unconfigured" | "unsupported" | "error";

export type AppUpdaterStatus = {
	currentVersion: string,
	state: AppUpdaterState,
	message: string | null,
};

export type AppearanceSettings = {
	language: string,
	theme: ThemeMode,
};

export type AutostartPlatform = "windows" | "linux" | "macos" | "other";

export type AutostartStatus = {
	enabled: boolean,
	platform: AutostartPlatform,
	artifactKind: string | null,
	artifactPath: string | null,
	artifactName: string | null,
};

export type BehaviorSettings = {
	autostart: boolean,
	statistics: boolean,
	realtimeSpeed: boolean,
};

export type CertificateFetchRequest = {
	address: string,
	port: number,
	serverName: string | null,
	allowInsecure: boolean,
	includeChain: boolean,
};

export type CertificateFetchResult = {
	pem: string,
	sha256: string[],
	chainCount: number,
	warning: string | null,
};

/**
 *  Top-level connection mode. A derived view over the two
 *  persisted primitives (system proxy type + TUN flag), never stored itself.
 */
export type ConnectionMode = 
/**  Local inbound for system proxy use (optionally PAC); macOS setup is manual. */
"systemProxy" | 
/**  TUN mode; all traffic is routed through the virtual interface. */
"vpn";

export type ConnectionModeStatus = {
	mode: ConnectionMode,
	pacEnabled: boolean,
	pacAvailable: boolean,
	vpnAvailable: boolean,
	/**
	 *  sing-box process rules only match traffic entering through TUN, so
	 *  per-app rules are effective only while `mode` is `Vpn`.
	 */
	processRulesEffective: boolean,
};

/**
 *  Which core operation a log line is about.
 * 
 *  The flow used to interpolate an English fragment ("connect", "Routing
 *  changed") into its log sentences; the fragment is a code now so the whole
 *  sentence can be assembled in the reader's language.
 */
export type CoreFlowReason = "connect" | "restart" | "disconnect" | "routingChanged" | "dnsChanged" | "tunChanged" | "connectionModeChanged" | "settingsSaved";

export type CoreSeedInstallResult = {
	coreType: CoreType,
	status: CoreSeedInstallStatus,
	installedFiles: string[],
};

export type CoreSeedInstallStatus = "installed" | "alreadyInstalled" | "seedMissing";

export type CoreSettings = {
	logEnabled: boolean,
	logLevel: string,
	muxEnabled: boolean,
	defaultAllowInsecure: boolean,
	defaultFingerprint: string,
	defaultUserAgent: string,
	sendThrough: string | null,
	bindInterface: string | null,
	fragmentEnabled: boolean,
	cacheFileEnabled: boolean,
};

/**
 *  What the core process is doing right now.
 * 
 *  The single vocabulary for the runtime's connection state: the status command
 *  returns it inside [`crate::RuntimeStatusResponse`] and the transient
 *  `coreState` stream carries the very same struct, so there is nothing to
 *  translate between a response and an event. `Connecting`/`Disconnecting` are
 *  transitions only the event stream ever reports — a status read observes a
 *  settled supervisor and answers `Connected`, `Disconnected`, or `CleanupPending`.
 */
export type CoreState = "cleanupPending" | "disconnected" | "connecting" | "connected" | "disconnecting";

export type CoreType = "singBox";

/**  Why a persistence call failed, at the granularity the UI can act on. */
export type DatabaseErrorCode = 
/**
 *  The stored schema is not the one this build expects; the database has to
 *  be reset manually before anything else will work.
 */
"schemaUnsupported" | 
/**  A stored payload could not be decoded — one bad row, or a damaged file. */
"corrupt" | 
/**  Another writer holds the database. Retrying is the remedy. */
"locked" | 
/**  The database file could not be read or written. */
"io" | "other";

export type DnsSettings = {
	addCommonHosts: boolean | null,
	fakeIp: boolean | null,
	globalFakeIp: boolean | null,
	blockBindingQuery: boolean | null,
	direct: string | null,
	remote: string | null,
	bootstrap: string | null,
	directStrategy: string | null,
	proxyStrategy: string | null,
	hosts: string | null,
	directExpectedIps: string | null,
};

export type ExportProfilesFormat = "shareLinks" | "shareLinksBase64" | "voyaBundle";

export type ExportProfilesRequest = {
	indexIds: string[],
	format: ExportProfilesFormat,
};

export type ExportProfilesResult = {
	text: string,
	count: number,
	format: ExportProfilesFormat,
};

export type GrpcSettings = {
	idleTimeoutSeconds: number | null,
	healthCheckTimeoutSeconds: number | null,
	permitWithoutStream: boolean | null,
};

export type HysteriaSettings = {
	uploadMbps: number,
	downloadMbps: number,
	hopIntervalSeconds: number,
};

export type ImportProfilesResult = {
	imported: number,
	updated: number,
	skipped: number,
	parsed: number,
	filtered: number,
	deduped: number,
	failed: number,
	removedExisting: number,
	removedDuplicates: number,
	discardedNodeOverrides: number,
	subscriptionId: string | null,
	importedProfileIds: string[],
	updatedProfileIds: string[],
	messages: string[],
};

export type InboundSettings = {
	localPort: number,
	protocol: string,
	sniffingEnabled: boolean,
	lanConnectionsAllowed: boolean,
	separateLanPort: boolean,
	username: string,
	password: string,
	secondaryPortEnabled: boolean,
};

export type InvalidateEvent = {
	keys: QueryInvalidation[],
};

/**
 *  One frontend query cache, named on the wire.
 * 
 *  Replaces the free-string key list the shell used to build by hand. The
 *  variants are generated into `apps/desktop/src/ipc/bindings.ts`, and
 *  `apps/desktop/src/ipc/query-keys.ts` maps each one onto the `queryKey`
 *  array its `useQuery` really uses, so a variant added here fails the frontend
 *  typecheck until the map is extended. Only caches an emitter can actually
 *  invalidate belong here; a query whose data no command mutates
 *  (`process-candidates`, `profile-share-qr`) deliberately has no variant.
 * 
 *  Internally tagged rather than a bare string so a future scope that has to
 *  name one row (`{ kind: "profile", id }`) is an additive change instead of a
 *  rewrite of the wire shape.
 */
export type InvalidationScope = 
/**  `["profiles"]` — the profile list, every filter slice of it. */
{ kind: "profiles" } | 
/**  `["subscriptions"]` */
{ kind: "subscriptions" } | 
/**  `["subscription-metadata"]` */
{ kind: "subscriptionMetadata" } | 
/**  `["routings"]` */
{ kind: "routings" } | 
/**  `["dns"]` */
{ kind: "dns" } | 
/**  `["app-settings"]` — the whole settings bundle projected from `AppConfig`. */
{ kind: "appSettings" } | 
/**  `["ui-preferences"]` — the appearance slice the shell reads on its own. */
{ kind: "uiPreferences" } | 
/**  `["connection-mode"]` — TUN / system-proxy mode and its availability. */
{ kind: "connectionMode" } | 
/**  `["proxy-connections"]` */
{ kind: "proxyConnections" };

/**
 *  A log line the **app** wrote, named by code.
 * 
 *  Only lines the app authors are in here. Everything the core process prints
 *  travels as [`LogLineBody::Core`] and is shown byte for byte.
 */
export type LogCode = { code: "connecting" } | { code: "connected" } | { code: "restarting" } | { code: "restarted" } | { code: "disconnecting" } | { code: "disconnected" } | { code: "restartingAfterChange"; reason: CoreFlowReason } | { code: "restartedAfterChange"; reason: CoreFlowReason } | 
/**  The core exited and was restarted straight away. */
{ code: "coreExitRestarted"; attempt: number } | 
/**  The core exited and a restart is scheduled. */
{ code: "coreExitRetryScheduled"; attempt: number; delayMs: number } | 
/**  The core exited too often and the app stopped restarting it. */
{ code: "coreExitGaveUp" } | { code: "nativeTunExited" } | 
/**
 *  An operation failed before the supervisor was touched, so the core that
 *  was already running is still serving traffic.
 */
{ code: "previousCoreStillRunning"; reason: CoreFlowReason } | 
/**  The supervisor could not say what state it ended up in. */
{ code: "runtimeStatusRefreshFailed"; reason: CoreFlowReason } | 
/**  A core operation failed; `detail` carries the error. */
{ code: "coreOperationFailed"; reason: CoreFlowReason } | 
/**  A change was committed and its follow-up work failed. */
{ code: "postCommitFailed" } | { code: "speedtestCancellationRequested" } | { code: "subscriptionAutoUpdateFailed"; remarks: string } | { code: "subscriptionAutoUpdateFinished"; remarks: string; imported: number };

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

/**  One line in the Logs panel. */
export type LogLineBody = 
/**
 *  Output of the core process, passed through unchanged. It is the core's
 *  own text in the core's own wording, so translating it is not ours to do.
 */
{ source: "core"; line: string } | 
/**
 *  A `tracing` event from the app's own instrumentation, forwarded to the
 *  panel so a failure is visible without opening the file log. Structured
 *  developer diagnostics with a module target — deliberately untranslated,
 *  for the same reason a stack trace is.
 */
{ source: "diagnostic"; line: string } | 
/**
 *  A line the app wrote *for the user*. `detail` is an untranslated
 *  technical diagnostic (an error's `Display`), shown after the translated
 *  sentence.
 */
{ source: "app"; code: LogCode; detail: string | null };

/**
 *  One line for the Logs panel.
 * 
 *  `body` says who wrote it: the core process (raw passthrough) or the app
 *  itself (a [`crate::LogCode`] the frontend translates). It used to be a
 *  single `line: String`, which meant every sentence the app logged reached
 *  the panel in English whatever the interface language was.
 */
export type LogLineEvent = {
	id: number,
	level: LogLevel,
	body: LogLineBody,
};

export type MoveAction = "top" | "up" | "down" | "bottom" | "position";

export type MultiplexingSettings = {
	protocol: string,
	maxConnections: number,
	padding: boolean | null,
};

export type NetworkSettings = {
	tun: TunSettings,
	systemProxy: SystemProxySettings,
	inbounds: InboundSettings[],
};

/**
 *  What the backend is telling the user about, as a code the frontend
 *  translates.
 * 
 *  One variant per distinct message rather than a message assembled from
 *  parts: a notice is a whole sentence in every locale, and languages do not
 *  agree on how to build one out of a subject and a verb.
 */
export type NoticeCode = { code: "profileRefreshFailed" } | { code: "subscriptionRefreshFailed" } | { code: "routingRefreshFailed" } | { code: "dnsRefreshFailed" } | { code: "proxyViewRefreshFailed" } | { code: "connectionModeRefreshFailed" } | { code: "settingsRefreshFailed" } | { code: "routingSavedRestartFailed" } | { code: "routingDeletedRestartFailed" } | { code: "routingSelectedRestartFailed" } | { code: "routingRuleSavedRestartFailed" } | { code: "routingRulesDeletedRestartFailed" } | { code: "routingRuleMovedRestartFailed" } | { code: "dnsSavedRestartFailed" } | { code: "tunSavedRestartFailed" } | { code: "connectionModeSavedRestartFailed" } | { code: "settingsSavedRuntimeUpdateFailed" } | { code: "proxyModeSavedRuntimeUpdateFailed" } | { code: "settingsSavedSystemProxyUpdateFailed" } | { code: "systemProxyStatusRefreshFailed" } | { code: "tunStatusRefreshFailed" } | { code: "trayRefreshFailed" } | { code: "coreStopped" } | { code: "nativeTunStopped" } | { code: "coreStartedSystemProxyFailed" } | { code: "systemProxyRestoreFailed" } | { code: "subscriptionAutoUpdateFailed"; remarks: string };

/**
 *  A running process or installed application offered by the per-app proxy
 *  picker; `process_name` is the executable basename sing-box matches on.
 */
export type ProcessCandidate = {
	displayName: string,
	processName: string,
	executablePath: string | null,
	source: ProcessCandidateSource,
};

export type ProcessCandidateSource = "runningProcess" | "installedApplication";

export type Profile = {
	id: string,
	subscriptionId: string | null,
	displayLog: boolean,
	remarks: string,
	protocol: ProfileProtocol,
	transport: ProfileTransport | null,
	tls: TlsSettings | null,
};

export type ProfileKind = "vmess" | "shadowsocks" | "socks" | "vless" | "trojan" | "hysteria2" | "tuic" | "wireGuard" | "http" | "anytls" | "naive";

export type ProfileListEntry = {
	profile: Profile,
	metrics: ProfileMetrics,
	traffic: ProfileTraffic,
	isActive: boolean,
};

/**
 *  A profile listing plus what is missing from it.
 * 
 *  `undecodableProfiles` counts stored profiles this build could not read —
 *  most often ones written by a newer build. Persistence skips those rows
 *  rather than failing the whole listing, so one unreadable server cannot take
 *  away the user's ability to see, connect to or delete the others.
 * 
 *  The count travels *with* the rows instead of arriving as a notice on the
 *  side: the listing is re-fetched on every profile query, so an event would
 *  repeat without end, while a field on the response lets the screen state the
 *  shortfall once, quietly, beside the list it belongs to.
 */
export type ProfileListing = {
	entries: ProfileListEntry[],
	undecodableProfiles: number,
};

export type ProfileMetrics = {
	delayMs: number,
	sort: number,
	/**
	 *  The last probe's outcome, decoded from the persisted `profile_ex`
	 *  column. `None` means the profile has never been tested.
	 */
	outcome: SpeedtestOutcome | null,
	ipInfo: string | null,
	countryCode: string | null,
};

export type ProfileProtocol = { kind: "vmess"; server: ServerEndpoint; uuid: string; cipher: string | null } | { kind: "shadowsocks"; server: ServerEndpoint; password: string; method: string; udpOverTcp: boolean } | { kind: "socks"; server: ServerEndpoint; username: string; password: string } | { kind: "vless"; server: ServerEndpoint; uuid: string; flow: string | null; encryption: string | null } | { kind: "trojan"; server: ServerEndpoint; password: string } | { kind: "hysteria2"; server: ServerEndpoint; password: string; portHops: string | null; obfuscationPassword: string | null } | { kind: "tuic"; server: ServerEndpoint; uuid: string; password: string; congestionControl: string | null } | { kind: "wireGuard"; server: ServerEndpoint; privateKey: string; peerPublicKey: string | null; presharedKey: string | null; interfaceAddress: string | null; allowedIps: string | null; reserved: string | null; mtu: number | null } | { kind: "http"; server: ServerEndpoint; username: string; password: string } | { kind: "anytls"; server: ServerEndpoint; password: string } | { kind: "naive"; server: ServerEndpoint; username: string; password: string; quic: boolean; congestionControl: string | null; insecureConcurrency: number | null; udpOverTcp: boolean };

export type ProfileTraffic = {
	totalUpload: number | null,
	totalDownload: number | null,
	todayUpload: number | null,
	todayDownload: number | null,
	date: number | null,
};

export type ProfileTransport = { kind: "tcp"; header: string | null; host: string | null; path: string | null } | { kind: "kcp"; header: string | null; seed: string | null; mtu: number | null } | { kind: "websocket"; host: string | null; path: string | null } | { kind: "httpUpgrade"; host: string | null; path: string | null } | { kind: "xhttp"; host: string | null; path: string | null; mode: string | null; extra: string | null } | { kind: "http2"; host: string | null; path: string | null } | { kind: "grpc"; authority: string | null; serviceName: string | null; mode: string | null } | { kind: "quic"; host: string | null; path: string | null };

export type ProxyConnectionItem = {
	id: string | null,
	network: string | null,
	connectionType: string | null,
	host: string,
	source: string,
	destination: string,
	upload: number | null,
	download: number | null,
	start: string,
	chains: string[],
	rule: string | null,
	rulePayload: string | null,
	process: string | null,
	processPath: string | null,
};

export type ProxyConnectionsSnapshot = {
	downloadTotal: number | null,
	uploadTotal: number | null,
	connections: ProxyConnectionItem[],
};

export type ProxyMonitorState = "running" | "stopped" | "failed";

export type ProxyMonitorStatus = {
	state: ProxyMonitorState,
	running: boolean,
	stale: boolean,
	message: string | null,
};

export type ProxySettings = {
	/**
	 *  The persisted Clash traffic mode. Typed for the same reason as
	 *  [`SystemProxySettings::mode`]: `rename_all = "camelCase"` emits the very
	 *  canonical strings this field stores (`rule`, `global`, `unchanged`).
	 */
	trafficMode: TrafficMode,
};

export type QrCodeImage = {
	mimeType: string,
	svg: string,
};

export type QrScanFailureReason = "permissionDenied" | "unsupported" | "captureFailed" | "timeout" | "busy" | 
/**  The clipboard held no image. Only a clipboard scan reports it. */
"noImage";

export type QrScanResult = {
	status: QrScanStatus,
	texts: string[],
	source: string,
	message: string | null,
	/**  Also set on a successful scan when some displays could not be captured. */
	failureReason: QrScanFailureReason | null,
};

export type QrScanStatus = "found" | "notFound" | "unavailable";

/**
 *  One invalidated cache plus the change that invalidated it.
 * 
 *  `reason` stays a free string on purpose: it is diagnostic (it names the
 *  command, and shows up in logs), never part of the contract the frontend
 *  switches on.
 */
export type QueryInvalidation = {
	scope: InvalidationScope,
	reason: string,
};

export type ResourceUpdateFile = {
	name: string,
	bytes: number,
	usedProxy: boolean,
};

export type Routing = Routing_Serialize | Routing_Deserialize;

export type RoutingRule = {
	id: string,
	kind: string | null,
	port: string | null,
	network: string | null,
	inboundTags: string[] | null,
	outbound: string | null,
	ip: string[] | null,
	domain: string[] | null,
	protocol: string[] | null,
	process: string[] | null,
	enabled: boolean,
	remarks: string | null,
	scope: RoutingRuleScope | null,
};

export type RoutingRuleScope = "all" | "routing" | "dns";

export type RoutingSettings = {
	domainStrategy: string,
	singboxDomainStrategy: string,
};

export type Routing_Deserialize = {
	id: string,
	remarks: string,
	sourceUrl: string,
	rules: RoutingRule[],
	enabled: boolean,
	locked: boolean,
	icon: string,
	singboxRulesetPath: string,
	domainStrategy: string,
	singboxDomainStrategy: string,
	sort: number,
};

export type Routing_Serialize = {
	id: string,
	remarks: string,
	sourceUrl: string,
	rules: RoutingRule[],
	enabled: boolean,
	locked: boolean,
	icon: string,
	singboxRulesetPath: string,
	domainStrategy: string,
	singboxDomainStrategy: string,
	sort: number,
	isActive: boolean,
};

/**
 *  What the runtime is doing, as both an answer and an announcement.
 * 
 *  The four runtime commands return this, and `TransientStreamEvent::CoreState`
 *  carries exactly the same struct, so the frontend stores whichever arrives
 *  first without reshaping it. It used to be two types — this one plus an
 *  identically-shaped `CoreStateEvent` — which cost three converters in the
 *  shell and three more on the frontend to move one fact between them.
 * 
 *  `Deserialize` exists because it travels as an event payload, not because
 *  anything sends one to the backend.
 */
export type RuntimeStatusResponse = {
	/**  Milliseconds since this core connected; absent outside a confirmed connection. */
	connectedDurationMs: number | null,
	state: CoreState,
	/**
	 *  The confirmed running tunnel, independent of the saved connection mode.
	 *  Absent during transitions, pending cleanup, and local-proxy operation.
	 */
	activeTunBackend: TunBackend | null,
	activeProfileId: string | null,
	mainPid: number | null,
	prePid: number | null,
	runningCoreType: CoreType | null,
};

export type ServerEndpoint = {
	address: string,
	port: number,
};

export type ServerStatItem = {
	indexId: string,
	totalUp: number | null,
	totalDown: number | null,
	todayUp: number | null,
	todayDown: number | null,
	dateNow: number | null,
};

export type SettingsApplyAction = "none" | "reconnect" | "reapplyProxy";

export type SettingsApplyStatus = {
	action: SettingsApplyAction,
	connected: boolean,
};

export type ShellTabTarget = "profiles" | "proxyConnections" | "logs";

/**
 *  How a probe ended, as a code rather than a sentence.
 * 
 *  Persisted in `profile_ex.message` using the same camelCase codes as IPC.
 *  Unrecognised stored values become `Unknown` without hiding the profile.
 */
export type SpeedtestOutcome = 
/**  Selected and queued behind another probe. */
"waiting" | 
/**  The probe is running right now. */
"testing" | 
/**  The probe finished; `delay` carries the measurement. */
"completed" | "timedOut" | "proxyConnectFailed" | "proxyConnectionRefused" | "proxyConnectionClosed" | "cancelled" | 
/**  The run ended before this profile's turn came up. */
"skipped" | 
/**  The profile's own configuration is invalid, so nothing was probed. */
"invalidProfile" | 
/**  The test core could not be started, or its config could not be written. */
"coreUnavailable" | 
/**  No free local port was available for the probe. */
"noAvailablePort" | 
/**  A failure with no more specific code. */
"failed" | 
/**  A stored value this build cannot classify, without dropping the row. */
"unknown";

export type SpeedtestRequest = {
	target: SpeedtestTarget,
};

/**
 *  One profile's probe result.
 * 
 *  `detail` is an untranslated technical line shown under the outcome. It is
 *  never persisted and never carries a local filesystem path: the failure
 *  classification used to fall through to the error's own `Display`, which for
 *  a config-write failure printed the app-data directory into a column the
 *  profile table renders.
 */
export type SpeedtestResult = {
	indexId: string,
	delay: number | null,
	outcome: SpeedtestOutcome,
	detail: string | null,
	ipInfo: string | null,
	countryCode: string | null,
};

export type SpeedtestRunResult = {
	cancelled: boolean,
	selectedCount: number,
	completedCount: number,
	results: SpeedtestResult[],
};

export type SpeedtestSettings = {
	timeoutSeconds: number,
	latencyUrl: string,
	ipLookupUrl: string,
	pageSize: number | null,
	delayIntervalSeconds: number | null,
};

export type SpeedtestStatus = {
	running: boolean,
};

export type SpeedtestTarget = { scope: "all" } | { scope: "profiles"; profileIds: string[] };

export type StatisticsSnapshot = {
	activeProfileId: string | null,
	proxyUploadBytesPerSecond: number | null,
	proxyDownloadBytesPerSecond: number | null,
	directUploadBytesPerSecond: number | null,
	directDownloadBytesPerSecond: number | null,
	uploadBytesPerSecond: number | null,
	downloadBytesPerSecond: number | null,
	serverStat: ServerStatItem | null,
};

export type Subscription = {
	id: string,
	remarks: string,
	url: string,
	additionalUrl: string,
	enabled: boolean,
	userAgent: string,
	sort: number,
	filter: string | null,
	converterTarget: string | null,
	autoUpdateIntervalMinutes: number | null,
};

/**
 *  Usage metadata reported by the subscription server on the latest successful
 *  fetch (`subscription-userinfo` and `profile-title` response headers).
 */
export type SubscriptionMetadata = {
	subscriptionId: string,
	uploadBytes: number | null,
	downloadBytes: number | null,
	totalBytes: number | null,
	expireAt: number | null,
	lastUpdateAt: number | null,
	profileTitle: string | null,
};

export type SubscriptionUpdateResult = {
	updated: number,
	skipped: number,
	imported: number,
	removedExisting: number,
	messages: string[],
};

export type SystemProxyManagement = "automatic" | "manual" | "unsupported";

export type SystemProxyObservation = "unknown" | "clear" | "localProxy" | "otherProxy";

export type SystemProxySettings = {
	/**
	 *  The persisted OS-proxy mode. Typed rather than a `String`: the enum's
	 *  `rename_all = "camelCase"` emits exactly the four values this field has
	 *  always stored (`forcedClear`, `forcedChange`, `unchanged`, `pac`), so the
	 *  stored payload is unchanged and `voya-db` pins that with a value test.
	 */
	mode: SystemProxyType,
	exceptions: string,
	bypassLocal: boolean,
	advancedProtocol: string,
	customPacPath: string | null,
	customScriptPath: string | null,
};

/**
 *  The OS proxy state, as both an answer and an announcement.
 * 
 *  `TransientStreamEvent::SysProxyChanged` carries this struct; the narrower
 *  `SysProxyChanged` it replaced duplicated four of these fields and re-declared
 *  `SystemProxyType` under a second name.
 */
export type SystemProxyStatusResponse = {
	management: SystemProxyManagement,
	/**  Read-only OS observation. Unknown must never be presented as restored. */
	observation: SystemProxyObservation,
	manualCleanupRequired: boolean,
	requestedMode: SystemProxyType,
	/**  The app's applied policy; always Unchanged on manual platforms. */
	effectiveMode: SystemProxyType,
	pacAvailable: boolean,
	proxy: string | null,
	exceptions: string,
	pacUrl: string | null,
};

export type SystemProxyType = "forcedClear" | "forcedChange" | "unchanged" | "pac";

export type ThemeMode = "system" | "light" | "dark";

export type TitleBarLayout = "macos" | "windows" | "none";

export type TlsMode = "tls" | "reality";

export type TlsSettings = {
	mode: TlsMode,
	serverName: string | null,
	alpn: string[],
	realityPublicKey: string | null,
	realityShortId: string | null,
	realitySpiderX: string | null,
	mldsa65Verify: string | null,
	certificatePem: string | null,
	certificateSha256: string[],
	echConfig: string[],
	finalMask: string | null,
};

export type TrafficMode = "rule" | "global" | "unchanged";

export type TrafficModeResponse = {
	mode: TrafficMode,
};

/**
 *  Live state that is not a query cache.
 * 
 *  The three status variants carry the very structs their commands return, so
 *  the frontend stores an event payload and a command result interchangeably.
 *  They used to be narrower parallel DTOs, which cost a converter in the shell
 *  and another on the frontend for each one.
 */
export type TransientStreamEvent = { kind: "logLine"; payload: LogLineEvent } | { kind: "coreState"; payload: RuntimeStatusResponse } | { kind: "statistics"; payload: StatisticsSnapshot } | { kind: "sysProxyChanged"; payload: SystemProxyStatusResponse } | { kind: "tunChanged"; payload: TunStatus } | { kind: "proxyMonitorStatus"; payload: ProxyMonitorStatus } | { kind: "proxyConnections"; payload: ProxyConnectionsSnapshot } | { kind: "speedtestResult"; payload: SpeedtestResult };

export type TunBackend = "process" | "macosPacketTunnel" | "windowsService" | "unsupported";

export type TunPlatform = "windows" | "linux" | "macos" | "other";

export type TunPreflight = {
	platform: TunPlatform,
	state: TunPreflightState,
	notes: string[],
	routeRestoreNote: string,
	windowsCleanupDevices: string[],
};

export type TunPreflightState = "ready" | "needsElevation" | "manualCheck" | "unsupported";

export type TunProviderDiagnostics = {
	backend: TunBackend,
	containerPath: string | null,
	statusPath: string | null,
	logPath: string | null,
	packagingMode: string | null,
	expectedProviderPath: string | null,
	systemExtensionState: string | null,
	registrationPaths: string[],
	statusState: string | null,
	lastError: string | null,
	providerBundlePath: string | null,
	breadcrumbs: string[],
	providerLogTail: string[],
	hostLogTail: string[],
	message: string | null,
};

export type TunProviderState = "notApplicable" | "missingComponent" | "permissionRequired" | "stopped" | "starting" | "running" | "error";

export type TunSettings = {
	enabled: boolean,
	autoRoute: boolean,
	strictRoute: boolean,
	stack: string,
	mtu: number,
	ipv6Enabled: boolean,
	icmpRouting: string,
};

export type TunStatus = {
	enabled: boolean,
	backend: TunBackend,
	providerState: TunProviderState,
	allowEnableTun: boolean,
	requiresElevation: boolean,
	elevationGranted: boolean,
	needsVpnPermission: boolean,
	needsServiceInstall: boolean,
	nativeComponentReady: boolean,
	lastProviderError: string | null,
	providerPathMismatch: boolean,
	resolvedProviderPath: string | null,
	expectedProviderPath: string | null,
	restoreOnDisconnect: boolean,
	preflight: TunPreflight,
};

/**
 *  Why a submitted or generated value was rejected.
 * 
 *  Produced by `voya_core`'s node/group validators, by the DNS pane's checks
 *  and by settings validation. [`ValidationCode::Untranslated`] is the
 *  deliberate escape hatch for the managers that have no code yet: it is
 *  greppable, it shows the English diagnostic verbatim, and adding a code for
 *  one is a purely additive change.
 */
export type ValidationCode = { code: "subscriptionReadOnly"; subscriptionId: string } | { code: "invalidAddress" } | { code: "invalidPort" } | { code: "invalidPassword" } | { code: "invalidFlow" } | { code: "invalidShadowsocksMethod" } | { code: "invalidRealityPublicKey" } | { code: "invalidFinalMask" } | { code: "unsupportedNetwork"; network: string } | { code: "unsupportedProtocol"; protocol: string } | { code: "unsupportedProtocolNetwork"; protocol: string; network: string } | { code: "unsupportedShadowsocksNetwork"; network: string } | { code: "routingRuleWithoutOutbound"; rule: string } | { code: "routingRuleOutboundNotFound"; rule: string; outbound: string } | { code: "dnsAddressEmpty" } | { code: "dnsAddressPort"; port: string } | { code: "dnsHostsLine"; line: number } | { code: "dnsExpectedIps" } | { code: "textRequired" } | { code: "textTooLong" } | { code: "textControlCharacters" } | { code: "tooManyItems" } | { code: "unsupportedSettingsSchema"; found: number; expected: number } | { code: "tunMtuOutOfRange"; min: number; max: number } | { code: "negativeHysteriaBandwidth" } | { code: "hysteriaHopIntervalTooShort"; minimumSeconds: number } | 
/**
 *  A rejection this contract has no code for. The English `message` is the
 *  failing manager's own diagnostic and is rendered verbatim.
 */
{ code: "untranslated"; message: string };

/**
 *  One rejected value.
 * 
 *  `field` is a stable identifier, not a display label: the DNS pane keys its
 *  inputs by `direct`/`remote`/`bootstrap`/`hosts`, the settings surface by its
 *  contract path (`network.tun.mtu`), and the group builder by `children`.
 */
export type ValidationIssue = {
	field: string,
	code: ValidationCode,
	/**  Empty unless the validator descended into a group or a rule outbound. */
	scope: ValidationScope[],
};

/**
 *  Where a validation message was produced, when the validator had to walk
 *  into a group's children or a routing rule's outbound to find it.
 * 
 *  This replaces the `"group child A / B: "` prefixes the validators used to
 *  glue onto the front of a message, which made the message itself
 *  untranslatable. The frontend renders the breadcrumb from these entries and
 *  the translated message after it.
 */
export type ValidationScope = { kind: "routingRuleOutbound"; rule: string; outbound: string };

export type WindowChromeConfig = {
	titleBarLayout: TitleBarLayout,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

