// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	loadUiPreferences: () => typedError<AppearanceSettings, AppError>(__TAURI_INVOKE("load_ui_preferences")),
	loadAppSettings: () => typedError<AppSettingsV1, AppError>(__TAURI_INVOKE("load_app_settings")),
	saveAppSettings: (settings: AppSettingsV1) => typedError<AppSettingsV1, AppError>(__TAURI_INVOKE("save_app_settings", { settings })),
	generateQrCode: (content: string) => typedError<QrCodeImage, AppError>(__TAURI_INVOKE("generate_qr_code", { content })),
	scanScreenQr: () => typedError<QrScanResult, AppError>(__TAURI_INVOKE("scan_screen_qr")),
	fetchCertificate: (request: CertificateFetchRequest) => typedError<CertificateFetchResult, AppError>(__TAURI_INVOKE("fetch_certificate", { request })),
	calculateCertificateSha256: (pem: string) => typedError<string[], AppError>(__TAURI_INVOKE("calculate_certificate_sha256", { pem })),
	/**
	 *  Trigger the one-time native authorization dialog and, on success, install
	 *  the passwordless elevation launcher. No admin password is stored.
	 */
	tunRequestElevation: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("tun_request_elevation")),
	connectActiveProfile: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("connect_active_profile")),
	disconnectCore: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("disconnect_core")),
	restartCore: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("restart_core")),
	runtimeStatus: () => typedError<RuntimeStatusResponse, AppError>(__TAURI_INVOKE("runtime_status")),
	systemProxyStatus: () => typedError<SystemProxyStatusResponse, AppError>(__TAURI_INVOKE("system_proxy_status")),
	setSystemProxyMode: (mode: SysProxyType) => typedError<SystemProxyStatusResponse, AppError>(__TAURI_INVOKE("set_system_proxy_mode", { mode })),
	connectionModeStatus: () => typedError<ConnectionModeStatus, AppError>(__TAURI_INVOKE("connection_mode_status")),
	/**
	 *  Switches the app between the three Hiddify-style connection modes by
	 *  mutating the persisted system proxy + TUN primitives in one transaction.
	 *  Entering VPN runs the full TUN preflight; only a TUN flag change restarts
	 *  a connected core, while proxy-only/system-proxy switches re-apply the OS
	 *  proxy live.
	 */
	setConnectionMode: (mode: ConnectionMode, pacEnabled: boolean | null) => typedError<ConnectionModeStatus, AppError>(__TAURI_INVOKE("set_connection_mode", { mode, pacEnabled })),
	tunStatus: () => typedError<TunStatus, AppError>(__TAURI_INVOKE("tun_status")),
	tunProviderDiagnostics: () => typedError<TunProviderDiagnostics, AppError>(__TAURI_INVOKE("tun_provider_diagnostics")),
	setTunEnabled: (enabled: boolean) => typedError<TunStatus, AppError>(__TAURI_INVOKE("set_tun_enabled", { enabled })),
	loadDnsSettings: () => typedError<DnsSettings, AppError>(__TAURI_INVOKE("load_dns_settings")),
	saveDnsSettings: (settings: DnsSettings) => typedError<DnsSettings, AppError>(__TAURI_INVOKE("save_dns_settings", { settings })),
	listProfiles: (subscriptionId: string | null, filter: string | null) => typedError<ProfileListEntry[], AppError>(__TAURI_INVOKE("list_profiles", { subscriptionId, filter })),
	saveProfile: (profile: Profile) => typedError<ProfileListEntry, AppError>(__TAURI_INVOKE("save_profile", { profile })),
	deleteProfiles: (indexIds: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_profiles", { indexIds })),
	copyProfiles: (indexIds: string[]) => typedError<ProfileListEntry[], AppError>(__TAURI_INVOKE("copy_profiles", { indexIds })),
	exportProfileShareLinks: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_share_links", { indexIds })),
	exportProfileShareLinksBase64: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_share_links_base64", { indexIds })),
	exportProfileVoyaBundle: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_voya_bundle", { indexIds })),
	exportProfileClientConfig: (indexIds: string[]) => typedError<ExportProfilesResult, AppError>(__TAURI_INVOKE("export_profile_client_config", { indexIds })),
	setActiveProfile: (indexId: string) => typedError<ProfileListEntry, AppError>(__TAURI_INVOKE("set_active_profile", { indexId })),
	moveProfile: (subscriptionId: string | null, indexId: string, action: MoveAction, position: number | null) => typedError<ProfileListEntry[], AppError>(__TAURI_INVOKE("move_profile", { subscriptionId, indexId, action, position })),
	sortProfiles: (subscriptionId: string | null, sortKey: ProfileSortKey, ascending: boolean) => typedError<ProfileListEntry[], AppError>(__TAURI_INVOKE("sort_profiles", { subscriptionId, sortKey, ascending })),
	dedupeProfiles: (subscriptionId: string | null, keepOlder: boolean | null) => typedError<ProfileDedupeResult, AppError>(__TAURI_INVOKE("dedupe_profiles", { subscriptionId, keepOlder })),
	listGroupChildCandidates: (currentIndexId: string | null, filter: string | null) => typedError<GroupChildCandidate[], AppError>(__TAURI_INVOKE("list_group_child_candidates", { currentIndexId, filter })),
	previewGroupProfile: (profile: Profile) => typedError<GroupPreview, AppError>(__TAURI_INVOKE("preview_group_profile", { profile })),
	saveGroupProfile: (profile: Profile) => typedError<ProfileListEntry, AppError>(__TAURI_INVOKE("save_group_profile", { profile })),
	listSubscriptions: () => typedError<Subscription[], AppError>(__TAURI_INVOKE("list_subscriptions")),
	listSubscriptionMetadata: () => typedError<SubscriptionMetadata[], AppError>(__TAURI_INVOKE("list_subscription_metadata")),
	saveSubscription: (item: Subscription) => typedError<Subscription, AppError>(__TAURI_INVOKE("save_subscription", { item })),
	deleteSubscriptions: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_subscriptions", { ids })),
	importProfilesFromText: (text: string, subscriptionId: string | null) => typedError<ImportProfilesResult, AppError>(__TAURI_INVOKE("import_profiles_from_text", { text, subscriptionId })),
	updateSubscriptions: (subscriptionId: string | null, preferProxy: boolean, proxyUrl: string | null) => typedError<SubscriptionUpdateResult, AppError>(__TAURI_INVOKE("update_subscriptions", { subscriptionId, preferProxy, proxyUrl })),
	listRoutings: () => typedError<Routing_Serialize[], AppError>(__TAURI_INVOKE("list_routings")),
	saveRouting: (item: Routing_Deserialize) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("save_routing", { item })),
	deleteRoutings: (ids: string[]) => typedError<number, AppError>(__TAURI_INVOKE("delete_routings", { ids })),
	setActiveRouting: (id: string) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("set_active_routing", { id })),
	saveRoutingRule: (routingId: string, rule: RoutingRule) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("save_routing_rule", { routingId, rule })),
	deleteRoutingRules: (routingId: string, ruleIds: string[]) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("delete_routing_rules", { routingId, ruleIds })),
	moveRoutingRule: (routingId: string, ruleId: string, action: MoveAction, position: number | null) => typedError<Routing_Serialize, AppError>(__TAURI_INVOKE("move_routing_rule", { routingId, ruleId, action, position })),
	importConfigTemplate: (selection: ConfigTemplateSelection, preferProxy: boolean, proxyUrl: string | null) => typedError<ConfigTemplateImportResult, AppError>(__TAURI_INVOKE("import_config_template", { selection, preferProxy, proxyUrl })),
	/**
	 *  Enumerates running processes (and installed applications where the OS
	 *  makes that cheap) for the per-app proxy picker. Blocking OS enumeration
	 *  runs off the async runtime.
	 */
	listProcessCandidates: () => typedError<ProcessCandidate[], AppError>(__TAURI_INVOKE("list_process_candidates")),
	proxyListGroups: () => typedError<ProxyGroupsSnapshot, AppError>(__TAURI_INVOKE("proxy_list_groups")),
	proxyTestDelay: (nodeNames: string[]) => typedError<ProxyDelayTestResult[], AppError>(__TAURI_INVOKE("proxy_test_delay", { nodeNames })),
	proxySelectNode: (groupName: string, nodeName: string) => typedError<ProxyGroupsSnapshot, AppError>(__TAURI_INVOKE("proxy_select_node", { groupName, nodeName })),
	proxyListConnections: () => typedError<ProxyConnectionsSnapshot, AppError>(__TAURI_INVOKE("proxy_list_connections")),
	proxyCloseConnection: (connectionId: string | null) => typedError<ProxyConnectionsSnapshot, AppError>(__TAURI_INVOKE("proxy_close_connection", { connectionId })),
	proxySetTrafficMode: (mode: TrafficMode) => typedError<TrafficModeResponse, AppError>(__TAURI_INVOKE("proxy_set_traffic_mode", { mode })),
	proxyReloadConfig: (path: string | null) => typedError<null, AppError>(__TAURI_INVOKE("proxy_reload_config", { path })),
	proxyStartMonitor: () => typedError<ProxyMonitorStatus, AppError>(__TAURI_INVOKE("proxy_start_monitor")),
	proxyStopMonitor: () => typedError<ProxyMonitorStatus, AppError>(__TAURI_INVOKE("proxy_stop_monitor")),
	runSpeedtest: (request: SpeedTestRequest) => typedError<SpeedtestRunResult, AppError>(__TAURI_INVOKE("run_speedtest", { request })),
	cancelSpeedtest: () => typedError<SpeedtestStatus, AppError>(__TAURI_INVOKE("cancel_speedtest")),
	speedtestStatus: () => typedError<SpeedtestStatus, AppError>(__TAURI_INVOKE("speedtest_status")),
	appUpdateStatus: () => typedError<AppUpdaterStatus, AppError>(__TAURI_INVOKE("app_update_status")),
	updateGeoAssets: () => typedError<ResourceUpdateFile[], AppError>(__TAURI_INVOKE("update_geo_assets")),
	updateSrsAssets: () => typedError<ResourceUpdateFile[], AppError>(__TAURI_INVOKE("update_srs_assets")),
	/**
	 *  Re-install a core binary from the packaged seed (`{resource_dir}/core-seeds/<core>/`)
	 *  into `bin/<core>/`. This is the recovery action behind the missing-core prompt: the
	 *  startup seed copy already runs automatically, but this lets the UI re-run it on demand
	 *  when the binary is absent (e.g. cleared bin dir, antivirus removal, or a skipped first run).
	 */
	installCoreSeed: (coreType: CoreType) => typedError<CoreSeedInstallResult, AppError>(__TAURI_INVOKE("install_core_seed", { coreType })),
	/**
	 *  Report the window decoration this build should render. Only Windows gets the
	 *  custom borderless title bar; macOS and Linux keep their native frame, and the
	 *  web fallback (no Tauri runtime) resolves to `none` on the frontend.
	 */
	getWindowChromeConfig: () => typedError<WindowChromeConfig, AppError>(__TAURI_INVOKE("get_window_chrome_config")),
	/**
	 *  Tint the Windows Acrylic blur material to match the in-app light/dark theme.
	 *  The frontend drives its own (non-system) theme, so this command sets the tint
	 *  explicitly per mode to keep the native material's base color aligned with the
	 *  UI. Acrylic has a single variant; light and dark differ only by `color`.
	 * 
	 *  Non-Windows platforms are a no-op: window effects are an OS capability, and
	 *  macOS / Linux / web fall back to the flat CSS neutral-gray veil.
	 */
	setWindowAcrylic: (dark: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_window_acrylic", { dark })),
};

/** Events */
export const events = {
	appEvent: makeEvent<AppEvent>("app-event"),
	invalidateEvent: makeEvent<InvalidateEvent>("invalidate-event"),
	transientStreamEvent: makeEvent<TransientStreamEvent>("transient-stream-event"),
};

/* Types */
export type AppDnsSettings = {
	useSystemHosts: boolean | null,
	addCommonHosts: boolean | null,
	fakeIp: boolean | null,
	globalFakeIp: boolean | null,
	blockBindingQuery: boolean | null,
	direct: string | null,
	remote: string | null,
	bootstrap: string | null,
	directStrategy: string | null,
	proxyStrategy: string | null,
	serveStale: boolean | null,
	parallelQuery: boolean | null,
	hosts: string | null,
	directExpectedIps: string | null,
};

export type AppError = { kind: "eventEmit"; message: string } | { kind: "autostart"; message: string } | { kind: "configSave"; message: string } | { kind: "certificate"; message: string } | { kind: "proxyRuntime"; message: string } | { kind: "database"; message: string } | { kind: "dns"; message: DnsCommandError } | { kind: "group"; message: string } | { kind: "hotkey"; message: string } | { kind: "preset"; message: string } | { kind: "profile"; message: string } | { kind: "qr"; message: string } | { kind: "export"; message: string } | { kind: "missingCore"; message: MissingCoreError } | { kind: "runtime"; message: string } | { kind: "routing"; message: string } | { kind: "speedtest"; message: string } | { kind: "sudo"; message: string } | { kind: "subscription"; message: string } | { kind: "sysProxy"; message: string } | { kind: "state"; message: string } | { kind: "tun"; message: string } | { kind: "update"; message: string };

export type AppEvent = { kind: "notice"; payload: AppNotice } | { kind: "selectTab"; payload: ShellTabTarget };

export type AppNotice = {
	level: AppNoticeLevel,
	title: string,
	message: string | null,
};

export type AppNoticeLevel = "info" | "warning" | "error";

export type AppSettingsV1 = {
	schemaVersion: number,
	appearance: AppearanceSettings,
	behavior: BehaviorSettings,
	core: CoreSettings,
	network: NetworkSettings,
	routing: RoutingSettings,
	dns: AppDnsSettings,
	sources: SourceSettings,
	speedTest: SpeedTestSettings,
	multiplexing: MultiplexingSettings,
	grpc: GrpcSettings,
	hysteria: HysteriaSettings,
	proxy: ProxySettings,
	shortcuts: ShortcutSettings,
};

export type AppUpdaterState = "ready" | "unconfigured" | "unsupported" | "error";

export type AppUpdaterStatus = {
	currentVersion: string,
	state: AppUpdaterState,
	message: string | null,
};

export type AppearanceSettings = {
	language: string,
	theme: ThemeMode,
};

export type AutostartPlatform = "windows" | "linux" | "macos" | "other";

export type AutostartStatus = {
	enabled: boolean,
	platform: AutostartPlatform,
	artifactKind: string | null,
	artifactPath: string | null,
	artifactName: string | null,
};

export type BehaviorSettings = {
	autostart: boolean,
	statistics: boolean,
	realtimeSpeed: boolean,
	/**
	 *  `None` means enabled (the default); optional so settings blobs saved by
	 *  older builds keep deserializing under `deny_unknown_fields`.
	 */
	autoCreateSubscriptionGroup?: boolean | null,
};

export type CertificateFetchRequest = {
	address: string,
	port: number,
	serverName: string | null,
	allowInsecure: boolean,
	includeChain: boolean,
};

export type CertificateFetchResult = {
	pem: string,
	sha256: string[],
	chainCount: number,
	warning: string | null,
};

export type ConfigSourceSettings = {
	geoSourceUrl: string | null,
	srsSourceUrl: string | null,
	routeRulesTemplateSourceUrl: string | null,
};

export type ConfigTemplateImportResult = {
	sources: ConfigSourceSettings,
	routingIds: string[],
	activeRoutingId: string | null,
	reusedExistingRouting: boolean,
};

export type ConfigTemplateSelection = { type: "default" } | { type: "custom"; sources: ConfigSourceSettings };

/**
 *  Hiddify-style top-level connection mode. A derived view over the two
 *  persisted primitives (system proxy type + TUN flag), never stored itself.
 */
export type ConnectionMode = 
/**  Local inbounds only; the OS proxy is cleared and TUN stays off. */
"proxyOnly" | 
/**  OS system proxy points at the local inbound (optionally via PAC). */
"systemProxy" | 
/**  TUN mode; all traffic is routed through the virtual interface. */
"vpn";

export type ConnectionModeStatus = {
	mode: ConnectionMode,
	pacEnabled: boolean,
	pacAvailable: boolean,
	vpnAvailable: boolean,
	/**
	 *  sing-box process rules only match traffic entering through TUN, so
	 *  per-app rules are effective only while `mode` is `Vpn`.
	 */
	processRulesEffective: boolean,
};

export type CoreSeedInstallResult = {
	coreType: CoreType,
	status: CoreSeedInstallStatus,
	installedFiles: string[],
};

export type CoreSeedInstallStatus = "installed" | "alreadyInstalled" | "seedMissing";

export type CoreSettings = {
	logEnabled: boolean,
	logLevel: string,
	muxEnabled: boolean,
	defaultAllowInsecure: boolean,
	defaultFingerprint: string,
	defaultUserAgent: string,
	sendThrough: string | null,
	bindInterface: string | null,
	fragmentEnabled: boolean,
	cacheFileEnabled: boolean,
};

export type CoreState = "disconnected" | "connecting" | "connected" | "disconnecting";

export type CoreStateEvent = {
	state: CoreState,
	activeProfileId: string | null,
	mainPid: number | null,
	prePid: number | null,
	runningCoreType: CoreType | null,
};

export type CoreType = "singBox";

export type DnsCommandError = {
	message: string,
	issues: DnsValidationIssue[],
};

export type DnsSettings = {
	useSystemHosts: boolean | null,
	addCommonHosts: boolean | null,
	fakeIp: boolean | null,
	globalFakeIp: boolean | null,
	blockBindingQuery: boolean | null,
	direct: string | null,
	remote: string | null,
	bootstrap: string | null,
	directStrategy: string | null,
	proxyStrategy: string | null,
	serveStale: boolean | null,
	parallelQuery: boolean | null,
	hosts: string | null,
	directExpectedIps: string | null,
};

export type DnsValidationIssue = {
	field: string,
	message: string,
};

export type ExportProfilesFormat = "shareLinks" | "shareLinksBase64" | "voyaBundle" | "clientConfig";

export type ExportProfilesRequest = {
	indexIds: string[],
	format: ExportProfilesFormat,
};

export type ExportProfilesResult = {
	text: string,
	count: number,
	format: ExportProfilesFormat,
};

export type GroupChildCandidate = {
	profileId: string,
	remarks: string,
	address: string,
	protocol: ProfileKind,
	subscriptionId: string | null,
	isGroup: boolean,
	selectable: boolean,
	reason: string | null,
};

export type GroupPreview = {
	validation: GroupValidation,
	singboxRoutes: GroupPreviewRoute[],
};

export type GroupPreviewRoute = {
	tag: string,
	kind: string,
	dialerProxy: string | null,
	downloadDialerProxy: string | null,
	detour: string | null,
	outbounds: string[],
};

export type GroupValidation = {
	valid: boolean,
	childProfileIds: string[],
	errors: string[],
	warnings: string[],
};

export type GrpcSettings = {
	idleTimeoutSeconds: number | null,
	healthCheckTimeoutSeconds: number | null,
	permitWithoutStream: boolean | null,
};

export type HysteriaSettings = {
	uploadMbps: number,
	downloadMbps: number,
	hopIntervalSeconds: number,
};

export type ImportProfilesResult = {
	imported: number,
	updated: number,
	skipped: number,
	parsed: number,
	filtered: number,
	deduped: number,
	failed: number,
	removedExisting: number,
	removedDuplicates: number,
	discardedNodeOverrides: number,
	subscriptionId: string | null,
	importedProfileIds: string[],
	updatedProfileIds: string[],
	messages: string[],
};

export type InboundSettings = {
	localPort: number,
	protocol: string,
	sniffingEnabled: boolean,
	lanConnectionsAllowed: boolean,
	separateLanPort: boolean,
	username: string,
	password: string,
	secondaryPortEnabled: boolean,
};

export type InvalidateEvent = {
	keys: QueryInvalidation[],
};

export type LoadStrategy = "leastPing" | "fallback" | "random" | "roundRobin" | "leastLoad";

export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

export type LogLineEvent = {
	id: number,
	level: LogLevel,
	line: string,
};

export type MissingCoreError = {
	message: string,
	coreType: CoreType,
	searchDir: string,
	candidates: string[],
	downloadUrl: string,
};

export type MoveAction = "top" | "up" | "down" | "bottom" | "position";

export type MultiplexingSettings = {
	protocol: string,
	maxConnections: number,
	padding: boolean | null,
};

export type NetworkSettings = {
	tun: TunSettings,
	systemProxy: SystemProxySettings,
	inbounds: InboundSettings[],
};

/**
 *  A running process or installed application offered by the per-app proxy
 *  picker; `process_name` is the executable basename sing-box matches on.
 */
export type ProcessCandidate = {
	displayName: string,
	processName: string,
	executablePath: string | null,
	source: ProcessCandidateSource,
};

export type ProcessCandidateSource = "runningProcess" | "installedApplication";

export type Profile = {
	id: string,
	subscriptionId: string | null,
	displayLog: boolean,
	remarks: string,
	protocol: ProfileProtocol,
	transport: ProfileTransport | null,
	tls: TlsSettings | null,
};

export type ProfileDedupeResult = {
	total: number,
	kept: number,
	removedProfileIds: string[],
};

export type ProfileKind = "vmess" | "custom" | "shadowsocks" | "socks" | "vless" | "trojan" | "hysteria2" | "tuic" | "wireGuard" | "http" | "anytls" | "naive" | "policyGroup" | "proxyChain";

export type ProfileListEntry = {
	profile: Profile,
	metrics: ProfileMetrics,
	traffic: ProfileTraffic,
	isActive: boolean,
};

export type ProfileMetrics = {
	delayMs: number,
	speedBytesPerSecond: number | null,
	sort: number,
	message: string | null,
	ipInfo: string | null,
};

export type ProfileProtocol = { kind: "vmess"; server: ServerEndpoint; uuid: string; cipher: string | null } | { kind: "custom"; source: string; filter: string | null } | { kind: "shadowsocks"; server: ServerEndpoint; password: string; method: string; udpOverTcp: boolean } | { kind: "socks"; server: ServerEndpoint; username: string; password: string } | { kind: "vless"; server: ServerEndpoint; uuid: string; flow: string | null; encryption: string | null } | { kind: "trojan"; server: ServerEndpoint; password: string } | { kind: "hysteria2"; server: ServerEndpoint; password: string; portHops: string | null; obfuscationPassword: string | null } | { kind: "tuic"; server: ServerEndpoint; uuid: string; password: string; congestionControl: string | null } | { kind: "wireGuard"; server: ServerEndpoint; privateKey: string; peerPublicKey: string | null; presharedKey: string | null; interfaceAddress: string | null; allowedIps: string | null; reserved: string | null; mtu: number | null } | { kind: "http"; server: ServerEndpoint; username: string; password: string } | { kind: "anytls"; server: ServerEndpoint; password: string } | { kind: "naive"; server: ServerEndpoint; username: string; password: string; quic: boolean; congestionControl: string | null; insecureConcurrency: number | null; udpOverTcp: boolean } | { kind: "policyGroup"; childProfileIds: string[]; sourceSubscriptionId: string | null; filter: string | null; strategy: LoadStrategy } | { kind: "proxyChain"; childProfileIds: string[] };

export type ProfileSortKey = "sort" | "protocol" | "remarks" | "address" | "port" | "transport" | "tls" | "delay" | "speed" | "ipInfo" | "subscriptionId";

export type ProfileTraffic = {
	totalUpload: number | null,
	totalDownload: number | null,
	todayUpload: number | null,
	todayDownload: number | null,
	date: number | null,
};

export type ProfileTransport = { kind: "tcp"; header: string | null; host: string | null; path: string | null } | { kind: "kcp"; header: string | null; seed: string | null; mtu: number | null } | { kind: "websocket"; host: string | null; path: string | null } | { kind: "httpUpgrade"; host: string | null; path: string | null } | { kind: "xhttp"; host: string | null; path: string | null; mode: string | null; extra: string | null } | { kind: "http2"; host: string | null; path: string | null } | { kind: "grpc"; authority: string | null; serviceName: string | null; mode: string | null } | { kind: "quic"; host: string | null; path: string | null };

export type ProxyConnectionItem = {
	id: string | null,
	network: string | null,
	connectionType: string | null,
	host: string,
	source: string,
	destination: string,
	upload: number | null,
	download: number | null,
	start: string,
	chains: string[],
	rule: string | null,
	rulePayload: string | null,
	process: string | null,
	processPath: string | null,
};

export type ProxyConnectionsSnapshot = {
	downloadTotal: number | null,
	uploadTotal: number | null,
	connections: ProxyConnectionItem[],
};

export type ProxyDelayTestResult = {
	name: string,
	delay: number | null,
	message: string | null,
};

export type ProxyGroup = {
	name: string,
	proxyType: string,
	now: string | null,
	nodes: ProxyNode[],
};

export type ProxyGroupsSnapshot = {
	groups: ProxyGroup[],
	trafficMode: TrafficMode,
};

export type ProxyMonitorState = "running" | "stopped" | "failed";

export type ProxyMonitorStatus = {
	state: ProxyMonitorState,
	running: boolean,
	stale: boolean,
	message: string | null,
};

export type ProxyNode = {
	name: string,
	proxyType: string,
	delay: number | null,
	delayLabel: string,
	udp: boolean,
	active: boolean,
	testable: boolean,
};

export type ProxySettings = {
	trafficMode: string,
	nodeSorting: number,
};

export type ProxyTrafficEvent = {
	up: number | null,
	down: number | null,
};

export type QrCodeImage = {
	mimeType: string,
	svg: string,
};

export type QrScanResult = {
	status: QrScanStatus,
	text: string | null,
	source: string,
	message: string | null,
};

export type QrScanStatus = "found" | "notFound" | "unavailable";

export type QueryInvalidation = {
	queryKey: string[],
	reason: string,
};

export type ResourceUpdateFile = {
	name: string,
	bytes: number,
	usedProxy: boolean,
};

export type Routing = Routing_Serialize | Routing_Deserialize;

export type RoutingRule = {
	id: string,
	kind: string | null,
	port: string | null,
	network: string | null,
	inboundTags: string[] | null,
	outbound: string | null,
	ip: string[] | null,
	domain: string[] | null,
	protocol: string[] | null,
	process: string[] | null,
	enabled: boolean,
	remarks: string | null,
	scope: RoutingRuleScope | null,
};

export type RoutingRuleScope = "all" | "routing" | "dns";

export type RoutingSettings = {
	domainStrategy: string,
	singboxDomainStrategy: string,
};

export type Routing_Deserialize = {
	id: string,
	remarks: string,
	sourceUrl: string,
	rules: RoutingRule[],
	enabled: boolean,
	locked: boolean,
	icon: string,
	singboxRulesetPath: string,
	domainStrategy: string,
	singboxDomainStrategy: string,
	sort: number,
};

export type Routing_Serialize = {
	id: string,
	remarks: string,
	sourceUrl: string,
	rules: RoutingRule[],
	enabled: boolean,
	locked: boolean,
	icon: string,
	singboxRulesetPath: string,
	domainStrategy: string,
	singboxDomainStrategy: string,
	sort: number,
	isActive: boolean,
};

export type RuntimeConnectionState = "disconnected" | "connected";

export type RuntimeStatusResponse = {
	state: RuntimeConnectionState,
	activeProfileId: string | null,
	mainPid: number | null,
	prePid: number | null,
	runningCoreType: CoreType | null,
};

export type ServerEndpoint = {
	address: string,
	port: number,
};

export type ServerStatItem = {
	indexId: string,
	totalUp: number | null,
	totalDown: number | null,
	todayUp: number | null,
	todayDown: number | null,
	dateNow: number | null,
};

export type ShellTabTarget = "profiles" | "proxyGroups" | "proxyConnections" | "logs";

export type ShortcutChord = {
	alt: boolean,
	control: boolean,
	shift: boolean,
	keyCode: number,
};

export type ShortcutSettings = {
	showWindowShortcut: ShortcutChord | null,
};

export type SourceSettings = {
	subscriptionConverter: string | null,
	geo: string | null,
	singboxRuleset: string | null,
	routingTemplate: string | null,
};

export type SpeedTestKind = "tcpConnect" | "latency" | "udp" | "download" | "mixed";

export type SpeedTestRequest = {
	kind: SpeedTestKind,
	target: SpeedTestTarget,
};

export type SpeedTestResult = {
	action: SpeedTestKind,
	indexId: string,
	delay: number | null,
	speed: number | null,
	message: string | null,
	ipInfo: string | null,
};

export type SpeedTestSettings = {
	timeoutSeconds: number,
	downloadUrl: string,
	latencyUrl: string,
	mixedConcurrency: number,
	ipLookupUrl: string,
	udpTarget: string,
	pageSize: number | null,
	delayIntervalMs: number | null,
};

export type SpeedTestTarget = { scope: "all" } | { scope: "profiles"; profileIds: string[] };

export type SpeedtestRunResult = {
	action: SpeedTestKind,
	cancelled: boolean,
	selectedCount: number,
	completedCount: number,
	results: SpeedTestResult[],
};

export type SpeedtestStatus = {
	running: boolean,
};

export type StatisticsSnapshot = {
	activeProfileId: string | null,
	proxyUploadBytesPerSecond: number | null,
	proxyDownloadBytesPerSecond: number | null,
	directUploadBytesPerSecond: number | null,
	directDownloadBytesPerSecond: number | null,
	uploadBytesPerSecond: number | null,
	downloadBytesPerSecond: number | null,
	serverStat: ServerStatItem | null,
};

export type Subscription = {
	id: string,
	remarks: string,
	url: string,
	additionalUrl: string,
	enabled: boolean,
	userAgent: string,
	sort: number,
	filter: string | null,
	converterTarget: string | null,
	preSocksPort: number | null,
	autoUpdateIntervalMinutes: number | null,
};

/**
 *  Usage metadata reported by the subscription server on the latest successful
 *  fetch (`subscription-userinfo` and `profile-title` response headers).
 */
export type SubscriptionMetadata = {
	subscriptionId: string,
	uploadBytes: number | null,
	downloadBytes: number | null,
	totalBytes: number | null,
	expireAt: number | null,
	lastUpdateAt: number | null,
	profileTitle: string | null,
};

export type SubscriptionUpdateResult = {
	updated: number,
	skipped: number,
	imported: number,
	removedExisting: number,
	messages: string[],
};

export type SysProxyChanged = {
	requestedMode: SysProxyMode,
	effectiveMode: SysProxyMode,
	pacAvailable: boolean,
	proxy: string | null,
};

export type SysProxyMode = "unchanged" | "forcedChange" | "forcedClear" | "pac";

export type SysProxyType = "forcedClear" | "forcedChange" | "unchanged" | "pac";

export type SystemProxySettings = {
	mode: string,
	exceptions: string,
	bypassLocal: boolean,
	advancedProtocol: string,
	customPacPath: string | null,
	customScriptPath: string | null,
};

export type SystemProxyStatusResponse = {
	requestedMode: SysProxyType,
	effectiveMode: SysProxyType,
	pacAvailable: boolean,
	proxy: string | null,
	exceptions: string,
	pacUrl: string | null,
};

export type ThemeMode = "system" | "light" | "dark";

export type TitleBarLayout = "windows" | "none";

export type TlsMode = "tls" | "reality";

export type TlsSettings = {
	mode: TlsMode,
	serverName: string | null,
	alpn: string[],
	realityPublicKey: string | null,
	realityShortId: string | null,
	realitySpiderX: string | null,
	mldsa65Verify: string | null,
	certificatePem: string | null,
	certificateSha256: string[],
	echConfig: string[],
	finalMask: string | null,
};

export type TrafficMode = "rule" | "global" | "direct" | "unchanged";

export type TrafficModeResponse = {
	mode: TrafficMode,
};

export type TransientStreamEvent = { kind: "logLine"; payload: LogLineEvent } | { kind: "coreState"; payload: CoreStateEvent } | { kind: "statistics"; payload: StatisticsSnapshot } | { kind: "sysProxyChanged"; payload: SysProxyChanged } | { kind: "tunChanged"; payload: TunChanged } | { kind: "proxyMonitorStatus"; payload: ProxyMonitorStatus } | { kind: "proxyTraffic"; payload: ProxyTrafficEvent } | { kind: "proxyConnections"; payload: ProxyConnectionsSnapshot } | { kind: "speedtestResult"; payload: SpeedTestResult };

export type TunBackend = "process" | "macosPacketTunnel" | "windowsService" | "unsupported";

export type TunChanged = {
	enabled: boolean,
	backend: TunBackend,
	providerState: TunProviderState,
	nativeComponentReady: boolean,
	lastProviderError: string | null,
};

export type TunPlatform = "windows" | "linux" | "macos" | "other";

export type TunPreflight = {
	platform: TunPlatform,
	state: TunPreflightState,
	notes: string[],
	routeRestoreNote: string,
	windowsCleanupDevices: string[],
};

export type TunPreflightState = "ready" | "needsElevation" | "manualCheck" | "unsupported";

export type TunProviderDiagnostics = {
	backend: TunBackend,
	containerPath: string | null,
	statusPath: string | null,
	logPath: string | null,
	packagingMode: string | null,
	expectedProviderPath: string | null,
	systemExtensionState: string | null,
	registrationPaths: string[],
	statusState: string | null,
	lastError: string | null,
	providerBundlePath: string | null,
	breadcrumbs: string[],
	providerLogTail: string[],
	hostLogTail: string[],
	message: string | null,
};

export type TunProviderState = "notApplicable" | "missingComponent" | "permissionRequired" | "stopped" | "starting" | "running" | "error";

export type TunSettings = {
	enabled: boolean,
	autoRoute: boolean,
	strictRoute: boolean,
	stack: string,
	mtu: number,
	ipv6Enabled: boolean,
	icmpRouting: string,
};

export type TunStatus = {
	enabled: boolean,
	backend: TunBackend,
	providerState: TunProviderState,
	allowEnableTun: boolean,
	requiresElevation: boolean,
	elevationGranted: boolean,
	needsVpnPermission: boolean,
	needsServiceInstall: boolean,
	nativeComponentReady: boolean,
	lastProviderError: string | null,
	providerPathMismatch: boolean,
	resolvedProviderPath: string | null,
	expectedProviderPath: string | null,
	restoreOnDisconnect: boolean,
	preflight: TunPreflight,
};

export type WindowChromeConfig = {
	titleBarLayout: TitleBarLayout,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

