pub mod commands;
pub mod events;
pub mod window;

use tauri_specta::{collect_commands, collect_events, Builder, Commands};

fn ipc_commands() -> Commands<tauri::Wry> {
    collect_commands![
        commands::load_ui_preferences,
        commands::load_app_settings,
        commands::get_settings_apply_status::<tauri::Wry>,
        commands::apply_pending_settings::<tauri::Wry>,
        commands::save_app_settings::<tauri::Wry>,
        commands::generate_qr_code,
        commands::scan_screen_qr,
        commands::read_clipboard_text,
        commands::tun_request_elevation,
        commands::connect_active_profile::<tauri::Wry>,
        commands::disconnect_core::<tauri::Wry>,
        commands::restart_core::<tauri::Wry>,
        commands::runtime_status,
        commands::system_proxy_status,
        commands::connection_mode_status,
        commands::set_connection_mode::<tauri::Wry>,
        commands::check_connection_ip,
        commands::resolve_close_request::<tauri::Wry>,
        commands::tun_status,
        commands::tun_provider_diagnostics,
        commands::set_tun_enabled::<tauri::Wry>,
        commands::load_dns_settings,
        commands::save_dns_settings::<tauri::Wry>,
        commands::list_profiles,
        commands::save_profile::<tauri::Wry>,
        commands::delete_profiles::<tauri::Wry>,
        commands::export_profile_share_links,
        commands::set_active_profile::<tauri::Wry>,
        commands::move_profile::<tauri::Wry>,
        commands::list_policy_groups,
        commands::save_policy_group::<tauri::Wry>,
        commands::delete_policy_groups::<tauri::Wry>,
        commands::set_active_policy_group::<tauri::Wry>,
        commands::select_policy_group_member::<tauri::Wry>,
        commands::policy_group_runtime,
        commands::test_policy_group_delay::<tauri::Wry>,
        commands::list_subscriptions,
        commands::list_subscription_metadata,
        commands::save_subscription::<tauri::Wry>,
        commands::delete_subscriptions::<tauri::Wry>,
        commands::import_profiles_from_text::<tauri::Wry>,
        commands::update_subscriptions::<tauri::Wry>,
        commands::list_routings,
        commands::save_routing::<tauri::Wry>,
        commands::delete_routings::<tauri::Wry>,
        commands::set_active_routing::<tauri::Wry>,
        commands::save_routing_rule::<tauri::Wry>,
        commands::delete_routing_rules::<tauri::Wry>,
        commands::move_routing_rule::<tauri::Wry>,
        commands::reset_routing_rules::<tauri::Wry>,
        commands::list_process_candidates,
        commands::proxy_list_connections,
        commands::proxy_close_connection::<tauri::Wry>,
        commands::proxy_set_traffic_mode::<tauri::Wry>,
        commands::proxy_start_monitor,
        commands::proxy_stop_monitor,
        commands::run_speedtest::<tauri::Wry>,
        commands::cancel_speedtest::<tauri::Wry>,
        commands::speedtest_status,
        commands::app_update_status::<tauri::Wry>,
        commands::update_geo_assets,
        commands::update_srs_assets,
        commands::install_core_seed,
        window::get_window_chrome_config,
        window::set_window_acrylic,
    ]
}

pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .typ::<voya_contracts::Profile>()
        .typ::<voya_contracts::ProfileKind>()
        .typ::<voya_contracts::ProfileProtocol>()
        .typ::<voya_contracts::ProfileTransport>()
        .typ::<voya_contracts::TlsSettings>()
        .typ::<voya_contracts::ProfileListEntry>()
        .typ::<voya_contracts::ProfileListing>()
        .typ::<voya_contracts::Subscription>()
        .typ::<voya_contracts::SubscriptionMetadata>()
        .typ::<voya_contracts::ImportProfilesResult>()
        .typ::<voya_contracts::SubscriptionUpdateResult>()
        .typ::<voya_contracts::Routing>()
        .typ::<voya_contracts::RoutingRule>()
        .typ::<voya_contracts::RoutingRuleScope>()
        .typ::<voya_contracts::MoveAction>()
        .typ::<voya_contracts::DnsSettings>()
        .typ::<voya_contracts::ValidationIssue>()
        .typ::<voya_contracts::ProxyConnectionsSnapshot>()
        .typ::<voya_contracts::ProxyConnectionItem>()
        .typ::<voya_contracts::ProxyMonitorState>()
        .typ::<voya_contracts::ProxyMonitorStatus>()
        .typ::<voya_contracts::SpeedtestResult>()
        .typ::<voya_contracts::SpeedtestRunResult>()
        .typ::<voya_contracts::SpeedtestStatus>()
        .typ::<voya_contracts::ResourceUpdateFile>()
        .typ::<voya_contracts::AppSettingsV1>()
        .typ::<voya_contracts::AppearanceSettings>()
        .typ::<voya_contracts::AutostartStatus>()
        .typ::<voya_contracts::AutostartPlatform>()
        .typ::<voya_contracts::QrCodeImage>()
        .typ::<voya_contracts::QrScanResult>()
        .typ::<voya_contracts::QrScanStatus>()
        .typ::<voya_contracts::ExportProfilesRequest>()
        .typ::<voya_contracts::ExportProfilesResult>()
        .typ::<voya_contracts::ExportProfilesFormat>()
        .typ::<voya_contracts::SpeedtestTarget>()
        .typ::<voya_contracts::SpeedtestRequest>()
        .typ::<voya_contracts::TrafficMode>()
        .typ::<voya_contracts::TrafficModeResponse>()
        .typ::<voya_contracts::TunStatus>()
        .typ::<voya_contracts::TunPreflight>()
        .typ::<voya_contracts::TunProviderDiagnostics>()
        .typ::<voya_contracts::ServerStatItem>()
        .typ::<voya_contracts::WindowChromeConfig>()
        .commands(ipc_commands())
        .events(collect_events![
            events::InvalidateEvent,
            events::TransientStreamEvent,
            events::AppEvent,
        ])
}
